/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   /nix/store/788mx070y81zjlg5ipcl0cra3afviw9k-gcc-wrapper-15.2.0/bin/gcc -c -w -fmax-errors=3 -pthread   -I/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib -I/mnt/temp/CodingMain/Tyr-Crypto/tests -o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@f..@f..@f..@f..@favk@ffgber@f3x4kjtpdeys4eln9k5yid90pdpclo8yw-avz-hajenccrq-2.2.4@favz@fyvo@fflfgrz@frkprcgvbaf.nim.c.o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@f..@f..@f..@f..@favk@ffgber@f3x4kjtpdeys4eln9k5yid90pdpclo8yw-avz-hajenccrq-2.2.4@favz@fyvo@fflfgrz@frkprcgvbaf.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_OverflowDefect__5CE1A8U9cGniHEIQeBrrggA tyObject_OverflowDefect__5CE1A8U9cGniHEIQeBrrggA;
typedef struct tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA;
typedef struct tyObject_ArithmeticDefect__B19cQZdl5aF78P6nqsMR0rg tyObject_ArithmeticDefect__B19cQZdl5aF78P6nqsMR0rg;
typedef struct tyObject_Defect__Nd4Y5abZD4gYJp7OjPazMw tyObject_Defect__Nd4Y5abZD4gYJp7OjPazMw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__lQYMoIzOpEqh2HdAFaxIkA tySequence__lQYMoIzOpEqh2HdAFaxIkA;
typedef struct tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content;
typedef struct tyObject_GcEnv__EbgK4YL36mkIoyirWn7g7w tyObject_GcEnv__EbgK4YL36mkIoyirWn7g7w;
typedef struct tyObject_CellSeq__8VNF7uy4bMUscautQXez0w tyObject_CellSeq__8VNF7uy4bMUscautQXez0w;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__ll4xbCks2hDjW8VBlTWNxQ tyObject_CellSeq__ll4xbCks2hDjW8VBlTWNxQ;
typedef struct tyTuple__Iru6auDKQ1oTx3Ldqa7bLg tyTuple__Iru6auDKQ1oTx3Ldqa7bLg;
typedef struct tyObject_RangeDefect__GEKjcwfErMQkG09aoBkAViQ tyObject_RangeDefect__GEKjcwfErMQkG09aoBkAViQ;
typedef struct tyObject_IndexDefect__Hhq9aUYzhSSLc005CAUivmw tyObject_IndexDefect__Hhq9aUYzhSSLc005CAUivmw;
typedef struct tyObject_IOError__9b23SqoPWL2x64iERQ7jedA tyObject_IOError__9b23SqoPWL2x64iERQ7jedA;
typedef struct tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A;
typedef struct tyObject_AssertionDefect__2T3Jbmc6trCng5ZNLDaxQg tyObject_AssertionDefect__2T3Jbmc6trCng5ZNLDaxQg;
typedef struct tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ;
typedef struct tyObject_DivByZeroDefect__iGiTq77Odim23eloE6REPA tyObject_DivByZeroDefect__iGiTq77Odim23eloE6REPA;
typedef struct tyObject_OSError__d4m3qF5JXx4IHjSIuo3MIA tyObject_OSError__d4m3qF5JXx4IHjSIuo3MIA;
typedef struct tyObject_NilAccessDefect__ifYN3jitdgvvFxr36FRubg tyObject_NilAccessDefect__ifYN3jitdgvvFxr36FRubg;
typedef struct tyObject_ObjectConversionDefect__UtXdBXS1UdtT5RvCN9bQ3dQ tyObject_ObjectConversionDefect__UtXdBXS1UdtT5RvCN9bQ3dQ;
typedef struct tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__lQYMoIzOpEqh2HdAFaxIkA {
  NI len; tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQYMoIzOpEqh2HdAFaxIkA trace;
	Exception* up;
};
struct tyObject_Defect__Nd4Y5abZD4gYJp7OjPazMw {
	Exception Sup;
};
struct tyObject_ArithmeticDefect__B19cQZdl5aF78P6nqsMR0rg {
	tyObject_Defect__Nd4Y5abZD4gYJp7OjPazMw Sup;
};
struct tyObject_OverflowDefect__5CE1A8U9cGniHEIQeBrrggA {
	tyObject_ArithmeticDefect__B19cQZdl5aF78P6nqsMR0rg Sup;
};
struct tyObject_CellSeq__8VNF7uy4bMUscautQXez0w {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__ll4xbCks2hDjW8VBlTWNxQ {
	NI len;
	NI cap;
	tyTuple__Iru6auDKQ1oTx3Ldqa7bLg* d;
};
struct tyObject_GcEnv__EbgK4YL36mkIoyirWn7g7w {
	tyObject_CellSeq__8VNF7uy4bMUscautQXez0w traceStack;
	tyObject_CellSeq__ll4xbCks2hDjW8VBlTWNxQ toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_RangeDefect__GEKjcwfErMQkG09aoBkAViQ {
	tyObject_Defect__Nd4Y5abZD4gYJp7OjPazMw Sup;
};
struct tyObject_IndexDefect__Hhq9aUYzhSSLc005CAUivmw {
	tyObject_Defect__Nd4Y5abZD4gYJp7OjPazMw Sup;
};
struct tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A {
	Exception Sup;
};
struct tyObject_IOError__9b23SqoPWL2x64iERQ7jedA {
	tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A Sup;
};
struct tyObject_AssertionDefect__2T3Jbmc6trCng5ZNLDaxQg {
	tyObject_Defect__Nd4Y5abZD4gYJp7OjPazMw Sup;
};
struct tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ {
	tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A Sup;
};
struct tyObject_DivByZeroDefect__iGiTq77Odim23eloE6REPA {
	tyObject_ArithmeticDefect__B19cQZdl5aF78P6nqsMR0rg Sup;
};
struct tyObject_OSError__d4m3qF5JXx4IHjSIuo3MIA {
	tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A Sup;
	NI32 errorCode;
};
struct tyObject_NilAccessDefect__ifYN3jitdgvvFxr36FRubg {
	tyObject_Defect__Nd4Y5abZD4gYJp7OjPazMw Sup;
};
struct tyObject_ObjectConversionDefect__UtXdBXS1UdtT5RvCN9bQ3dQ {
	tyObject_Defect__Nd4Y5abZD4gYJp7OjPazMw Sup;
};
struct tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content { NI cap; tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5266)(tyObject_OverflowDefect__5CE1A8U9cGniHEIQeBrrggA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___flfgrz_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__flfgrz_u3546)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA* s_p1, TNimTypeV2* desc_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fgqZnffregvbaf_u74)(tySequence__lQYMoIzOpEqh2HdAFaxIkA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5278)(tyObject_OverflowDefect__5CE1A8U9cGniHEIQeBrrggA* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__flfgrz_u3029)(tyObject_CellSeq__8VNF7uy4bMUscautQXez0w* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__flfgrz_u3037)(tyObject_CellSeq__8VNF7uy4bMUscautQXez0w* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u60)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u4793)(tyObject_RangeDefect__GEKjcwfErMQkG09aoBkAViQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u4805)(tyObject_RangeDefect__GEKjcwfErMQkG09aoBkAViQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u4862)(tyObject_IndexDefect__Hhq9aUYzhSSLc005CAUivmw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u4874)(tyObject_IndexDefect__Hhq9aUYzhSSLc005CAUivmw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u9033)(tyObject_IOError__9b23SqoPWL2x64iERQ7jedA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u9045)(tyObject_IOError__9b23SqoPWL2x64iERQ7jedA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u66)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fgqZnffregvbaf_u35)(tyObject_AssertionDefect__2T3Jbmc6trCng5ZNLDaxQg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___fgqZnffregvbaf_u47)(tyObject_AssertionDefect__2T3Jbmc6trCng5ZNLDaxQg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u68)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u8181)(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u8193)(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u70)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5332)(tyObject_DivByZeroDefect__iGiTq77Odim23eloE6REPA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5344)(tyObject_DivByZeroDefect__iGiTq77Odim23eloE6REPA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u72)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fgqZbfreebef_u60)(tyObject_OSError__d4m3qF5JXx4IHjSIuo3MIA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___fgqZbfreebef_u72)(tyObject_OSError__d4m3qF5JXx4IHjSIuo3MIA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u74)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5189)(tyObject_NilAccessDefect__ifYN3jitdgvvFxr36FRubg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5201)(tyObject_NilAccessDefect__ifYN3jitdgvvFxr36FRubg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u76)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5085)(tyObject_ObjectConversionDefect__UtXdBXS1UdtT5RvCN9bQ3dQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5097)(tyObject_ObjectConversionDefect__UtXdBXS1UdtT5RvCN9bQ3dQ* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__5CE1A8U9cGniHEIQeBrrggA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__GEKjcwfErMQkG09aoBkAViQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__Hhq9aUYzhSSLc005CAUivmw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__9b23SqoPWL2x64iERQ7jedA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__2T3Jbmc6trCng5ZNLDaxQg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__knMwTE9cBPqCO0qkZrysJgQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__iGiTq77Odim23eloE6REPA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__d4m3qF5JXx4IHjSIuo3MIA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__ifYN3jitdgvvFxr36FRubg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__UtXdBXS1UdtT5RvCN9bQ3dQ_;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4509;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[5] = {3701606400, 1285336064, 3726173440, 1607492864, 557122304};
N_LIB_PRIVATE TNimTypeV2 NTIv2__5CE1A8U9cGniHEIQeBrrggA_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u56, .size = sizeof(tyObject_OverflowDefect__5CE1A8U9cGniHEIQeBrrggA), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__5CE1A8U9cGniHEIQeBrrggA), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___flfgrz_u5278, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 3726173440, 1118008064};
N_LIB_PRIVATE TNimTypeV2 NTIv2__GEKjcwfErMQkG09aoBkAViQ_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u60, .size = sizeof(tyObject_RangeDefect__GEKjcwfErMQkG09aoBkAViQ), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__GEKjcwfErMQkG09aoBkAViQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)eqtrace___flfgrz_u4805, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[4] = {3701606400, 1285336064, 3726173440, 448614656};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Hhq9aUYzhSSLc005CAUivmw_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u62, .size = sizeof(tyObject_IndexDefect__Hhq9aUYzhSSLc005CAUivmw), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__Hhq9aUYzhSSLc005CAUivmw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)eqtrace___flfgrz_u4874, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[4] = {3701606400, 1285336064, 3966501376, 1842522624};
N_LIB_PRIVATE TNimTypeV2 NTIv2__9b23SqoPWL2x64iERQ7jedA_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u64, .size = sizeof(tyObject_IOError__9b23SqoPWL2x64iERQ7jedA), .align = (NI16) NIM_ALIGNOF(tyObject_IOError__9b23SqoPWL2x64iERQ7jedA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_7, .traceImpl = (void*)eqtrace___flfgrz_u9045, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_8[4] = {3701606400, 1285336064, 3726173440, 1036611072};
N_LIB_PRIVATE TNimTypeV2 NTIv2__2T3Jbmc6trCng5ZNLDaxQg_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u66, .size = sizeof(tyObject_AssertionDefect__2T3Jbmc6trCng5ZNLDaxQg), .align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__2T3Jbmc6trCng5ZNLDaxQg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_8, .traceImpl = (void*)eqtrace___fgqZnffregvbaf_u47, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_9[4] = {3701606400, 1285336064, 3966501376, 1932545024};
N_LIB_PRIVATE TNimTypeV2 NTIv2__knMwTE9cBPqCO0qkZrysJgQ_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u68, .size = sizeof(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), .align = (NI16) NIM_ALIGNOF(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_9, .traceImpl = (void*)eqtrace___flfgrz_u8193, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_10[5] = {3701606400, 1285336064, 3726173440, 1607492864, 1754508032};
N_LIB_PRIVATE TNimTypeV2 NTIv2__iGiTq77Odim23eloE6REPA_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u70, .size = sizeof(tyObject_DivByZeroDefect__iGiTq77Odim23eloE6REPA), .align = (NI16) NIM_ALIGNOF(tyObject_DivByZeroDefect__iGiTq77Odim23eloE6REPA), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_10, .traceImpl = (void*)eqtrace___flfgrz_u5344, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_11[4] = {3701606400, 1285336064, 3966501376, 2310514688};
N_LIB_PRIVATE TNimTypeV2 NTIv2__d4m3qF5JXx4IHjSIuo3MIA_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u72, .size = sizeof(tyObject_OSError__d4m3qF5JXx4IHjSIuo3MIA), .align = (NI16) NIM_ALIGNOF(tyObject_OSError__d4m3qF5JXx4IHjSIuo3MIA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_11, .traceImpl = (void*)eqtrace___fgqZbfreebef_u72, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_12[4] = {3701606400, 1285336064, 3726173440, 4128103936};
N_LIB_PRIVATE TNimTypeV2 NTIv2__ifYN3jitdgvvFxr36FRubg_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u74, .size = sizeof(tyObject_NilAccessDefect__ifYN3jitdgvvFxr36FRubg), .align = (NI16) NIM_ALIGNOF(tyObject_NilAccessDefect__ifYN3jitdgvvFxr36FRubg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_12, .traceImpl = (void*)eqtrace___flfgrz_u5201, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_13[4] = {3701606400, 1285336064, 3726173440, 3588031744};
N_LIB_PRIVATE TNimTypeV2 NTIv2__UtXdBXS1UdtT5RvCN9bQ3dQ_ = {.destructor = (void*)rttiDestroy__flfgrzZrkprcgvbaf_u76, .size = sizeof(tyObject_ObjectConversionDefect__UtXdBXS1UdtT5RvCN9bQ3dQ), .align = (NI16) NIM_ALIGNOF(tyObject_ObjectConversionDefect__UtXdBXS1UdtT5RvCN9bQ3dQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_13, .traceImpl = (void*)eqtrace___flfgrz_u5097, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2741;
	framePtr__flfgrz_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2741 = (*framePtr__flfgrz_u2741).prev;
}
static N_INLINE(NI, minuspercent___flfgrz_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/arithmetics.nim");
	nimlf_(364, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4509);
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicDyn", "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(512, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(513);	{
		tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(514);		nimlf_(58, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___flfgrz_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA*) (T5_));
		nimlf_(515, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(516);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__TzI3paKQY09cLjc9cmCvur3A_2;
			nimln_(519);			if (nimSubInt((*cell_1).rc, ((NI)16), &TM__TzI3paKQY09cLjc9cmCvur3A_2)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell_1).rc = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_2);
		}
LA6_: ;
		nimln_(521);		rememberCycle__flfgrz_u3546(result, cell_1, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5266)(tyObject_OverflowDefect__5CE1A8U9cGniHEIQeBrrggA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u5266(((tyObject_OverflowDefect__5CE1A8U9cGniHEIQeBrrggA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, add__flfgrz_u3029)(tyObject_CellSeq__8VNF7uy4bMUscautQXez0w* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	NI TM__TzI3paKQY09cLjc9cmCvur3A_4;
	nimfr_("add", "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/cellseqs_v2.nim");
{	nimlf_(28, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__flfgrz_u3037(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	if (nimAddInt((*s_p0).len, ((NI)1), &TM__TzI3paKQY09cLjc9cmCvur3A_4)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_4);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");
	nimlf_(136, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(137);	{
		tyObject_GcEnv__EbgK4YL36mkIoyirWn7g7w* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(138);		j_1 = ((tyObject_GcEnv__EbgK4YL36mkIoyirWn7g7w*) (env_p1));
		nimln_(139);		add__flfgrz_u3029((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5278)(tyObject_OverflowDefect__5CE1A8U9cGniHEIQeBrrggA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u4793)(tyObject_RangeDefect__GEKjcwfErMQkG09aoBkAViQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u60)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u4793(((tyObject_RangeDefect__GEKjcwfErMQkG09aoBkAViQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u4805)(tyObject_RangeDefect__GEKjcwfErMQkG09aoBkAViQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u4862)(tyObject_IndexDefect__Hhq9aUYzhSSLc005CAUivmw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u4862(((tyObject_IndexDefect__Hhq9aUYzhSSLc005CAUivmw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u4874)(tyObject_IndexDefect__Hhq9aUYzhSSLc005CAUivmw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u9033)(tyObject_IOError__9b23SqoPWL2x64iERQ7jedA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u64)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u9033(((tyObject_IOError__9b23SqoPWL2x64iERQ7jedA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u9045)(tyObject_IOError__9b23SqoPWL2x64iERQ7jedA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fgqZnffregvbaf_u35)(tyObject_AssertionDefect__2T3Jbmc6trCng5ZNLDaxQg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u66)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___fgqZnffregvbaf_u35(((tyObject_AssertionDefect__2T3Jbmc6trCng5ZNLDaxQg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___fgqZnffregvbaf_u47)(tyObject_AssertionDefect__2T3Jbmc6trCng5ZNLDaxQg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u8181)(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u68)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u8181(((tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u8193)(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5332)(tyObject_DivByZeroDefect__iGiTq77Odim23eloE6REPA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u70)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u5332(((tyObject_DivByZeroDefect__iGiTq77Odim23eloE6REPA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5344)(tyObject_DivByZeroDefect__iGiTq77Odim23eloE6REPA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___fgqZbfreebef_u60)(tyObject_OSError__d4m3qF5JXx4IHjSIuo3MIA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u72)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___fgqZbfreebef_u60(((tyObject_OSError__d4m3qF5JXx4IHjSIuo3MIA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___fgqZbfreebef_u72)(tyObject_OSError__d4m3qF5JXx4IHjSIuo3MIA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5189)(tyObject_NilAccessDefect__ifYN3jitdgvvFxr36FRubg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u74)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u5189(((tyObject_NilAccessDefect__ifYN3jitdgvvFxr36FRubg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5201)(tyObject_NilAccessDefect__ifYN3jitdgvvFxr36FRubg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___flfgrz_u5085)(tyObject_ObjectConversionDefect__UtXdBXS1UdtT5RvCN9bQ3dQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___fgqZnffregvbaf_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__flfgrzZrkprcgvbaf_u76)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___flfgrz_u5085(((tyObject_ObjectConversionDefect__UtXdBXS1UdtT5RvCN9bQ3dQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___flfgrz_u5097)(tyObject_ObjectConversionDefect__UtXdBXS1UdtT5RvCN9bQ3dQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
