/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   /nix/store/788mx070y81zjlg5ipcl0cra3afviw9k-gcc-wrapper-15.2.0/bin/gcc -c -w -fmax-errors=3 -pthread   -I/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib -I/mnt/temp/CodingMain/Tyr-Crypto/tests -o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fphfgbz_pelcgb@fnflzzrgevp@fcd@fqvyvguvhz@fcnenzf.nim.c.o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fphfgbz_pelcgb@fnflzzrgevp@fcd@fqvyvguvhz@fcnenzf.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_DilithiumParams__fB5BqeZ2VdLTHgzEfQcVGA tyObject_DilithiumParams__fB5BqeZ2VdLTHgzEfQcVGA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_DilithiumParams__fB5BqeZ2VdLTHgzEfQcVGA {
	NimStringV2 name;
	NI k;
	NI l;
	NI eta;
	NI tau;
	NI32 beta;
	NI32 gamma1;
	NI32 gamma2;
	NI omega;
	NI ctildeBytes;
	NI polyEtaPackedBytes;
	NI polyT1PackedBytes;
	NI polyT0PackedBytes;
	NI polyZPackedBytes;
	NI polyW1PackedBytes;
	NI publicKeyBytes;
	NI secretKeyBytes;
	NI signatureBytes;
};
typedef tyObject_DilithiumParams__fB5BqeZ2VdLTHgzEfQcVGA tyArray__CsgK0Vb0YKdlAak9aff5Zwg[3];
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___flfgrz_u2708)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__qB0oSDoMMY9cyyZ39ajnkYfA_2 = { 9 | NIM_STRLIT_FLAG, "ML-DSA-44" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__qB0oSDoMMY9cyyZ39ajnkYfA_3 = { 9 | NIM_STRLIT_FLAG, "ML-DSA-65" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__qB0oSDoMMY9cyyZ39ajnkYfA_4 = { 9 | NIM_STRLIT_FLAG, "ML-DSA-87" };
N_LIB_PRIVATE NIM_CONST tyArray__CsgK0Vb0YKdlAak9aff5Zwg dilithiumParamsTable__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZqvyvguvhzZcnenzf_u93 = {{{9, (NimStrPayload*)&TM__qB0oSDoMMY9cyyZ39ajnkYfA_2}, ((NI)4), ((NI)4), ((NI)2), ((NI)39), ((NI32)78), ((NI32)131072), ((NI32)95232), ((NI)80), ((NI)32), ((NI)96), ((NI)320), ((NI)416), ((NI)576), ((NI)192), ((NI)1312), ((NI)2560), ((NI)2420)}
,
{{9, (NimStrPayload*)&TM__qB0oSDoMMY9cyyZ39ajnkYfA_3}, ((NI)6), ((NI)5), ((NI)4), ((NI)49), ((NI32)196), ((NI32)524288), ((NI32)261888), ((NI)55), ((NI)48), ((NI)128), ((NI)320), ((NI)416), ((NI)640), ((NI)128), ((NI)1952), ((NI)4032), ((NI)3309)}
,
{{9, (NimStrPayload*)&TM__qB0oSDoMMY9cyyZ39ajnkYfA_4}, ((NI)8), ((NI)7), ((NI)2), ((NI)60), ((NI32)120), ((NI32)524288), ((NI32)261888), ((NI)75), ((NI)64), ((NI)96), ((NI)320), ((NI)416), ((NI)640), ((NI)128), ((NI)2592), ((NI)4896), ((NI)4627)}
}
;
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZqvyvguvhzZcnenzf_u50)(tyObject_DilithiumParams__fB5BqeZ2VdLTHgzEfQcVGA* dest_p0, tyObject_DilithiumParams__fB5BqeZ2VdLTHgzEfQcVGA* src_p1) {
	eqcopy___flfgrz_u2708((&(*dest_p0).name), (*src_p1).name);
	(*dest_p0).k = (*src_p1).k;
	(*dest_p0).l = (*src_p1).l;
	(*dest_p0).eta = (*src_p1).eta;
	(*dest_p0).tau = (*src_p1).tau;
	(*dest_p0).beta = (*src_p1).beta;
	(*dest_p0).gamma1 = (*src_p1).gamma1;
	(*dest_p0).gamma2 = (*src_p1).gamma2;
	(*dest_p0).omega = (*src_p1).omega;
	(*dest_p0).ctildeBytes = (*src_p1).ctildeBytes;
	(*dest_p0).polyEtaPackedBytes = (*src_p1).polyEtaPackedBytes;
	(*dest_p0).polyT1PackedBytes = (*src_p1).polyT1PackedBytes;
	(*dest_p0).polyT0PackedBytes = (*src_p1).polyT0PackedBytes;
	(*dest_p0).polyZPackedBytes = (*src_p1).polyZPackedBytes;
	(*dest_p0).polyW1PackedBytes = (*src_p1).polyW1PackedBytes;
	(*dest_p0).publicKeyBytes = (*src_p1).publicKeyBytes;
	(*dest_p0).secretKeyBytes = (*src_p1).secretKeyBytes;
	(*dest_p0).signatureBytes = (*src_p1).signatureBytes;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZqvyvguvhzZcnenzf_u47)(tyObject_DilithiumParams__fB5BqeZ2VdLTHgzEfQcVGA* dest_p0) {
	if ((*dest_p0).name.p && !((*dest_p0).name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).name.p);
}
}
