/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   /nix/store/788mx070y81zjlg5ipcl0cra3afviw9k-gcc-wrapper-15.2.0/bin/gcc -c -w -fmax-errors=3 -pthread   -I/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib -I/mnt/temp/CodingMain/Tyr-Crypto/tests -o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fphfgbz_pelcgb@fnflzzrgevp@fcd@ffcuvapf@fpbagrkg.nim.c.o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fphfgbz_pelcgb@fnflzzrgevp@fcd@ffcuvapf@fpbagrkg.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_SphincsCtx__ZqZSWx8EiFz3SY4zNwgGlA tyObject_SphincsCtx__ZqZSWx8EiFz3SY4zNwgGlA;
typedef NU8 tyArray__qtqsWM5aXmcpMIVmvq3kAA[16];
struct tyObject_SphincsCtx__ZqZSWx8EiFz3SY4zNwgGlA {
	tyArray__qtqsWM5aXmcpMIVmvq3kAA pubSeed;
	tyArray__qtqsWM5aXmcpMIVmvq3kAA skSeed;
};
static N_INLINE(void, copyMem__flfgrz_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, clearSensitivePlainData__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZfcuvapfZpbagrkg_u12)(tyObject_SphincsCtx__ZqZSWx8EiFz3SY4zNwgGlA* S_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4509;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__flfgrz_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2741;
	framePtr__flfgrz_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2741 = (*framePtr__flfgrz_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, initCtx__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZfcuvapfZpbagrkg_u6)(tyObject_SphincsCtx__ZqZSWx8EiFz3SY4zNwgGlA* ctx_p0, NU8* pkSeed_p1, NI pkSeed_p1Len_0, NU8* skSeed_p2, NI skSeed_p2Len_0) {
	nimfr_("initCtx", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/sphincs/context.nim");
{	nimlf_(14, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/sphincs/context.nim");	if (((NI)0) < 0 || ((NI)0) >= pkSeed_p1Len_0){ raiseIndexError2(((NI)0),pkSeed_p1Len_0-1); goto BeforeRet_;
	}
	copyMem__flfgrz_u1731(((void*) ((&(*ctx_p0).pubSeed[(((NI)0))- 0]))), ((void*) ((&pkSeed_p1[((NI)0)]))), ((NI)16));
	nimln_(15);	if (((NI)0) < 0 || ((NI)0) >= skSeed_p2Len_0){ raiseIndexError2(((NI)0),skSeed_p2Len_0-1); goto BeforeRet_;
	}
	copyMem__flfgrz_u1731(((void*) ((&(*ctx_p0).skSeed[(((NI)0))- 0]))), ((void*) ((&skSeed_p2[((NI)0)]))), ((NI)16));
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4509);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, clearCtx__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZfcuvapfZpbagrkg_u10)(tyObject_SphincsCtx__ZqZSWx8EiFz3SY4zNwgGlA* ctx_p0) {
NIM_BOOL* nimErr_;
	nimfr_("clearCtx", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/sphincs/context.nim");
{nimErr_ = nimErrorFlag();
	nimln_(20);	clearSensitivePlainData__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZfcuvapfZpbagrkg_u12(ctx_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
