/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   /nix/store/788mx070y81zjlg5ipcl0cra3afviw9k-gcc-wrapper-15.2.0/bin/gcc -c -w -fmax-errors=3 -pthread   -I/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib -I/mnt/temp/CodingMain/Tyr-Crypto/tests -o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fphfgbz_pelcgb@fflzzrgevp@ffun3@ffun3.nim.c.o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fphfgbz_pelcgb@fflzzrgevp@ffun3@ffun3.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <x86intrin.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ;
typedef struct tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__lQYMoIzOpEqh2HdAFaxIkA tySequence__lQYMoIzOpEqh2HdAFaxIkA;
typedef struct tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content;
typedef struct tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg;
typedef struct tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA;
typedef struct tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
typedef NU8 tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg;
typedef NU64 tyArray__ti0bWuszecJ2jGEjnJGmWg[25];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__lQYMoIzOpEqh2HdAFaxIkA {
  NI len; tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQYMoIzOpEqh2HdAFaxIkA trace;
	Exception* up;
};
struct tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A {
	Exception Sup;
};
struct tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ {
	tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A Sup;
};
typedef NU64 tyArray__13id4dQh19aNgtyEctXzOhA[24];
typedef NU8 tyArray__k5CantrhGuvnhsRWsHF5HA[168];
typedef NU8 tyArray__cdsir9aPB24hAk6k77P9b9bCA[8];
typedef NU8 tyArray__6qSULJVkHXjL25e22OI5AQ[136];
struct tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg {
	RootObj Sup;
	NI used0;
	tyArray__ti0bWuszecJ2jGEjnJGmWg S1;
	tyArray__6qSULJVkHXjL25e22OI5AQ blk2;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NU8* A_p0, NI A_p0Len_0, void* ClE_0);
void* ClE_0;
} tyProc__AmYyP09cVAnPVL9bYlOQH9chg;
typedef N_CLOSURE_PTR(void, TM__n2hmFo6ThUGbJBhyfD9ajFg_13) (NU8* A_p0, NI A_p0Len_0);
typedef N_CLOSURE_PTR(void, TM__n2hmFo6ThUGbJBhyfD9ajFg_14) (NU8* A_p0, NI A_p0Len_0);
typedef N_CLOSURE_PTR(void, TM__n2hmFo6ThUGbJBhyfD9ajFg_15) (NU8* A_p0, NI A_p0Len_0);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef N_CLOSURE_PTR(void, TM__n2hmFo6ThUGbJBhyfD9ajFg_16) (void);
struct tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA {
	NI rc;
	NI rootIdx;
};
typedef NU8 tyArray__ekVvh9bp9cVe7STNUL8R406w[1];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content { NI cap; tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, sha3Digest__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u679)(NU8* A_p0, NI A_p0Len_0, tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg v_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__fgqZflfenaq_u144)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(NI, sha3DigestBytes__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u19)(tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg v_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, sha3DigestInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u665)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0, tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg v_p2);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__flfgrzZzrzbel_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NI, sha3RateBytes__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u22)(tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg v_p0);
static N_INLINE(void, absorbBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u116)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0, NI o_p2, NI rateBytes_p3);
static N_INLINE(NU64, load64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u52)(NU8* A_p0, NI A_p0Len_0, NI o_p1);
N_LIB_PRIVATE N_NIMCALL(void, keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173)(NU64* S_p0);
static N_INLINE(NU64, rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458)(NU64 value_p0, NI shift_p1);
static N_INLINE(int, shiftTypeTo__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u486)(NI shift_p1);
N_LIB_PRIVATE N_NIMCALL(void, absorbFinalBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u322)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0, NI o_p2, NI rateBytes_p3);
static N_INLINE(void, absorbFinalBlockWithDomain__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u123)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0, NI o_p2, NI rateBytes_p3, NU8 domain_p4);
static N_INLINE(void, squeezeBytesInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u238)(tyArray__ti0bWuszecJ2jGEjnJGmWg S0_p0, NU8* dst_p1, NI dst_p1Len_0, NI rateBytes_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, squeezeBytesState__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u193)(NU64* S_p0, NU8* dst_p1, NI dst_p1Len_0, NI rateBytes_p2);
static N_INLINE(void, store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84)(NU8* A_p0, NI A_p0Len_0, NI o_p1, NU64 v_p2);
N_LIB_PRIVATE N_NIMCALL(tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg, sha3VariantFromOutLen__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u25)(NI outLen_p0);
N_LIB_PRIVATE N_NIMCALL(void, shake128Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u190)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0);
static N_INLINE(void, shake128AbsorbOnce__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u703)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0);
static N_INLINE(void, absorbFinalPartsWithDomain__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u348)(NU64* S_p0, NI rateBytes_p1, NU8 domain_p2, NU8* A_p3, NI A_p3Len_0);
static N_INLINE(void, absorbPartState__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u327)(NU64* S_p0, NU8* tail_p1, NI* tailLen_p2, NU8* A_p3, NI A_p3Len_0, NI rateBytes_p4);
N_LIB_PRIVATE N_NIMCALL(void, shake256Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u175)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0);
static N_INLINE(void, shake256AbsorbOnce__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u706)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0);
static N_INLINE(void, shake128SqueezeBlocksIntoUnchecked__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u714)(NU64* S_p0, NU8* dst_p1, NI dst_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(void, shake256ChunksInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u767)(NU8* dst_p0, NI dst_p0Len_0, NU8* A0_p1, NI A0_p1Len_0, NU8* A1_p2, NI A1_p2Len_0, NU8* A2_p3, NI A2_p3Len_0);
N_LIB_PRIVATE N_CLOSURE(void, absorbPartialChunk__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u775)(NU8* A_p0, NI A_p0Len_0, void* ClE_0);
static N_INLINE(void, copyMem__flfgrz_u1731)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_CLOSURE(void, finalizePartial__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u826)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u998)(tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___flfgrz_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__flfgrz_u3546)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
extern TNimTypeV2 NTIv2__knMwTE9cBPqCO0qkZrysJgQ_;
static const struct {
  NI cap; NIM_CHAR data[48+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_2 = { 48 | NIM_STRLIT_FLAG, "sha3 output buffer length does not match variant" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_3 = {48, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_2};
static const struct {
  NI cap; NIM_CHAR data[51+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_4 = { 51 | NIM_STRLIT_FLAG, "sha3 output length must be one of 28, 32, 48, or 64" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_5 = {51, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_4};
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_6 = { 35 | NIM_STRLIT_FLAG, "shake128 output length must be >= 0" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_7 = {35, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_6};
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_8 = { 35 | NIM_STRLIT_FLAG, "shake256 output length must be >= 0" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_9 = {35, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_8};
static const struct {
  NI cap; NIM_CHAR data[56+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_10 = { 56 | NIM_STRLIT_FLAG, "shake128 block squeeze requires a whole number of blocks" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_11 = {56, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_10};
N_LIB_PRIVATE TNimTypeV2 NTIv2__VBn7z1gkJnsFECAXuYH8Kg_;
N_LIB_PRIVATE NIM_CONST tyArray__13id4dQh19aNgtyEctXzOhA keccakRoundConstants__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u17 = {1ULL,
32898ULL,
9223372036854808714ULL,
9223372039002292224ULL,
32907ULL,
2147483649ULL,
9223372039002292353ULL,
9223372036854808585ULL,
138ULL,
136ULL,
2147516425ULL,
2147483658ULL,
2147516555ULL,
9223372036854775947ULL,
9223372036854808713ULL,
9223372036854808579ULL,
9223372036854808578ULL,
9223372036854775936ULL,
32778ULL,
9223372039002259466ULL,
9223372039002292353ULL,
9223372036854808704ULL,
2147483649ULL,
9223372039002292232ULL}
;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4509;
static NIM_CONST NU32 TM__n2hmFo6ThUGbJBhyfD9ajFg_12[2] = {3701606400, 435932928};
N_LIB_PRIVATE TNimTypeV2 NTIv2__VBn7z1gkJnsFECAXuYH8Kg_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg), .align = (NI16) NIM_ALIGNOF(tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg), .depth = 1, .display = TM__n2hmFo6ThUGbJBhyfD9ajFg_12, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2741;
	framePtr__flfgrz_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2741 = (*framePtr__flfgrz_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, sha3DigestBytes__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u19)(tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg v_p0) {
	NI result;
	nimfr_("sha3DigestBytes", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
	nimlf_(274, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");	switch (v_p0) {
	case ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)0):
	{
		nimln_(276);		result = ((NI)28);
	}
	break;
	case ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)1):
	{
		nimln_(278);		result = ((NI)32);
	}
	break;
	case ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)2):
	{
		nimln_(280);		result = ((NI)48);
	}
	break;
	case ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)3):
	{
		nimln_(282);		result = ((NI)64);
	}
	break;
	default: __builtin_unreachable();
	}
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__flfgrzZzrzbel_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4509);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__flfgrzZzrzbel_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, sha3RateBytes__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u22)(tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg v_p0) {
	NI result;
	nimfr_("sha3RateBytes", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
	nimln_(286);	switch (v_p0) {
	case ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)0):
	{
		nimln_(288);		result = ((NI)144);
	}
	break;
	case ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)1):
	{
		nimln_(290);		result = ((NI)136);
	}
	break;
	case ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)2):
	{
		nimln_(292);		result = ((NI)104);
	}
	break;
	case ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)3):
	{
		nimln_(294);		result = ((NI)72);
	}
	break;
	default: __builtin_unreachable();
	}
	popFrame();
	return result;
}
static N_INLINE(NU64, load64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u52)(NU8* A_p0, NI A_p0Len_0, NI o_p1) {
	NU64 result;
	nimfr_("load64Le", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
	nimln_(320);	nimln_(327);	nimln_(326);	nimln_(325);	nimln_(324);	nimln_(323);	nimln_(322);	nimln_(321);	nimln_(322);	nimln_(323);	nimln_(324);	nimln_(325);	nimln_(326);	nimln_(327);	nimln_(328);	result = (NU64)((NU64)((NU64)((NU64)((NU64)((NU64)((NU64)(((NU64) (A_p0[o_p1])) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)1))]))) << (NU64)(((NI)8)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)2))]))) << (NU64)(((NI)16)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)3))]))) << (NU64)(((NI)24)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)4))]))) << (NU64)(((NI)32)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)5))]))) << (NU64)(((NI)40)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)6))]))) << (NU64)(((NI)48)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)7))]))) << (NU64)(((NI)56))));
	popFrame();
	return result;
}
static N_INLINE(void, absorbBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u116)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0, NI o_p2, NI rateBytes_p3) {
	NI lane_1;
	NI laneCount_1;
NIM_BOOL* nimErr_;
	nimfr_("absorbBlock", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(342);	lane_1 = ((NI)0);
	nimln_(343);	laneCount_1 = ((NI)0);
	nimln_(344);	laneCount_1 = (NI)(rateBytes_p3 / ((NI)8));
	nimln_(345);	lane_1 = ((NI)0);
	{
		nimln_(346);		while (1) {
			NU64 T3_;
			if (!(lane_1 < laneCount_1)) goto LA2;
			nimln_(347);			T3_ = (NU64)0;
			T3_ = load64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u52(A_p1, A_p1Len_0, (NI)(o_p2 + (NI)(lane_1 * ((NI)8))));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			S_p0[(lane_1)- 0] = (NU64)(S_p0[(lane_1)- 0] ^ T3_);
			nimln_(348);			lane_1 = (NI)(lane_1 + ((NI)1));
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(int, shiftTypeTo__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u486)(NI shift_p1) {
	int result;
	nimfr_("shiftTypeTo", "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/bitops.nim");
{	result = (int)0;
	nimlf_(771, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/bitops.nim");	if ((shift_p1) < ((int)(-2147483647 -1)) || (shift_p1) > ((int)2147483647)){ raiseRangeErrorI(shift_p1, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
	}
	result = ((int) (shift_p1));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NU64, rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458)(NU64 value_p0, NI shift_p1) {
	NU64 result;
	int T1_;
	unsigned long long T2_;
NIM_BOOL* nimErr_;
	nimfr_("rotateLeftBits", "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/bitops.nim");
{nimErr_ = nimErrorFlag();
	result = (NU64)0;
	nimln_(786);	nimln_(807);	T1_ = (int)0;
	T1_ = shiftTypeTo__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u486(shift_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (unsigned long long)0;
	T2_ = __rolq(((unsigned long long) (value_p0)), T1_);
	result = ((NU64) (T2_));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173)(NU64* S_p0) {
	NU64 a0_1;
	NU64 a1_1;
	NU64 a2_1;
	NU64 a3_1;
	NU64 a4_1;
	NU64 a5_1;
	NU64 a6_1;
	NU64 a7_1;
	NU64 a8_1;
	NU64 a9_1;
	NU64 a10_1;
	NU64 a11_1;
	NU64 a12_1;
	NU64 a13_1;
	NU64 a14_1;
	NU64 a15_1;
	NU64 a16_1;
	NU64 a17_1;
	NU64 a18_1;
	NU64 a19_1;
	NU64 a20_1;
	NU64 a21_1;
	NU64 a22_1;
	NU64 a23_1;
	NU64 a24_1;
	NU64 c0_1;
	NU64 c1_1;
	NU64 c2_1;
	NU64 c3_1;
	NU64 c4_1;
	NU64 d0_1;
	NU64 d1_1;
	NU64 d2_1;
	NU64 d3_1;
	NU64 d4_1;
	NU64 b0_1;
	NU64 b1_1;
	NU64 b2_1;
	NU64 b3_1;
	NU64 b4_1;
	NU64 b5_1;
	NU64 b6_1;
	NU64 b7_1;
	NU64 b8_1;
	NU64 b9_1;
	NU64 b10_1;
	NU64 b11_1;
	NU64 b12_1;
	NU64 b13_1;
	NU64 b14_1;
	NU64 b15_1;
	NU64 b16_1;
	NU64 b17_1;
	NU64 b18_1;
	NU64 b19_1;
	NU64 b20_1;
	NU64 b21_1;
	NU64 b22_1;
	NU64 b23_1;
	NU64 b24_1;
	NI round_1;
NIM_BOOL* nimErr_;
	nimfr_("keccakF1600Ref", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(528, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");	a0_1 = S_p0[(((NI)0))- 0];
	nimln_(529);	a1_1 = S_p0[(((NI)1))- 0];
	nimln_(530);	a2_1 = S_p0[(((NI)2))- 0];
	nimln_(531);	a3_1 = S_p0[(((NI)3))- 0];
	nimln_(532);	a4_1 = S_p0[(((NI)4))- 0];
	nimln_(533);	a5_1 = S_p0[(((NI)5))- 0];
	nimln_(534);	a6_1 = S_p0[(((NI)6))- 0];
	nimln_(535);	a7_1 = S_p0[(((NI)7))- 0];
	nimln_(536);	a8_1 = S_p0[(((NI)8))- 0];
	nimln_(537);	a9_1 = S_p0[(((NI)9))- 0];
	nimln_(538);	a10_1 = S_p0[(((NI)10))- 0];
	nimln_(539);	a11_1 = S_p0[(((NI)11))- 0];
	nimln_(540);	a12_1 = S_p0[(((NI)12))- 0];
	nimln_(541);	a13_1 = S_p0[(((NI)13))- 0];
	nimln_(542);	a14_1 = S_p0[(((NI)14))- 0];
	nimln_(543);	a15_1 = S_p0[(((NI)15))- 0];
	nimln_(544);	a16_1 = S_p0[(((NI)16))- 0];
	nimln_(545);	a17_1 = S_p0[(((NI)17))- 0];
	nimln_(546);	a18_1 = S_p0[(((NI)18))- 0];
	nimln_(547);	a19_1 = S_p0[(((NI)19))- 0];
	nimln_(548);	a20_1 = S_p0[(((NI)20))- 0];
	nimln_(549);	a21_1 = S_p0[(((NI)21))- 0];
	nimln_(550);	a22_1 = S_p0[(((NI)22))- 0];
	nimln_(551);	a23_1 = S_p0[(((NI)23))- 0];
	nimln_(552);	a24_1 = S_p0[(((NI)24))- 0];
	nimln_(553);	c0_1 = 0ULL;
	nimln_(554);	c1_1 = 0ULL;
	nimln_(555);	c2_1 = 0ULL;
	nimln_(556);	c3_1 = 0ULL;
	nimln_(557);	c4_1 = 0ULL;
	nimln_(558);	d0_1 = 0ULL;
	nimln_(559);	d1_1 = 0ULL;
	nimln_(560);	d2_1 = 0ULL;
	nimln_(561);	d3_1 = 0ULL;
	nimln_(562);	d4_1 = 0ULL;
	nimln_(563);	b0_1 = 0ULL;
	nimln_(564);	b1_1 = 0ULL;
	nimln_(565);	b2_1 = 0ULL;
	nimln_(566);	b3_1 = 0ULL;
	nimln_(567);	b4_1 = 0ULL;
	nimln_(568);	b5_1 = 0ULL;
	nimln_(569);	b6_1 = 0ULL;
	nimln_(570);	b7_1 = 0ULL;
	nimln_(571);	b8_1 = 0ULL;
	nimln_(572);	b9_1 = 0ULL;
	nimln_(573);	b10_1 = 0ULL;
	nimln_(574);	b11_1 = 0ULL;
	nimln_(575);	b12_1 = 0ULL;
	nimln_(576);	b13_1 = 0ULL;
	nimln_(577);	b14_1 = 0ULL;
	nimln_(578);	b15_1 = 0ULL;
	nimln_(579);	b16_1 = 0ULL;
	nimln_(580);	b17_1 = 0ULL;
	nimln_(581);	b18_1 = 0ULL;
	nimln_(582);	b19_1 = 0ULL;
	nimln_(583);	b20_1 = 0ULL;
	nimln_(584);	b21_1 = 0ULL;
	nimln_(585);	b22_1 = 0ULL;
	nimln_(586);	b23_1 = 0ULL;
	nimln_(587);	b24_1 = 0ULL;
	nimln_(588);	round_1 = ((NI)0);
	nimln_(589);	round_1 = ((NI)0);
	{
		nimln_(590);		while (1) {
			NU64 T3_;
			NU64 T4_;
			NU64 T5_;
			NU64 T6_;
			NU64 T7_;
			if (!(round_1 < ((NI)24))) goto LA2;
			nimln_(591);			c0_1 = (NU64)((NU64)((NU64)((NU64)(a0_1 ^ a5_1) ^ a10_1) ^ a15_1) ^ a20_1);
			nimln_(592);			c1_1 = (NU64)((NU64)((NU64)((NU64)(a1_1 ^ a6_1) ^ a11_1) ^ a16_1) ^ a21_1);
			nimln_(593);			c2_1 = (NU64)((NU64)((NU64)((NU64)(a2_1 ^ a7_1) ^ a12_1) ^ a17_1) ^ a22_1);
			nimln_(594);			c3_1 = (NU64)((NU64)((NU64)((NU64)(a3_1 ^ a8_1) ^ a13_1) ^ a18_1) ^ a23_1);
			nimln_(595);			c4_1 = (NU64)((NU64)((NU64)((NU64)(a4_1 ^ a9_1) ^ a14_1) ^ a19_1) ^ a24_1);
			nimln_(597);			T3_ = (NU64)0;
			T3_ = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(c1_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			d0_1 = (NU64)(c4_1 ^ T3_);
			nimln_(598);			T4_ = (NU64)0;
			T4_ = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(c2_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			d1_1 = (NU64)(c0_1 ^ T4_);
			nimln_(599);			T5_ = (NU64)0;
			T5_ = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(c3_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			d2_1 = (NU64)(c1_1 ^ T5_);
			nimln_(600);			T6_ = (NU64)0;
			T6_ = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(c4_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			d3_1 = (NU64)(c2_1 ^ T6_);
			nimln_(601);			T7_ = (NU64)0;
			T7_ = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(c0_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			d4_1 = (NU64)(c3_1 ^ T7_);
			nimln_(603);			a0_1 = (NU64)(a0_1 ^ d0_1);
			nimln_(604);			a5_1 = (NU64)(a5_1 ^ d0_1);
			nimln_(605);			a10_1 = (NU64)(a10_1 ^ d0_1);
			nimln_(606);			a15_1 = (NU64)(a15_1 ^ d0_1);
			nimln_(607);			a20_1 = (NU64)(a20_1 ^ d0_1);
			nimln_(608);			a1_1 = (NU64)(a1_1 ^ d1_1);
			nimln_(609);			a6_1 = (NU64)(a6_1 ^ d1_1);
			nimln_(610);			a11_1 = (NU64)(a11_1 ^ d1_1);
			nimln_(611);			a16_1 = (NU64)(a16_1 ^ d1_1);
			nimln_(612);			a21_1 = (NU64)(a21_1 ^ d1_1);
			nimln_(613);			a2_1 = (NU64)(a2_1 ^ d2_1);
			nimln_(614);			a7_1 = (NU64)(a7_1 ^ d2_1);
			nimln_(615);			a12_1 = (NU64)(a12_1 ^ d2_1);
			nimln_(616);			a17_1 = (NU64)(a17_1 ^ d2_1);
			nimln_(617);			a22_1 = (NU64)(a22_1 ^ d2_1);
			nimln_(618);			a3_1 = (NU64)(a3_1 ^ d3_1);
			nimln_(619);			a8_1 = (NU64)(a8_1 ^ d3_1);
			nimln_(620);			a13_1 = (NU64)(a13_1 ^ d3_1);
			nimln_(621);			a18_1 = (NU64)(a18_1 ^ d3_1);
			nimln_(622);			a23_1 = (NU64)(a23_1 ^ d3_1);
			nimln_(623);			a4_1 = (NU64)(a4_1 ^ d4_1);
			nimln_(624);			a9_1 = (NU64)(a9_1 ^ d4_1);
			nimln_(625);			a14_1 = (NU64)(a14_1 ^ d4_1);
			nimln_(626);			a19_1 = (NU64)(a19_1 ^ d4_1);
			nimln_(627);			a24_1 = (NU64)(a24_1 ^ d4_1);
			nimln_(629);			b0_1 = a0_1;
			nimln_(630);			b10_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a1_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(631);			b20_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a2_1, ((NI)62));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(632);			b5_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a3_1, ((NI)28));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(633);			b15_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a4_1, ((NI)27));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(634);			b16_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a5_1, ((NI)36));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(635);			b1_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a6_1, ((NI)44));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(636);			b11_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a7_1, ((NI)6));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(637);			b21_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a8_1, ((NI)55));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(638);			b6_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a9_1, ((NI)20));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(639);			b7_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a10_1, ((NI)3));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(640);			b17_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a11_1, ((NI)10));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(641);			b2_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a12_1, ((NI)43));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(642);			b12_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a13_1, ((NI)25));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(643);			b22_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a14_1, ((NI)39));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(644);			b23_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a15_1, ((NI)41));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(645);			b8_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a16_1, ((NI)45));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(646);			b18_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a17_1, ((NI)15));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(647);			b3_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a18_1, ((NI)21));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(648);			b13_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a19_1, ((NI)8));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(649);			b14_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a20_1, ((NI)18));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(650);			b24_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a21_1, ((NI)2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(651);			b9_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a22_1, ((NI)61));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(652);			b19_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a23_1, ((NI)56));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(653);			b4_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u458(a24_1, ((NI)14));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(655);			nimln_(521);			a0_1 = (NU64)(b0_1 ^ (NU64)((NU64)((NU64) ~(b1_1)) & b2_1));
			nimln_(655);			nimln_(522);			a1_1 = (NU64)(b1_1 ^ (NU64)((NU64)((NU64) ~(b2_1)) & b3_1));
			nimln_(655);			nimln_(523);			a2_1 = (NU64)(b2_1 ^ (NU64)((NU64)((NU64) ~(b3_1)) & b4_1));
			nimln_(655);			nimln_(524);			a3_1 = (NU64)(b3_1 ^ (NU64)((NU64)((NU64) ~(b4_1)) & b0_1));
			nimln_(655);			nimln_(525);			a4_1 = (NU64)(b4_1 ^ (NU64)((NU64)((NU64) ~(b0_1)) & b1_1));
			nimln_(656);			nimln_(521);			a5_1 = (NU64)(b5_1 ^ (NU64)((NU64)((NU64) ~(b6_1)) & b7_1));
			nimln_(656);			nimln_(522);			a6_1 = (NU64)(b6_1 ^ (NU64)((NU64)((NU64) ~(b7_1)) & b8_1));
			nimln_(656);			nimln_(523);			a7_1 = (NU64)(b7_1 ^ (NU64)((NU64)((NU64) ~(b8_1)) & b9_1));
			nimln_(656);			nimln_(524);			a8_1 = (NU64)(b8_1 ^ (NU64)((NU64)((NU64) ~(b9_1)) & b5_1));
			nimln_(656);			nimln_(525);			a9_1 = (NU64)(b9_1 ^ (NU64)((NU64)((NU64) ~(b5_1)) & b6_1));
			nimln_(657);			nimln_(521);			a10_1 = (NU64)(b10_1 ^ (NU64)((NU64)((NU64) ~(b11_1)) & b12_1));
			nimln_(657);			nimln_(522);			a11_1 = (NU64)(b11_1 ^ (NU64)((NU64)((NU64) ~(b12_1)) & b13_1));
			nimln_(657);			nimln_(523);			a12_1 = (NU64)(b12_1 ^ (NU64)((NU64)((NU64) ~(b13_1)) & b14_1));
			nimln_(657);			nimln_(524);			a13_1 = (NU64)(b13_1 ^ (NU64)((NU64)((NU64) ~(b14_1)) & b10_1));
			nimln_(657);			nimln_(525);			a14_1 = (NU64)(b14_1 ^ (NU64)((NU64)((NU64) ~(b10_1)) & b11_1));
			nimln_(658);			nimln_(521);			a15_1 = (NU64)(b15_1 ^ (NU64)((NU64)((NU64) ~(b16_1)) & b17_1));
			nimln_(658);			nimln_(522);			a16_1 = (NU64)(b16_1 ^ (NU64)((NU64)((NU64) ~(b17_1)) & b18_1));
			nimln_(658);			nimln_(523);			a17_1 = (NU64)(b17_1 ^ (NU64)((NU64)((NU64) ~(b18_1)) & b19_1));
			nimln_(658);			nimln_(524);			a18_1 = (NU64)(b18_1 ^ (NU64)((NU64)((NU64) ~(b19_1)) & b15_1));
			nimln_(658);			nimln_(525);			a19_1 = (NU64)(b19_1 ^ (NU64)((NU64)((NU64) ~(b15_1)) & b16_1));
			nimln_(659);			nimln_(521);			a20_1 = (NU64)(b20_1 ^ (NU64)((NU64)((NU64) ~(b21_1)) & b22_1));
			nimln_(659);			nimln_(522);			a21_1 = (NU64)(b21_1 ^ (NU64)((NU64)((NU64) ~(b22_1)) & b23_1));
			nimln_(659);			nimln_(523);			a22_1 = (NU64)(b22_1 ^ (NU64)((NU64)((NU64) ~(b23_1)) & b24_1));
			nimln_(659);			nimln_(524);			a23_1 = (NU64)(b23_1 ^ (NU64)((NU64)((NU64) ~(b24_1)) & b20_1));
			nimln_(659);			nimln_(525);			a24_1 = (NU64)(b24_1 ^ (NU64)((NU64)((NU64) ~(b20_1)) & b21_1));
			nimln_(661);			a0_1 = (NU64)(a0_1 ^ keccakRoundConstants__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u17[(round_1)- 0]);
			nimln_(662);			round_1 = (NI)(round_1 + ((NI)1));
		} LA2: ;
	}
	nimln_(664);	S_p0[(((NI)0))- 0] = a0_1;
	nimln_(665);	S_p0[(((NI)1))- 0] = a1_1;
	nimln_(666);	S_p0[(((NI)2))- 0] = a2_1;
	nimln_(667);	S_p0[(((NI)3))- 0] = a3_1;
	nimln_(668);	S_p0[(((NI)4))- 0] = a4_1;
	nimln_(669);	S_p0[(((NI)5))- 0] = a5_1;
	nimln_(670);	S_p0[(((NI)6))- 0] = a6_1;
	nimln_(671);	S_p0[(((NI)7))- 0] = a7_1;
	nimln_(672);	S_p0[(((NI)8))- 0] = a8_1;
	nimln_(673);	S_p0[(((NI)9))- 0] = a9_1;
	nimln_(674);	S_p0[(((NI)10))- 0] = a10_1;
	nimln_(675);	S_p0[(((NI)11))- 0] = a11_1;
	nimln_(676);	S_p0[(((NI)12))- 0] = a12_1;
	nimln_(677);	S_p0[(((NI)13))- 0] = a13_1;
	nimln_(678);	S_p0[(((NI)14))- 0] = a14_1;
	nimln_(679);	S_p0[(((NI)15))- 0] = a15_1;
	nimln_(680);	S_p0[(((NI)16))- 0] = a16_1;
	nimln_(681);	S_p0[(((NI)17))- 0] = a17_1;
	nimln_(682);	S_p0[(((NI)18))- 0] = a18_1;
	nimln_(683);	S_p0[(((NI)19))- 0] = a19_1;
	nimln_(684);	S_p0[(((NI)20))- 0] = a20_1;
	nimln_(685);	S_p0[(((NI)21))- 0] = a21_1;
	nimln_(686);	S_p0[(((NI)22))- 0] = a22_1;
	nimln_(687);	S_p0[(((NI)23))- 0] = a23_1;
	nimln_(688);	S_p0[(((NI)24))- 0] = a24_1;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, absorbFinalBlockWithDomain__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u123)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0, NI o_p2, NI rateBytes_p3, NU8 domain_p4) {
	tyArray__k5CantrhGuvnhsRWsHF5HA blk_1;
	NI take_1;
	NI i_1;
NIM_BOOL* nimErr_;
	nimfr_("absorbFinalBlockWithDomain", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)blk_1, sizeof(tyArray__k5CantrhGuvnhsRWsHF5HA));
	nimln_(354);	take_1 = ((NI)0);
	nimln_(355);	i_1 = ((NI)0);
	nimln_(356);	take_1 = (NI)(A_p1Len_0 - o_p2);
	nimln_(357);	{
		if (!(take_1 < ((NI)0))) goto LA3_;
		nimln_(358);		take_1 = ((NI)0);
	}
LA3_: ;
	nimln_(359);	i_1 = ((NI)0);
	{
		nimln_(360);		while (1) {
			if (!(i_1 < take_1)) goto LA6;
			nimln_(361);			blk_1[(i_1)- 0] = A_p1[(NI)(o_p2 + i_1)];
			nimln_(362);			i_1 = (NI)(i_1 + ((NI)1));
		} LA6: ;
	}
	nimln_(363);	blk_1[(take_1)- 0] = (NU8)(blk_1[(take_1)- 0] ^ domain_p4);
	nimln_(364);	blk_1[((NI)(rateBytes_p3 - ((NI)1)))- 0] = (NU8)(blk_1[((NI)(rateBytes_p3 - ((NI)1)))- 0] ^ ((NU8)128));
	nimln_(365);	absorbBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u116(S_p0, blk_1, 168, ((NI)0), rateBytes_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, absorbFinalBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u322)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0, NI o_p2, NI rateBytes_p3) {
NIM_BOOL* nimErr_;
	nimfr_("absorbFinalBlock", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(439);	absorbFinalBlockWithDomain__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u123(S_p0, A_p1, A_p1Len_0, o_p2, rateBytes_p3, ((NU8)6));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84)(NU8* A_p0, NI A_p0Len_0, NI o_p1, NU64 v_p2) {
	nimfr_("store64Le", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
	nimln_(331);	A_p0[o_p1] = ((NU8) ((NU64)(v_p2 & 255ULL)));
	nimln_(332);	A_p0[(NI)(o_p1 + ((NI)1))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)8))) & 255ULL)));
	nimln_(333);	A_p0[(NI)(o_p1 + ((NI)2))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)16))) & 255ULL)));
	nimln_(334);	A_p0[(NI)(o_p1 + ((NI)3))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)24))) & 255ULL)));
	nimln_(335);	A_p0[(NI)(o_p1 + ((NI)4))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)32))) & 255ULL)));
	nimln_(336);	A_p0[(NI)(o_p1 + ((NI)5))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)40))) & 255ULL)));
	nimln_(337);	A_p0[(NI)(o_p1 + ((NI)6))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)48))) & 255ULL)));
	nimln_(338);	A_p0[(NI)(o_p1 + ((NI)7))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)56))) & 255ULL)));
	popFrame();
}
static N_INLINE(void, squeezeBytesState__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u193)(NU64* S_p0, NU8* dst_p1, NI dst_p1Len_0, NI rateBytes_p2) {
	NI i_1;
	tyArray__cdsir9aPB24hAk6k77P9b9bCA laneBytes_1;
	NI produced_1;
	NI take_1;
	NI blockBytes_1;
NIM_BOOL* nimErr_;
	nimfr_("squeezeBytesState", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(376);	i_1 = ((NI)0);
	nimln_(378);	produced_1 = ((NI)0);
	nimln_(379);	take_1 = ((NI)0);
	nimln_(380);	blockBytes_1 = ((NI)0);
	{
		nimln_(381);		while (1) {
			if (!(produced_1 < dst_p1Len_0)) goto LA2;
			nimln_(382);			blockBytes_1 = rateBytes_p2;
			nimln_(383);			{
				if (!((NI)(dst_p1Len_0 - produced_1) < blockBytes_1)) goto LA5_;
				nimln_(384);				blockBytes_1 = (NI)(dst_p1Len_0 - produced_1);
			}
LA5_: ;
			nimln_(385);			i_1 = ((NI)0);
			{
				nimln_(386);				while (1) {
					if (!((NI)(i_1 * ((NI)8)) < blockBytes_1)) goto LA8;
					nimln_(387);					store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(laneBytes_1, 8, ((NI)0), S_p0[(i_1)- 0]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(388);					take_1 = (NI)(blockBytes_1 - (NI)(i_1 * ((NI)8)));
					nimln_(389);					{
						if (!(((NI)8) < take_1)) goto LA11_;
						nimln_(390);						take_1 = ((NI)8);
					}
LA11_: ;
					{
						NI j_1;
						NI i_2;
						j_1 = (NI)0;
						nimlf_(128, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");						i_2 = ((NI)0);
						{
							nimln_(129);							while (1) {
								if (!(i_2 < take_1)) goto LA15;
								nimlf_(391, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");								j_1 = i_2;
								nimln_(392);								dst_p1[(NI)((NI)(produced_1 + (NI)(i_1 * ((NI)8))) + j_1)] = laneBytes_1[(j_1)- 0];
								nimlf_(131, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");								i_2 += ((NI)1);
							} LA15: ;
						}
					}
					nimlf_(393, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");					i_1 = (NI)(i_1 + ((NI)1));
				} LA8: ;
			}
			nimln_(394);			produced_1 = (NI)(produced_1 + blockBytes_1);
			nimln_(395);			{
				if (!(produced_1 < dst_p1Len_0)) goto LA18_;
				nimln_(396);				keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173(S_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA18_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, squeezeBytesInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u238)(tyArray__ti0bWuszecJ2jGEjnJGmWg S0_p0, NU8* dst_p1, NI dst_p1Len_0, NI rateBytes_p2) {
	tyArray__ti0bWuszecJ2jGEjnJGmWg S_1;
NIM_BOOL* nimErr_;
	nimfr_("squeezeBytesInto", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(400);	nimCopyMem((void*)S_1, (NIM_CONST void*)S0_p0, sizeof(tyArray__ti0bWuszecJ2jGEjnJGmWg));
	nimln_(401);	squeezeBytesState__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u193(S_1, dst_p1, dst_p1Len_0, rateBytes_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, sha3DigestInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u665)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0, tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg v_p2) {
	tyArray__ti0bWuszecJ2jGEjnJGmWg S_1;
	NI rateBytes_1;
	NI offset_1;
NIM_BOOL* nimErr_;
	nimfr_("sha3DigestInto", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)S_1, sizeof(tyArray__ti0bWuszecJ2jGEjnJGmWg));
	nimln_(694);	rateBytes_1 = ((NI)0);
	nimln_(695);	offset_1 = ((NI)0);
	nimln_(696);	{
		NI T3_;
		tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* T6_;
		T3_ = (NI)0;
		T3_ = sha3DigestBytes__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u19(v_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!((dst_p0Len_0 == T3_))) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ*) nimNewObj(sizeof(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), NIM_ALIGNOF(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__knMwTE9cBPqCO0qkZrysJgQ_);
		(*T6_).Sup.Sup.name = "ValueError";
		(*T6_).Sup.Sup.message = TM__n2hmFo6ThUGbJBhyfD9ajFg_3;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(697);		raiseExceptionEx((Exception*)T6_, "ValueError", "sha3DigestInto", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim", 697);
goto BeforeRet_;
	}
LA4_: ;
	nimln_(698);	rateBytes_1 = sha3RateBytes__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u22(v_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(699);	offset_1 = ((NI)0);
	{
		nimln_(700);		while (1) {
			if (!((NI)(offset_1 + rateBytes_1) <= A_p1Len_0)) goto LA8;
			nimln_(701);			absorbBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u116(S_1, A_p1, A_p1Len_0, offset_1, rateBytes_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(702);			keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173(S_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(703);			offset_1 = (NI)(offset_1 + rateBytes_1);
		} LA8: ;
	}
	nimln_(704);	absorbFinalBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u322(S_1, A_p1, A_p1Len_0, offset_1, rateBytes_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(705);	keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173(S_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(706);	squeezeBytesInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u238(S_1, dst_p0, dst_p0Len_0, rateBytes_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, sha3Digest__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u679)(NU8* A_p0, NI A_p0Len_0, tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg v_p1) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("sha3Digest", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(710);	T1_ = (NI)0;
	T1_ = sha3DigestBytes__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u19(v_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if ((T1_) < ((NI)0) || (T1_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(T1_, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = newSeq__fgqZflfenaq_u144((T1_));
	nimln_(711);	sha3DigestInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u665(((result).p) ? (result.p->data) : NIM_NIL, result.len, A_p0, A_p0Len_0, v_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg, sha3VariantFromOutLen__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u25)(NI outLen_p0) {
	tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg result;
	nimfr_("sha3VariantFromOutLen", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{	result = (tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)0;
	nimln_(298);	switch (outLen_p0) {
	case ((NI)28):
	{
		nimln_(300);		result = ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)0);
	}
	break;
	case ((NI)32):
	{
		nimln_(302);		result = ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)1);
	}
	break;
	case ((NI)48):
	{
		nimln_(304);		result = ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)2);
	}
	break;
	case ((NI)64):
	{
		nimln_(306);		result = ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)3);
	}
	break;
	default:
	{
		tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* T6_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ*) nimNewObj(sizeof(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), NIM_ALIGNOF(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__knMwTE9cBPqCO0qkZrysJgQ_);
		(*T6_).Sup.Sup.name = "ValueError";
		(*T6_).Sup.Sup.message = TM__n2hmFo6ThUGbJBhyfD9ajFg_5;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(308);		raiseExceptionEx((Exception*)T6_, "ValueError", "sha3VariantFromOutLen", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim", 308);
goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, sha3Hash__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u907)(NU8* A_p0, NI A_p0Len_0, NI outLen_p1) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg T1_;
NIM_BOOL* nimErr_;
	nimfr_("sha3Hash", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(976);	T1_ = (tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)0;
	T1_ = sha3VariantFromOutLen__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u25(outLen_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = sha3Digest__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u679(A_p0, A_p0Len_0, T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, absorbPartState__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u327)(NU64* S_p0, NU8* tail_p1, NI* tailLen_p2, NU8* A_p3, NI A_p3Len_0, NI rateBytes_p4) {
	NI offset_1;
	NI take_1;
	NI i_1;
NIM_BOOL* nimErr_;
	nimfr_("absorbPartState", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(444);	offset_1 = ((NI)0);
	nimln_(445);	take_1 = ((NI)0);
	nimln_(446);	i_1 = ((NI)0);
	nimln_(447);	{
		if (!(((NI)0) < (*tailLen_p2))) goto LA3_;
		nimln_(448);		take_1 = (NI)(rateBytes_p4 - (*tailLen_p2));
		nimln_(449);		{
			if (!(A_p3Len_0 < take_1)) goto LA7_;
			nimln_(450);			take_1 = A_p3Len_0;
		}
LA7_: ;
		nimln_(451);		i_1 = ((NI)0);
		{
			nimln_(452);			while (1) {
				if (!(i_1 < take_1)) goto LA10;
				nimln_(453);				tail_p1[((NI)((*tailLen_p2) + i_1))- 0] = A_p3[i_1];
				nimln_(454);				i_1 = (NI)(i_1 + ((NI)1));
			} LA10: ;
		}
		nimln_(455);		(*tailLen_p2) = (NI)((*tailLen_p2) + take_1);
		nimln_(456);		offset_1 = take_1;
		nimln_(457);		{
			if (!((*tailLen_p2) == rateBytes_p4)) goto LA13_;
			nimln_(458);			absorbBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u116(S_p0, tail_p1, 168, ((NI)0), rateBytes_p4);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(459);			keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173(S_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(460);			(*tailLen_p2) = ((NI)0);
		}
LA13_: ;
	}
LA3_: ;
	{
		nimln_(461);		while (1) {
			if (!((NI)(offset_1 + rateBytes_p4) <= A_p3Len_0)) goto LA16;
			nimln_(462);			absorbBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u116(S_p0, A_p3, A_p3Len_0, offset_1, rateBytes_p4);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(463);			keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173(S_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(464);			offset_1 = (NI)(offset_1 + rateBytes_p4);
		} LA16: ;
	}
	{
		nimln_(465);		while (1) {
			if (!(offset_1 < A_p3Len_0)) goto LA18;
			nimln_(466);			tail_p1[((*tailLen_p2))- 0] = A_p3[offset_1];
			nimln_(467);			(*tailLen_p2) = (NI)((*tailLen_p2) + ((NI)1));
			nimln_(468);			offset_1 = (NI)(offset_1 + ((NI)1));
		} LA18: ;
	}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, absorbFinalPartsWithDomain__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u348)(NU64* S_p0, NI rateBytes_p1, NU8 domain_p2, NU8* A_p3, NI A_p3Len_0) {
	tyArray__k5CantrhGuvnhsRWsHF5HA tail_1;
	NI tailLen_1;
	NI i_1;
NIM_BOOL* nimErr_;
	nimfr_("absorbFinalPartsWithDomain", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)tail_1, sizeof(tyArray__k5CantrhGuvnhsRWsHF5HA));
	nimln_(474);	tailLen_1 = ((NI)0);
	nimln_(475);	i_1 = ((NI)0);
	nimln_(476);	absorbPartState__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u327(S_p0, tail_1, (&tailLen_1), A_p3, A_p3Len_0, rateBytes_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(477);	i_1 = tailLen_1;
	{
		nimln_(478);		while (1) {
			if (!(i_1 < rateBytes_p1)) goto LA2;
			nimln_(479);			tail_1[(i_1)- 0] = ((NU8)0);
			nimln_(480);			i_1 = (NI)(i_1 + ((NI)1));
		} LA2: ;
	}
	nimln_(481);	tail_1[(tailLen_1)- 0] = (NU8)(tail_1[(tailLen_1)- 0] ^ domain_p2);
	nimln_(482);	tail_1[((NI)(rateBytes_p1 - ((NI)1)))- 0] = (NU8)(tail_1[((NI)(rateBytes_p1 - ((NI)1)))- 0] ^ ((NU8)128));
	nimln_(483);	absorbBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u116(S_p0, tail_1, 168, ((NI)0), rateBytes_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, shake128AbsorbOnce__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u703)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("shake128AbsorbOnce", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(715);	absorbFinalPartsWithDomain__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u348(S_p0, ((NI)168), ((NU8)31), A_p1, A_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(716);	keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173(S_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, shake128Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u190)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
	tyArray__ti0bWuszecJ2jGEjnJGmWg S_1;
NIM_BOOL* nimErr_;
	nimfr_("shake128Into", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)S_1, sizeof(tyArray__ti0bWuszecJ2jGEjnJGmWg));
	nimln_(932);	shake128AbsorbOnce__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u703(S_1, A_p1, A_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(933);	squeezeBytesState__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u193(S_1, dst_p0, dst_p0Len_0, ((NI)168));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, shake128__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u858)(NU8* A_p0, NI A_p0Len_0, NI outLen_p1) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
NIM_BOOL* nimErr_;
	nimfr_("shake128", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(937);	{
		tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* T5_;
		if (!(outLen_p1 < ((NI)0))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ*) nimNewObj(sizeof(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), NIM_ALIGNOF(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__knMwTE9cBPqCO0qkZrysJgQ_);
		(*T5_).Sup.Sup.name = "ValueError";
		(*T5_).Sup.Sup.message = TM__n2hmFo6ThUGbJBhyfD9ajFg_7;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(938);		raiseExceptionEx((Exception*)T5_, "ValueError", "shake128", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim", 938);
goto BeforeRet_;
	}
LA3_: ;
	nimln_(939);	if ((outLen_p1) < ((NI)0) || (outLen_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(outLen_p1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = newSeq__fgqZflfenaq_u144((outLen_p1));
	nimln_(940);	shake128Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u190(((result).p) ? (result.p->data) : NIM_NIL, result.len, A_p0, A_p0Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, shake256AbsorbOnce__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u706)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("shake256AbsorbOnce", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(720);	absorbFinalPartsWithDomain__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u348(S_p0, ((NI)136), ((NU8)31), A_p1, A_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(721);	keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173(S_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, shake256Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u175)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("shake256Into", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	{
		tyArray__ti0bWuszecJ2jGEjnJGmWg S_1;
		nimZeroMem((void*)S_1, sizeof(tyArray__ti0bWuszecJ2jGEjnJGmWg));
		nimln_(897);		shake256AbsorbOnce__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u706(S_1, A_p1, A_p1Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(898);		squeezeBytesInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u238(S_1, dst_p0, dst_p0Len_0, ((NI)136));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, shake256__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u742)(NU8* A_p0, NI A_p0Len_0, NI outLen_p1) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
NIM_BOOL* nimErr_;
	nimfr_("shake256", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(837);	{
		tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* T5_;
		if (!(outLen_p1 < ((NI)0))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ*) nimNewObj(sizeof(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), NIM_ALIGNOF(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__knMwTE9cBPqCO0qkZrysJgQ_);
		(*T5_).Sup.Sup.name = "ValueError";
		(*T5_).Sup.Sup.message = TM__n2hmFo6ThUGbJBhyfD9ajFg_9;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(838);		raiseExceptionEx((Exception*)T5_, "ValueError", "shake256", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim", 838);
goto BeforeRet_;
	}
LA3_: ;
	nimln_(839);	if ((outLen_p1) < ((NI)0) || (outLen_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(outLen_p1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = newSeq__fgqZflfenaq_u144((outLen_p1));
	nimln_(840);	shake256Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u175(((result).p) ? (result.p->data) : NIM_NIL, result.len, A_p0, A_p0Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, sha3512Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u892)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("sha3_512Into", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(956);	sha3DigestInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u665(dst_p0, dst_p0Len_0, A_p1, A_p1Len_0, ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)3));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, shake128SqueezeBlocksIntoUnchecked__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u714)(NU64* S_p0, NU8* dst_p1, NI dst_p1Len_0) {
	NI produced_1;
NIM_BOOL* nimErr_;
	nimfr_("shake128SqueezeBlocksIntoUnchecked", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(773);	produced_1 = ((NI)0);
	{
		nimln_(774);		while (1) {
			if (!(produced_1 < dst_p1Len_0)) goto LA2;
			nimln_(775);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)0)), S_p0[(((NI)0))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(776);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)8)), S_p0[(((NI)1))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(777);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)16)), S_p0[(((NI)2))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(778);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)24)), S_p0[(((NI)3))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(779);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)32)), S_p0[(((NI)4))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(780);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)40)), S_p0[(((NI)5))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(781);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)48)), S_p0[(((NI)6))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(782);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)56)), S_p0[(((NI)7))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(783);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)64)), S_p0[(((NI)8))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(784);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)72)), S_p0[(((NI)9))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(785);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)80)), S_p0[(((NI)10))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(786);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)88)), S_p0[(((NI)11))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(787);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)96)), S_p0[(((NI)12))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(788);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)104)), S_p0[(((NI)13))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(789);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)112)), S_p0[(((NI)14))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(790);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)120)), S_p0[(((NI)15))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(791);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)128)), S_p0[(((NI)16))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(792);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)136)), S_p0[(((NI)17))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(793);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)144)), S_p0[(((NI)18))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(794);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)152)), S_p0[(((NI)19))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(795);			store64Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u84(dst_p1, dst_p1Len_0, (NI)(produced_1 + ((NI)160)), S_p0[(((NI)20))- 0]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(796);			produced_1 = (NI)(produced_1 + ((NI)168));
			nimln_(797);			keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173(S_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, shake128SqueezeBlocksInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u721)(NU64* S_p0, NU8* dst_p1, NI dst_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("shake128SqueezeBlocksInto", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(801);	{
		tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* T5_;
		if (!!(((NI)(dst_p1Len_0 % ((NI)168)) == ((NI)0)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ*) nimNewObj(sizeof(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), NIM_ALIGNOF(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__knMwTE9cBPqCO0qkZrysJgQ_);
		(*T5_).Sup.Sup.name = "ValueError";
		(*T5_).Sup.Sup.message = TM__n2hmFo6ThUGbJBhyfD9ajFg_11;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(802);		raiseExceptionEx((Exception*)T5_, "ValueError", "shake128SqueezeBlocksInto", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim", 802);
goto BeforeRet_;
	}
LA3_: ;
	nimln_(803);	shake128SqueezeBlocksIntoUnchecked__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u714(S_p0, dst_p1, dst_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, sha3256Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u886)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("sha3_256Into", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(948);	sha3DigestInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u665(dst_p0, dst_p0Len_0, A_p1, A_p1Len_0, ((tyEnum_Sha3Variant__2qMq9c9cogkpAOi1EUJNNVTg)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, copyMem__flfgrz_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_CLOSURE(void, absorbPartialChunk__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u775)(NU8* A_p0, NI A_p0Len_0, void* ClE_0) {
	tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg* colonenvP__1;
	NI offset_1;
	NI take_1;
NIM_BOOL* nimErr_;
	nimfr_("absorbPartialChunk", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	colonenvP__1 = (tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg*) ClE_0;
	nimln_(853);	offset_1 = ((NI)0);
	nimln_(854);	take_1 = ((NI)0);
	nimln_(855);	{
		if (!((*colonenvP__1).used0 == ((NI)0))) goto LA3_;
		{
			nimln_(856);			while (1) {
				if (!((NI)(offset_1 + ((NI)136)) <= A_p0Len_0)) goto LA6;
				nimln_(857);				absorbBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u116((*colonenvP__1).S1, A_p0, A_p0Len_0, offset_1, ((NI)136));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(858);				keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173((*colonenvP__1).S1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(859);				offset_1 = (NI)(offset_1 + ((NI)136));
			} LA6: ;
		}
	}
LA3_: ;
	{
		nimln_(860);		while (1) {
			if (!(offset_1 < A_p0Len_0)) goto LA8;
			nimln_(861);			take_1 = (((NI)(((NI)136) - (*colonenvP__1).used0) <= (NI)(A_p0Len_0 - offset_1)) ? (NI)(((NI)136) - (*colonenvP__1).used0) : (NI)(A_p0Len_0 - offset_1));
			nimln_(862);			if ((take_1) < ((NI)0) || (take_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(take_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			copyMem__flfgrz_u1731(((void*) ((&(*colonenvP__1).blk2[((*colonenvP__1).used0)- 0]))), ((void*) ((&A_p0[offset_1]))), (take_1));
			nimln_(863);			(*colonenvP__1).used0 = (NI)((*colonenvP__1).used0 + take_1);
			nimln_(864);			offset_1 = (NI)(offset_1 + take_1);
			nimln_(865);			{
				if (!((*colonenvP__1).used0 == ((NI)136))) goto LA11_;
				nimln_(866);				absorbBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u116((*colonenvP__1).S1, (*colonenvP__1).blk2, 136, ((NI)0), ((NI)136));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(867);				keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173((*colonenvP__1).S1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(868);				(*colonenvP__1).used0 = ((NI)0);
			}
LA11_: ;
		} LA8: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_CLOSURE(void, finalizePartial__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u826)(void* ClE_0) {
	tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg* colonenvP__1;
	tyArray__6qSULJVkHXjL25e22OI5AQ finalBlock_1;
NIM_BOOL* nimErr_;
	nimfr_("finalizePartial", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	colonenvP__1 = (tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg*) ClE_0;
	nimZeroMem((void*)finalBlock_1, sizeof(tyArray__6qSULJVkHXjL25e22OI5AQ));
	nimln_(873);	{
		if (!(((NI)0) < (*colonenvP__1).used0)) goto LA3_;
		nimln_(874);		if (((*colonenvP__1).used0) < ((NI)0) || ((*colonenvP__1).used0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((*colonenvP__1).used0, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__flfgrz_u1731(((void*) ((&finalBlock_1[(((NI)0))- 0]))), ((void*) ((&(*colonenvP__1).blk2[(((NI)0))- 0]))), ((*colonenvP__1).used0));
	}
LA3_: ;
	nimln_(875);	finalBlock_1[((*colonenvP__1).used0)- 0] = (NU8)(finalBlock_1[((*colonenvP__1).used0)- 0] ^ ((NU8)31));
	nimln_(876);	finalBlock_1[(((NI)135))- 0] = (NU8)(finalBlock_1[(((NI)135))- 0] ^ ((NU8)128));
	nimln_(877);	absorbBlock__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u116((*colonenvP__1).S1, finalBlock_1, 136, ((NI)0), ((NI)136));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(878);	keccakF1600Ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u173((*colonenvP__1).S1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI, minuspercent___flfgrz_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/arithmetics.nim");
	nimlf_(364, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicDyn", "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(512, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(513);	{
		tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(514);		nimlf_(58, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___flfgrz_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__yFa2nHcbe5eF4ueVmcr3RA*) (T5_));
		nimlf_(515, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(516);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__n2hmFo6ThUGbJBhyfD9ajFg_17;
			nimln_(519);			if (nimSubInt((*cell_1).rc, ((NI)16), &TM__n2hmFo6ThUGbJBhyfD9ajFg_17)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell_1).rc = (NI)(TM__n2hmFo6ThUGbJBhyfD9ajFg_17);
		}
LA6_: ;
		nimln_(521);		rememberCycle__flfgrz_u3546(result, cell_1, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u998)(tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, shake256ChunksInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u767)(NU8* dst_p0, NI dst_p0Len_0, NU8* A0_p1, NI A0_p1Len_0, NU8* A1_p2, NI A1_p2Len_0, NU8* A2_p3, NI A2_p3Len_0) {
	tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg* colonenv__1;
	tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg* T1_;
NIM_BOOL* nimErr_;
	nimfr_("shake256ChunksInto", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	colonenv__1 = NIM_NIL;
	nimlf_(847, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");	T1_ = NIM_NIL;
	T1_ = (tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg*) nimNewObj(sizeof(tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg), NIM_ALIGNOF(tyObject_Env_sha3dotnim_shake256ChunksInto___VBn7z1gkJnsFECAXuYH8Kg));
	(*T1_).Sup.m_type = (&NTIv2__VBn7z1gkJnsFECAXuYH8Kg_);
	colonenv__1 = T1_;
	{
		tyProc__AmYyP09cVAnPVL9bYlOQH9chg T3_;
		tyProc__AmYyP09cVAnPVL9bYlOQH9chg T4_;
		tyProc__AmYyP09cVAnPVL9bYlOQH9chg T5_;
		tyProc__HzVCwACFYM9cx9aV62PdjtuA T6_;
		nimZeroMem((void*)(*colonenv__1).S1, sizeof(tyArray__ti0bWuszecJ2jGEjnJGmWg));
		nimln_(848);		nimZeroMem((void*)(*colonenv__1).blk2, sizeof(tyArray__6qSULJVkHXjL25e22OI5AQ));
		nimln_(849);		(*colonenv__1).used0 = ((NI)0);
		nimln_(883);		nimZeroMem((void*)(&T3_), sizeof(tyProc__AmYyP09cVAnPVL9bYlOQH9chg));
		T3_.ClP_0 = absorbPartialChunk__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u775; T3_.ClE_0 = colonenv__1;
		T3_.ClE_0? T3_.ClP_0(A0_p1, A0_p1Len_0, T3_.ClE_0):((TM__n2hmFo6ThUGbJBhyfD9ajFg_13)(T3_.ClP_0))(A0_p1, A0_p1Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(884);		nimZeroMem((void*)(&T4_), sizeof(tyProc__AmYyP09cVAnPVL9bYlOQH9chg));
		T4_.ClP_0 = absorbPartialChunk__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u775; T4_.ClE_0 = colonenv__1;
		T4_.ClE_0? T4_.ClP_0(A1_p2, A1_p2Len_0, T4_.ClE_0):((TM__n2hmFo6ThUGbJBhyfD9ajFg_14)(T4_.ClP_0))(A1_p2, A1_p2Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(885);		nimZeroMem((void*)(&T5_), sizeof(tyProc__AmYyP09cVAnPVL9bYlOQH9chg));
		T5_.ClP_0 = absorbPartialChunk__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u775; T5_.ClE_0 = colonenv__1;
		T5_.ClE_0? T5_.ClP_0(A2_p3, A2_p3Len_0, T5_.ClE_0):((TM__n2hmFo6ThUGbJBhyfD9ajFg_15)(T5_.ClP_0))(A2_p3, A2_p3Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(886);		nimZeroMem((void*)(&T6_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
		T6_.ClP_0 = finalizePartial__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u826; T6_.ClE_0 = colonenv__1;
		T6_.ClE_0? T6_.ClP_0(T6_.ClE_0):((TM__n2hmFo6ThUGbJBhyfD9ajFg_16)(T6_.ClP_0))();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(887);		squeezeBytesInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u238((*colonenv__1).S1, dst_p0, dst_p0Len_0, ((NI)136));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	nimln_(842);	eqdestroy___OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u998(colonenv__1);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, shake256Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u182)(NU8* dst_p0, NI dst_p0Len_0, NU8* A0_p1, NI A0_p1Len_0, NU8* A1_p2, NI A1_p2Len_0, NU8* A2_p3, NI A2_p3Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("shake256Into", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimln_(908);	shake256ChunksInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u767(dst_p0, dst_p0Len_0, A0_p1, A0_p1Len_0, A1_p2, A1_p2Len_0, A2_p3, A2_p3Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, shake256Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u178)(NU8* dst_p0, NI dst_p0Len_0, NU8* A0_p1, NI A0_p1Len_0, NU8* A1_p2, NI A1_p2Len_0) {
	tyArray__ekVvh9bp9cVe7STNUL8R406w empty_1;
NIM_BOOL* nimErr_;
	nimfr_("shake256Into", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/sha3/sha3.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)empty_1, sizeof(tyArray__ekVvh9bp9cVe7STNUL8R406w));
	nimln_(904);	shake256ChunksInto__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZfun3Zfun3_u767(dst_p0, dst_p0Len_0, A0_p1, A0_p1Len_0, A1_p2, A1_p2Len_0, empty_1, 0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
