/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   /nix/store/788mx070y81zjlg5ipcl0cra3afviw9k-gcc-wrapper-15.2.0/bin/gcc -c -w -fmax-errors=3 -pthread   -I/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib -I/mnt/temp/CodingMain/Tyr-Crypto/tests -o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fphfgbz_pelcgb@fnflzzrgevp@fcd@fxlore@fpoq.nim.c.o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fphfgbz_pelcgb@fnflzzrgevp@fcd@fxlore@fpoq.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_KyberParams__KlUGF0jYQ5WfQZY9cBkZZOQ tyObject_KyberParams__KlUGF0jYQ5WfQZY9cBkZZOQ;
typedef struct tyObject_Poly__OOcH647wDNJ3G2MVGodZ9cA tyObject_Poly__OOcH647wDNJ3G2MVGodZ9cA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ;
typedef struct tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__lQYMoIzOpEqh2HdAFaxIkA tySequence__lQYMoIzOpEqh2HdAFaxIkA;
typedef struct tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content;
typedef struct tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_KyberParams__KlUGF0jYQ5WfQZY9cBkZZOQ {
	NimStringV2 name;
	NimStringV2 pqcleanName;
	NI k;
	NI eta1;
	NI eta2;
	NI polyCompressedBytes;
	NI polyVecCompressedBytes;
	NI indcpaMsgBytes;
	NI indcpaPublicKeyBytes;
	NI indcpaSecretKeyBytes;
	NI indcpaBytes;
	NI publicKeyBytes;
	NI secretKeyBytes;
	NI ciphertextBytes;
	NI sharedSecretBytes;
	NI xofBlockBytes;
};
typedef NI16 tyArray__Q5VMONt75D2EmGD49aOcb4A[256];
struct tyObject_Poly__OOcH647wDNJ3G2MVGodZ9cA {
	tyArray__Q5VMONt75D2EmGD49aOcb4A coeffs;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__lQYMoIzOpEqh2HdAFaxIkA {
  NI len; tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQYMoIzOpEqh2HdAFaxIkA trace;
	Exception* up;
};
struct tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A {
	Exception Sup;
};
struct tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ {
	tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A Sup;
};
struct tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content { NI cap; tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, cbd2__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZpoq_u4)(tyObject_Poly__OOcH647wDNJ3G2MVGodZ9cA* R_p0, NU8* buf_p1, NI buf_p1Len_0);
static N_INLINE(NU32, load32Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZhgvy_u15)(NU8* A_p0, NI A_p0Len_0, NI o_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, cbd3__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZpoq_u25)(tyObject_Poly__OOcH647wDNJ3G2MVGodZ9cA* R_p0, NU8* buf_p1, NI buf_p1Len_0);
static N_INLINE(NU32, load24Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZhgvy_u3)(NU8* A_p0, NI A_p0Len_0, NI o_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
extern TNimTypeV2 NTIv2__knMwTE9cBPqCO0qkZrysJgQ_;
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_25 = { 22 | NIM_STRLIT_FLAG, "unsupported Kyber eta1" };
static const NimStringV2 TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_26 = {22, (NimStrPayload*)&TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_25};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_27 = { 22 | NIM_STRLIT_FLAG, "unsupported Kyber eta2" };
static const NimStringV2 TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_28 = {22, (NimStrPayload*)&TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_27};
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4509;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2741;
	framePtr__flfgrz_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2741 = (*framePtr__flfgrz_u2741).prev;
}
static N_INLINE(NU32, load32Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZhgvy_u15)(NU8* A_p0, NI A_p0Len_0, NI o_p1) {
	NU32 result;
	NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_2;
	NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_3;
	NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_4;
	nimfr_("load32Le", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/util.nim");
{	nimlf_(18, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/util.nim");	nimln_(21);	nimln_(20);	nimln_(19);	nimln_(20);	if (nimAddInt(o_p1, ((NI)1), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_2)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(21);	if (nimAddInt(o_p1, ((NI)2), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_3)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(22);	if (nimAddInt(o_p1, ((NI)3), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_4)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NU32)((NU32)((NU32)(((NU32) (A_p0[o_p1])) | (NU32)((NU64)(((NU32) (A_p0[(NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_2)]))) << (NU64)(((NI)8)))) | (NU32)((NU64)(((NU32) (A_p0[(NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_3)]))) << (NU64)(((NI)16)))) | (NU32)((NU64)(((NU32) (A_p0[(NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_4)]))) << (NU64)(((NI)24))));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4509);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, cbd2__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZpoq_u4)(tyObject_Poly__OOcH647wDNJ3G2MVGodZ9cA* R_p0, NU8* buf_p1, NI buf_p1Len_0) {
	NI i_1;
	NI j_1;
	NU32 t_1;
	NU32 d_1;
	NI16 a_1;
	NI16 b_1;
NIM_BOOL* nimErr_;
	nimfr_("cbd2", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/cbd.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(13, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/cbd.nim");	i_1 = ((NI)0);
	nimln_(14);	j_1 = ((NI)0);
	nimln_(15);	t_1 = ((NU32)0);
	nimln_(16);	d_1 = ((NU32)0);
	nimln_(17);	a_1 = ((NI16)0);
	nimln_(18);	b_1 = ((NI16)0);
	nimln_(19);	i_1 = ((NI)0);
	{
		nimln_(20);		while (1) {
			NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_5;
			NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_13;
			if (!(i_1 < ((NI)32))) goto LA2;
			nimln_(21);			if (nimMulInt(((NI)4), i_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_5)) { raiseOverflow(); goto BeforeRet_;
			};
			t_1 = load32Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZhgvy_u15(buf_p1, buf_p1Len_0, (NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_5));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(22);			d_1 = (NU32)(t_1 & ((NU32)1431655765));
			nimln_(23);			d_1 = (NU32)((NU32)(d_1) + (NU32)((NU32)((NU32)((NU32)(t_1) >> (NU64)(((NI)1))) & ((NU32)1431655765))));
			nimln_(24);			j_1 = ((NI)0);
			{
				nimln_(25);				while (1) {
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_6;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_7;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_8;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_9;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_10;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_11;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_12;
					if (!(j_1 < ((NI)8))) goto LA4;
					nimln_(26);					if (nimMulInt(((NI)4), j_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_6)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI64)((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_6))) & ((NU32)3))) < ((NI16)-32768) || (NI64)((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_6))) & ((NU32)3))) > ((NI16)32767)){ raiseRangeErrorI((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_6))) & ((NU32)3)), ((NI16)-32768), ((NI16)32767)); goto BeforeRet_;
					}
					a_1 = ((NI16) ((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_6))) & ((NU32)3))));
					nimln_(27);					if (nimMulInt(((NI)4), j_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_7)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_7), ((NI)2), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_8)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI64)((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_8))) & ((NU32)3))) < ((NI16)-32768) || (NI64)((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_8))) & ((NU32)3))) > ((NI16)32767)){ raiseRangeErrorI((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_8))) & ((NU32)3)), ((NI16)-32768), ((NI16)32767)); goto BeforeRet_;
					}
					b_1 = ((NI16) ((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_8))) & ((NU32)3))));
					nimln_(28);					if (nimMulInt(((NI)8), i_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_9)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_9), j_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_10)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt(a_1, b_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_11)) { raiseOverflow(); goto BeforeRet_;
					};
					if (TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_11 < -32768 || TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_11 > 32767){ raiseOverflow(); goto BeforeRet_;
					}
					(*R_p0).coeffs[((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_10))- 0] = (NI16)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_11);
					nimln_(29);					if (nimAddInt(j_1, ((NI)1), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_12)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_12);
				} LA4: ;
			}
			nimln_(30);			if (nimAddInt(i_1, ((NI)1), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_13)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_13);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NU32, load24Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZhgvy_u3)(NU8* A_p0, NI A_p0Len_0, NI o_p1) {
	NU32 result;
	NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_14;
	NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_15;
	nimfr_("load24Le", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/util.nim");
{	nimlf_(11, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/util.nim");	nimln_(13);	nimln_(12);	nimln_(13);	if (nimAddInt(o_p1, ((NI)1), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_14)) { raiseOverflow(); goto BeforeRet_;
	};
	nimln_(14);	if (nimAddInt(o_p1, ((NI)2), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_15)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NU32)((NU32)(((NU32) (A_p0[o_p1])) | (NU32)((NU64)(((NU32) (A_p0[(NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_14)]))) << (NU64)(((NI)8)))) | (NU32)((NU64)(((NU32) (A_p0[(NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_15)]))) << (NU64)(((NI)16))));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, cbd3__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZpoq_u25)(tyObject_Poly__OOcH647wDNJ3G2MVGodZ9cA* R_p0, NU8* buf_p1, NI buf_p1Len_0) {
	NI i_1;
	NI j_1;
	NU32 t_1;
	NU32 d_1;
	NI16 a_1;
	NI16 b_1;
NIM_BOOL* nimErr_;
	nimfr_("cbd3", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/cbd.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(34, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/cbd.nim");	i_1 = ((NI)0);
	nimln_(35);	j_1 = ((NI)0);
	nimln_(36);	t_1 = ((NU32)0);
	nimln_(37);	d_1 = ((NU32)0);
	nimln_(38);	a_1 = ((NI16)0);
	nimln_(39);	b_1 = ((NI16)0);
	nimln_(40);	i_1 = ((NI)0);
	{
		nimln_(41);		while (1) {
			NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_16;
			NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_24;
			if (!(i_1 < ((NI)64))) goto LA2;
			nimln_(42);			if (nimMulInt(((NI)3), i_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_16)) { raiseOverflow(); goto BeforeRet_;
			};
			t_1 = load24Le__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZhgvy_u3(buf_p1, buf_p1Len_0, (NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_16));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(43);			d_1 = (NU32)(t_1 & ((NU32)2396745));
			nimln_(44);			d_1 = (NU32)((NU32)(d_1) + (NU32)((NU32)((NU32)((NU32)(t_1) >> (NU64)(((NI)1))) & ((NU32)2396745))));
			nimln_(45);			d_1 = (NU32)((NU32)(d_1) + (NU32)((NU32)((NU32)((NU32)(t_1) >> (NU64)(((NI)2))) & ((NU32)2396745))));
			nimln_(46);			j_1 = ((NI)0);
			{
				nimln_(47);				while (1) {
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_17;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_18;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_19;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_20;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_21;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_22;
					NI TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_23;
					if (!(j_1 < ((NI)4))) goto LA4;
					nimln_(48);					if (nimMulInt(((NI)6), j_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_17)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI64)((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_17))) & ((NU32)7))) < ((NI16)-32768) || (NI64)((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_17))) & ((NU32)7))) > ((NI16)32767)){ raiseRangeErrorI((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_17))) & ((NU32)7)), ((NI16)-32768), ((NI16)32767)); goto BeforeRet_;
					}
					a_1 = ((NI16) ((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_17))) & ((NU32)7))));
					nimln_(49);					if (nimMulInt(((NI)6), j_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_18)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_18), ((NI)3), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_19)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI64)((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_19))) & ((NU32)7))) < ((NI16)-32768) || (NI64)((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_19))) & ((NU32)7))) > ((NI16)32767)){ raiseRangeErrorI((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_19))) & ((NU32)7)), ((NI16)-32768), ((NI16)32767)); goto BeforeRet_;
					}
					b_1 = ((NI16) ((NU32)((NU32)((NU32)(d_1) >> (NU64)((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_19))) & ((NU32)7))));
					nimln_(50);					if (nimMulInt(((NI)4), i_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_20)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_20), j_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_21)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt(a_1, b_1, &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_22)) { raiseOverflow(); goto BeforeRet_;
					};
					if (TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_22 < -32768 || TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_22 > 32767){ raiseOverflow(); goto BeforeRet_;
					}
					(*R_p0).coeffs[((NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_21))- 0] = (NI16)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_22);
					nimln_(51);					if (nimAddInt(j_1, ((NI)1), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_23)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_23);
				} LA4: ;
			}
			nimln_(52);			if (nimAddInt(i_1, ((NI)1), &TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_24)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_24);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, polyCbdEta1Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZpoq_u50)(tyObject_KyberParams__KlUGF0jYQ5WfQZY9cBkZZOQ* p_p0, tyObject_Poly__OOcH647wDNJ3G2MVGodZ9cA* r_p1, NU8* buf_p2, NI buf_p2Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("polyCbdEta1Into", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/cbd.nim");
{nimErr_ = nimErrorFlag();
	nimln_(56);	switch ((*p_p0).eta1) {
	case ((NI)2):
	{
		nimln_(58);		cbd2__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZpoq_u4(r_p1, buf_p2, buf_p2Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((NI)3):
	{
		nimln_(60);		cbd3__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZpoq_u25(r_p1, buf_p2, buf_p2Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
		tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* T4_;
		T4_ = NIM_NIL;
		T4_ = (tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ*) nimNewObj(sizeof(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), NIM_ALIGNOF(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ));
		(*T4_).Sup.Sup.Sup.m_type = (&NTIv2__knMwTE9cBPqCO0qkZrysJgQ_);
		(*T4_).Sup.Sup.name = "ValueError";
		(*T4_).Sup.Sup.message = TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_26;
		(*T4_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(62);		raiseExceptionEx((Exception*)T4_, "ValueError", "polyCbdEta1Into", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/cbd.nim", 62);
goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, polyCbdEta2Into__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZpoq_u59)(tyObject_KyberParams__KlUGF0jYQ5WfQZY9cBkZZOQ* p_p0, tyObject_Poly__OOcH647wDNJ3G2MVGodZ9cA* r_p1, NU8* buf_p2, NI buf_p2Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("polyCbdEta2Into", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/cbd.nim");
{nimErr_ = nimErrorFlag();
	nimln_(70);	switch ((*p_p0).eta2) {
	case ((NI)2):
	{
		nimln_(72);		cbd2__OOZfepZcebgbpbyfZphfgbz95pelcgbZnflzzrgevpZcdZxloreZpoq_u4(r_p1, buf_p2, buf_p2Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
		tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* T3_;
		T3_ = NIM_NIL;
		T3_ = (tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ*) nimNewObj(sizeof(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), NIM_ALIGNOF(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ));
		(*T3_).Sup.Sup.Sup.m_type = (&NTIv2__knMwTE9cBPqCO0qkZrysJgQ_);
		(*T3_).Sup.Sup.name = "ValueError";
		(*T3_).Sup.Sup.message = TM__Fmj8NuTJ1tIp1CkKQ9aI8XA_28;
		(*T3_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(74);		raiseExceptionEx((Exception*)T3_, "ValueError", "polyCbdEta2Into", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/asymmetric/pq/kyber/cbd.nim", 74);
goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
}
