/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   /nix/store/788mx070y81zjlg5ipcl0cra3afviw9k-gcc-wrapper-15.2.0/bin/gcc -c -w -fmax-errors=3 -pthread   -I/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib -I/mnt/temp/CodingMain/Tyr-Crypto/tests -o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fphfgbz_pelcgb@fflzzrgevp@ftvzyv@ftvzyv.nim.c.o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fphfgbz_pelcgb@fflzzrgevp@ftvzyv@ftvzyv.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <x86intrin.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

static N_INLINE(void, gimliColumnRound__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZtvzyvZtvzyv_u4)(NU32* state_p0, NI column_p1);
static N_INLINE(NU32, rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZpunpunZpunpun20_u43)(NU32 value_p0, NI shift_p1);
static N_INLINE(int, shiftTypeTo__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZpunpunZpunpun20_u71)(NI shift_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4727)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4509;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2741;
	framePtr__flfgrz_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2741 = (*framePtr__flfgrz_u2741).prev;
}
static N_INLINE(int, shiftTypeTo__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZpunpunZpunpun20_u71)(NI shift_p1) {
	int result;
	nimfr_("shiftTypeTo", "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/bitops.nim");
{	result = (int)0;
	nimlf_(771, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/bitops.nim");	if ((shift_p1) < ((int)(-2147483647 -1)) || (shift_p1) > ((int)2147483647)){ raiseRangeErrorI(shift_p1, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
	}
	result = ((int) (shift_p1));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4509);
	return result;
}
static N_INLINE(NU32, rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZpunpunZpunpun20_u43)(NU32 value_p0, NI shift_p1) {
	NU32 result;
	int T1_;
	unsigned int T2_;
NIM_BOOL* nimErr_;
	nimfr_("rotateLeftBits", "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/bitops.nim");
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	nimln_(786);	nimln_(805);	T1_ = (int)0;
	T1_ = shiftTypeTo__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZpunpunZpunpun20_u71(shift_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (unsigned int)0;
	T2_ = __rold(((unsigned int) (value_p0)), T1_);
	result = ((NU32) (T2_));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, gimliColumnRound__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZtvzyvZtvzyv_u4)(NU32* state_p0, NI column_p1) {
	NU32 x_1;
	NU32 y_1;
	NU32 z_1;
	NI TM__3gIUOafIDiyg3BPejdcIIA_2;
	NI TM__3gIUOafIDiyg3BPejdcIIA_3;
	NI TM__3gIUOafIDiyg3BPejdcIIA_4;
	NI TM__3gIUOafIDiyg3BPejdcIIA_5;
NIM_BOOL* nimErr_;
	nimfr_("gimliColumnRound", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/gimli/gimli.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(13, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/gimli/gimli.nim");	x_1 = ((NU32)0);
	nimln_(14);	y_1 = ((NU32)0);
	nimln_(15);	z_1 = ((NU32)0);
	nimln_(16);	if ((NU)(column_p1) > (NU)(11)){ raiseIndexError2(column_p1, 11); goto BeforeRet_;
	}
	x_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZpunpunZpunpun20_u43(state_p0[(column_p1)- 0], ((NI)24));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(17);	if (nimAddInt(((NI)4), column_p1, &TM__3gIUOafIDiyg3BPejdcIIA_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NU)((NI)(TM__3gIUOafIDiyg3BPejdcIIA_2)) > (NU)(11)){ raiseIndexError2((NI)(TM__3gIUOafIDiyg3BPejdcIIA_2), 11); goto BeforeRet_;
	}
	y_1 = rotateLeftBits__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZpunpunZpunpun20_u43(state_p0[((NI)(TM__3gIUOafIDiyg3BPejdcIIA_2))- 0], ((NI)9));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(18);	if (nimAddInt(((NI)8), column_p1, &TM__3gIUOafIDiyg3BPejdcIIA_3)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NU)((NI)(TM__3gIUOafIDiyg3BPejdcIIA_3)) > (NU)(11)){ raiseIndexError2((NI)(TM__3gIUOafIDiyg3BPejdcIIA_3), 11); goto BeforeRet_;
	}
	z_1 = state_p0[((NI)(TM__3gIUOafIDiyg3BPejdcIIA_3))- 0];
	nimln_(19);	if (nimAddInt(((NI)8), column_p1, &TM__3gIUOafIDiyg3BPejdcIIA_4)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NU)((NI)(TM__3gIUOafIDiyg3BPejdcIIA_4)) > (NU)(11)){ raiseIndexError2((NI)(TM__3gIUOafIDiyg3BPejdcIIA_4), 11); goto BeforeRet_;
	}
	state_p0[((NI)(TM__3gIUOafIDiyg3BPejdcIIA_4))- 0] = (NU32)((NU32)(x_1 ^ (NU32)((NU64)(z_1) << (NU64)(((NI)1)))) ^ (NU32)((NU64)((NU32)(y_1 & z_1)) << (NU64)(((NI)2))));
	nimln_(20);	if (nimAddInt(((NI)4), column_p1, &TM__3gIUOafIDiyg3BPejdcIIA_5)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NU)((NI)(TM__3gIUOafIDiyg3BPejdcIIA_5)) > (NU)(11)){ raiseIndexError2((NI)(TM__3gIUOafIDiyg3BPejdcIIA_5), 11); goto BeforeRet_;
	}
	state_p0[((NI)(TM__3gIUOafIDiyg3BPejdcIIA_5))- 0] = (NU32)((NU32)(y_1 ^ x_1) ^ (NU32)((NU64)((NU32)(x_1 | z_1)) << (NU64)(((NI)1))));
	nimln_(21);	if ((NU)(column_p1) > (NU)(11)){ raiseIndexError2(column_p1, 11); goto BeforeRet_;
	}
	state_p0[(column_p1)- 0] = (NU32)((NU32)(z_1 ^ y_1) ^ (NU32)((NU64)((NU32)(x_1 & y_1)) << (NU64)(((NI)3))));
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, gimli_core_ref__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZtvzyvZtvzyv_u38)(NU32* state_p0) {
	NU32 round_1;
	NI column_1;
NIM_BOOL* nimErr_;
	nimfr_("gimli_core_ref", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/custom_crypto/symmetric/gimli/gimli.nim");
{nimErr_ = nimErrorFlag();
	nimln_(26);	round_1 = ((NU32)24);
	nimln_(27);	column_1 = ((NI)0);
	{
		nimln_(28);		while (1) {
			if (!((NU32)(((NU32)0)) < (NU32)(round_1))) goto LA2;
			nimln_(29);			column_1 = ((NI)0);
			{
				nimln_(30);				while (1) {
					NI TM__3gIUOafIDiyg3BPejdcIIA_6;
					if (!(column_1 < ((NI)4))) goto LA4;
					nimln_(31);					gimliColumnRound__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZtvzyvZtvzyv_u4(state_p0, column_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(32);					if (nimAddInt(column_1, ((NI)1), &TM__3gIUOafIDiyg3BPejdcIIA_6)) { raiseOverflow(); goto BeforeRet_;
					};
					column_1 = (NI)(TM__3gIUOafIDiyg3BPejdcIIA_6);
				} LA4: ;
			}
			nimln_(34);			switch ((NU32)(round_1 & ((NU32)3))) {
			case ((NU32)0):
			{
				NU32 T6_;
				NU32 T7_;
				nimln_(36);				T6_ = (NU32)0;
				T6_ = state_p0[(((NI)0))- 0];
				state_p0[(((NI)0))- 0] = state_p0[(((NI)1))- 0];
				state_p0[(((NI)1))- 0] = T6_;
				nimln_(37);				T7_ = (NU32)0;
				T7_ = state_p0[(((NI)2))- 0];
				state_p0[(((NI)2))- 0] = state_p0[(((NI)3))- 0];
				state_p0[(((NI)3))- 0] = T7_;
				nimln_(38);				state_p0[(((NI)0))- 0] = (NU32)(state_p0[(((NI)0))- 0] ^ (NU32)(((NU32)IL64(2654435584)) | round_1));
			}
			break;
			case ((NU32)2):
			{
				NU32 T9_;
				NU32 T10_;
				nimln_(40);				T9_ = (NU32)0;
				T9_ = state_p0[(((NI)0))- 0];
				state_p0[(((NI)0))- 0] = state_p0[(((NI)2))- 0];
				state_p0[(((NI)2))- 0] = T9_;
				nimln_(41);				T10_ = (NU32)0;
				T10_ = state_p0[(((NI)1))- 0];
				state_p0[(((NI)1))- 0] = state_p0[(((NI)3))- 0];
				state_p0[(((NI)3))- 0] = T10_;
			}
			break;
			default:
			{
			}
			break;
			}
			nimln_(45);			round_1 -= ((NI)1);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
