/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   /nix/store/788mx070y81zjlg5ipcl0cra3afviw9k-gcc-wrapper-15.2.0/bin/gcc -c -w -fmax-errors=3 -pthread   -I/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib -I/mnt/temp/CodingMain/Tyr-Crypto/tests -o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fjenccre@fonfvp_ncv.nim.c.o /mnt/temp/CodingMain/Tyr-Crypto/nimcache/test_public_api_surface_seeded/@z..@ffep@fcebgbpbyf@fjenccre@fonfvp_ncv.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <pthread.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_blake3HashM__K1qyMN4PCbvdVVVfWU9cbzQ tyObject_blake3HashM__K1qyMN4PCbvdVVVfWU9cbzQ;
typedef struct tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ;
typedef struct tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__lQYMoIzOpEqh2HdAFaxIkA tySequence__lQYMoIzOpEqh2HdAFaxIkA;
typedef struct tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content;
typedef struct tyObject_gimliHashM__AfLBPsDYS6suguA8bhGDMA tyObject_gimliHashM__AfLBPsDYS6suguA8bhGDMA;
typedef struct tyObject_sha3HashM__6WDChQnSjwmK7O9bqDON5yQ tyObject_sha3HashM__6WDChQnSjwmK7O9bqDON5yQ;
typedef struct tyObject_AsymKeypair__mMX1LOGlynHzPqX7bTK3fA tyObject_AsymKeypair__mMX1LOGlynHzPqX7bTK3fA;
typedef struct tyObject_SignatureKeypair__tj4GaKvR2x3SedT8vg2teQ tyObject_SignatureKeypair__tj4GaKvR2x3SedT8vg2teQ;
typedef struct tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
typedef long tyArray__JnDexEsSwd1sgw7BR9b59bgw[5];
typedef NU8 tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w;
struct tyObject_blake3HashM__K1qyMN4PCbvdVVVfWU9cbzQ {
	char dummy;
};
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__lQYMoIzOpEqh2HdAFaxIkA {
  NI len; tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQYMoIzOpEqh2HdAFaxIkA trace;
	Exception* up;
};
struct tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A {
	Exception Sup;
};
struct tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ {
	tyObject_CatchableError__lexsAjui0wsbT1qH7vUU7A Sup;
};
struct tyObject_gimliHashM__AfLBPsDYS6suguA8bhGDMA {
	char dummy;
};
struct tyObject_sha3HashM__6WDChQnSjwmK7O9bqDON5yQ {
	NU16 outLen;
};
struct tyObject_AsymKeypair__mMX1LOGlynHzPqX7bTK3fA {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ publicKey;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ secretKey;
};
typedef NU8 tyEnum_SignatureAlgorithm__kiijkWO23zuWe1s7T6mDWg;
struct tyObject_SignatureKeypair__tj4GaKvR2x3SedT8vg2teQ {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ publicKey;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ secretKey;
	tyEnum_SignatureAlgorithm__kiijkWO23zuWe1s7T6mDWg algorithm;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
typedef int tyArray__y9cEmKvKoWBNvZLJvncDPkg[1];
struct tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQYMoIzOpEqh2HdAFaxIkA_Content { NI cap; tyObject_StackTraceEntry__c6K0v4IveFMyM4wqlmrZZg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
static N_INLINE(void, initLock__pberZybpxf_u7)(pthread_mutex_t* lock_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NI, macOutLen__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1916)(tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w alg_p0, NI outLen_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__flfgrz_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, blake3CustomHmac__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZuznp_u350)(NU8* key_p0, NI key_p0Len_0, NU8* msg_p1, NI msg_p1Len_0, NI outLen_p2, NI blockLen_p3, NU8 constA_p4, NU8 constB_p5);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, gimliCustomHmac__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZuznp_u366)(NU8* key_p0, NI key_p0Len_0, NU8* msg_p1, NI msg_p1Len_0, NI outLen_p2, NI blockLen_p3, NU8 constA_p4, NU8 constB_p5);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, poly1305CustomHmac__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZuznp_u374)(NU8* key_p0, NI key_p0Len_0, NU8* msg_p1, NI msg_p1Len_0, NI outLen_p2, NI blockLen_p3, NU8 constA_p4, NU8 constB_p5);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, sha3CustomHmac__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZuznp_u387)(NU8* key_p0, NI key_p0Len_0, NU8* msg_p1, NI msg_p1Len_0, NI outLen_p2, NI blockLen_p3, NU8 constA_p4, NU8 constB_p5);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___cherZgvzrf_u2640)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, hmacCreate__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1920)(tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w alg_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p1, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ msg_p2, NI outLen_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___cherZgvzrf_u2631)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, constantTimeEqual__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1121)(NU8* a_p0, NI a_p0Len_0, NU8* b_p1, NI b_p1Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__flfgrzZzrzbel_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, toDigest32__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1063)(NU8* input_p0, NI input_p0Len_0, tyArray__vEOa9c5qaE9ajWxR5R4zwfQg Result);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, blake3Hash__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZoynxr3Zoynxr3_u1169)(NU8* input_p0, NI input_p0Len_0, NI outLen_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, gimliXof__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZtvzyvZtvzyv95fcbatr_u181)(NU8* ks_p0, NI ks_p0Len_0, NU8* ns_p1, NI ns_p1Len_0, NU8* ms_p2, NI ms_p2Len_0, NI outLen_p3);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, sha3Hash__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZuznp_u346)(NU8* input_p0, NI input_p0Len_0, NI outLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, signatureKeypair__OOZfepZcebgbpbyfZjenccreZurycrefZfvtangher95fhccbeg_u245)(tyEnum_SignatureAlgorithm__kiijkWO23zuWe1s7T6mDWg alg_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ seed_p1, tyObject_SignatureKeypair__tj4GaKvR2x3SedT8vg2teQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___cherZgvzrf_u2628)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfepZcebgbpbyfZjenccreZurycrefZfvtangher95fhccbeg_u339)(tyObject_SignatureKeypair__tj4GaKvR2x3SedT8vg2teQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
extern TNimTypeV2 NTIv2__knMwTE9cBPqCO0qkZrysJgQ_;
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__Lly9bsS8jW67q6QyyKjIBFQ_3 = { 23 | NIM_STRLIT_FLAG, "digest must be 32 bytes" };
static const NimStringV2 TM__Lly9bsS8jW67q6QyyKjIBFQ_4 = {23, (NimStrPayload*)&TM__Lly9bsS8jW67q6QyyKjIBFQ_3};
static const struct {
  NI cap; NIM_CHAR data[60+1];
} TM__Lly9bsS8jW67q6QyyKjIBFQ_6 = { 60 | NIM_STRLIT_FLAG, "hybrid signature combinations are not supported by basic_api" };
static const NimStringV2 TM__Lly9bsS8jW67q6QyyKjIBFQ_7 = {60, (NimStrPayload*)&TM__Lly9bsS8jW67q6QyyKjIBFQ_6};
N_LIB_PRIVATE tySequence__6H5Oh5UUvVCLiakt9aTwtUQ oqsEntropyExtra__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u406;
N_LIB_PRIVATE pthread_mutex_t oqsEntropyLock__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u401;
N_LIB_PRIVATE NU64 oqsEntropyCounter__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u407 = 0ULL;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__flfgrz_u4509;
extern NIM_THREADVAR TFrame* framePtr__flfgrz_u2741;
static N_INLINE(void, initLock__pberZybpxf_u7)(pthread_mutex_t* lock_p0) {
	pthread_mutex_init(lock_p0, ((pthread_mutexattr_t*) NIM_NIL));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__flfgrz_u4509);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__flfgrz_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__flfgrz_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__flfgrz_u2741;
	framePtr__flfgrz_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__flfgrz_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__flfgrz_u2741 = (*framePtr__flfgrz_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, macOutLen__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1916)(tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w alg_p0, NI outLen_p1) {
	NI result;
	nimfr_("macOutLen", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");
{	nimlf_(1311, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");	{
		if (!(((NI)0) < outLen_p1)) goto LA3_;
		nimln_(1312);		nimln_(1310);		nimln_(1312);		result = outLen_p1;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(1313);	switch (alg_p0) {
	case ((tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w)2):
	{
		nimln_(1315);		result = ((NI)16);
	}
	break;
	default:
	{
		nimln_(1317);		result = ((NI)32);
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, hmacCreate__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1920)(tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w alg_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p1, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ msg_p2, NI outLen_p3) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	NI resolvedOutLen_1;
NIM_BOOL* nimErr_;
	nimfr_("hmacCreate", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(1321);	resolvedOutLen_1 = macOutLen__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1916(alg_p0, outLen_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1322);	switch (alg_p0) {
	case ((tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w)0):
	{
		nimln_(1324);		result = blake3CustomHmac__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZuznp_u350(((key_p1).p) ? (key_p1.p->data) : NIM_NIL, key_p1.len, ((msg_p2).p) ? (msg_p2.p->data) : NIM_NIL, msg_p2.len, resolvedOutLen_1, ((NI)64), ((NU8)54), ((NU8)92));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w)1):
	{
		nimln_(1326);		result = gimliCustomHmac__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZuznp_u366(((key_p1).p) ? (key_p1.p->data) : NIM_NIL, key_p1.len, ((msg_p2).p) ? (msg_p2.p->data) : NIM_NIL, msg_p2.len, resolvedOutLen_1, ((NI)48), ((NU8)54), ((NU8)92));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w)2):
	{
		nimln_(1328);		result = poly1305CustomHmac__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZuznp_u374(((key_p1).p) ? (key_p1.p->data) : NIM_NIL, key_p1.len, ((msg_p2).p) ? (msg_p2.p->data) : NIM_NIL, msg_p2.len, resolvedOutLen_1, ((NI)0), ((NU8)54), ((NU8)92));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w)3):
	{
		nimln_(1330);		result = sha3CustomHmac__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZuznp_u387(((key_p1).p) ? (key_p1.p->data) : NIM_NIL, key_p1.len, ((msg_p2).p) ? (msg_p2.p->data) : NIM_NIL, msg_p2.len, resolvedOutLen_1, ((NI)0), ((NU8)54), ((NU8)92));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, constantTimeEqual__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1121)(NU8* a_p0, NI a_p0Len_0, NU8* b_p1, NI b_p1Len_0) {
	NIM_BOOL result;
	NU colontmpD_;
	NU colontmpD__2;
	NU diff_1;
	NI i_1;
	NU8 bByte_1;
	nimfr_("constantTimeEqual", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");
{	colontmpD_ = (NU)0;
	colontmpD__2 = (NU)0;
	nimln_(815);	{
		if (!(a_p0Len_0 == b_p1Len_0)) goto LA3_;
		colontmpD_ = ((NU)0);
		diff_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = ((NU)1);
		diff_1 = colontmpD__2;
	}
LA1_: ;
	nimln_(816);	i_1 = ((NI)0);
	nimln_(817);	bByte_1 = ((NU8)0);
	nimln_(818);	i_1 = ((NI)0);
	{
		nimln_(819);		while (1) {
			NU8 colontmpD__3;
			NU8 colontmpD__4;
			NI TM__Lly9bsS8jW67q6QyyKjIBFQ_2;
			if (!(i_1 < a_p0Len_0)) goto LA7;
			colontmpD__3 = (NU8)0;
			colontmpD__4 = (NU8)0;
			nimln_(820);			{
				if (!(i_1 < b_p1Len_0)) goto LA10_;
				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				colontmpD__3 = b_p1[i_1];
				bByte_1 = colontmpD__3;
			}
			goto LA8_;
LA10_: ;
			{
				colontmpD__4 = ((NU8)0);
				bByte_1 = colontmpD__4;
			}
LA8_: ;
			nimln_(821);			if (i_1 < 0 || i_1 >= a_p0Len_0){ raiseIndexError2(i_1,a_p0Len_0-1); goto BeforeRet_;
			}
			diff_1 = (NU)(diff_1 | ((NU) ((NU8)(a_p0[i_1] ^ bByte_1))));
			nimln_(822);			if (nimAddInt(i_1, ((NI)1), &TM__Lly9bsS8jW67q6QyyKjIBFQ_2)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__Lly9bsS8jW67q6QyyKjIBFQ_2);
		} LA7: ;
	}
	nimln_(823);	result = (diff_1 == ((NU)0));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hmacAuth__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1927)(tyEnum_MacAlgorithm__85W8Ng7fVgezrs9cWxaQ75w alg_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p1, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ msg_p2, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tag_p3, NI outLen_p4) {
	NIM_BOOL result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ expected_1;
	NI T2_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T3_;
NIM_BOOL* nimErr_;
	nimfr_("hmacAuth", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	expected_1.len = 0; expected_1.p = NIM_NIL;
	nimln_(1334);	expected_1.len = 0; expected_1.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	nimlf_(1772, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");	nimlf_(1335, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");	T2_ = (NI)0;
	T2_ = macOutLen__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1916(alg_p0, outLen_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = hmacCreate__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1920(alg_p0, key_p1, msg_p2, T2_);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___cherZgvzrf_u2631(T3_); goto LA1_;}
	nimlf_(1772, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");	eqsink___cherZgvzrf_u2640((&expected_1), T3_);
	nimlf_(1336, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");	result = constantTimeEqual__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1121(((expected_1).p) ? (expected_1.p->data) : NIM_NIL, expected_1.len, ((tag_p3).p) ? (tag_p3.p->data) : NIM_NIL, tag_p3.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(1772, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");		eqdestroy___cherZgvzrf_u2631(expected_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__flfgrzZzrzbel_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__flfgrzZzrzbel_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, toDigest32__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1063)(NU8* input_p0, NI input_p0Len_0, tyArray__vEOa9c5qaE9ajWxR5R4zwfQg Result) {
	nimfr_("toDigest32", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");
{	nimZeroMem((void*)Result, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
	nimlf_(780, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");	{
		tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* T5_;
		if (!!((input_p0Len_0 == ((NI)32)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ*) nimNewObj(sizeof(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), NIM_ALIGNOF(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__knMwTE9cBPqCO0qkZrysJgQ_);
		(*T5_).Sup.Sup.name = "ValueError";
		(*T5_).Sup.Sup.message = TM__Lly9bsS8jW67q6QyyKjIBFQ_4;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(781);		raiseExceptionEx((Exception*)T5_, "ValueError", "toDigest32", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim", 781);
goto BeforeRet_;
	}
LA3_: ;
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		nimlf_(128, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__Lly9bsS8jW67q6QyyKjIBFQ_5;
				if (!(i_2 < ((NI)32))) goto LA8;
				nimlf_(782, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");				i_1 = i_2;
				nimln_(783);				if ((NU)(i_1) > (NU)(31)){ raiseIndexError2(i_1, 31); goto BeforeRet_;
				}
				if (i_1 < 0 || i_1 >= input_p0Len_0){ raiseIndexError2(i_1,input_p0Len_0-1); goto BeforeRet_;
				}
				Result[(i_1)- 0] = input_p0[i_1];
				nimlf_(131, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__Lly9bsS8jW67q6QyyKjIBFQ_5)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__Lly9bsS8jW67q6QyyKjIBFQ_5);
			} LA8: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, hash__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u2074)(NU8* message_p0, NI message_p0Len_0, tyObject_blake3HashM__K1qyMN4PCbvdVVVfWU9cbzQ __p1, tyArray__vEOa9c5qaE9ajWxR5R4zwfQg Result) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("hash", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(1420, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");	colontmpD_ = blake3Hash__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZoynxr3Zoynxr3_u1169(message_p0, message_p0Len_0, ((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	toDigest32__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1063(((colontmpD_).p) ? (colontmpD_.p->data) : NIM_NIL, colontmpD_.len, Result);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(1772, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");		eqdestroy___cherZgvzrf_u2631(colontmpD_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, hash__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u2078)(NU8* message_p0, NI message_p0Len_0, tyObject_gimliHashM__AfLBPsDYS6suguA8bhGDMA __p1, tyArray__vEOa9c5qaE9ajWxR5R4zwfQg Result) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T2_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T3_;
NIM_BOOL* nimErr_;
	nimfr_("hash", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyArray__vEOa9c5qaE9ajWxR5R4zwfQg));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(1424, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");	T2_.len = 0; T2_.p = NIM_NIL;
	T2_.len = 0; T2_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_.len = 0; T3_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	colontmpD_ = gimliXof__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZtvzyvZtvzyv95fcbatr_u181(((T2_).p) ? (T2_.p->data) : NIM_NIL, T2_.len, ((T3_).p) ? (T3_.p->data) : NIM_NIL, T3_.len, message_p0, message_p0Len_0, ((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	toDigest32__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1063(((colontmpD_).p) ? (colontmpD_.p->data) : NIM_NIL, colontmpD_.len, Result);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(1772, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");		eqdestroy___cherZgvzrf_u2631(colontmpD_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, hash__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u2090)(NU8* message_p0, NI message_p0Len_0, tyObject_sha3HashM__6WDChQnSjwmK7O9bqDON5yQ m_p1) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	NI colontmpD_;
	NI colontmpD__2;
	NI outLen_1;
NIM_BOOL* nimErr_;
	nimfr_("hash", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimlf_(1428, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");	nimln_(1429);	{
		if (!(m_p1.outLen == ((NU16)0))) goto LA3_;
		colontmpD_ = ((NI)32);
		outLen_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(1430);		colontmpD__2 = ((NI) (m_p1.outLen));
		outLen_1 = colontmpD__2;
	}
LA1_: ;
	nimln_(1431);	result = sha3Hash__OOZfepZcebgbpbyfZphfgbz95pelcgbZflzzrgevpZuznp_u346(message_p0, message_p0Len_0, outLen_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___grfg95choyvp95ncv95fhesnpr_u703)(tyObject_AsymKeypair__mMX1LOGlynHzPqX7bTK3fA* dest_p0, tyObject_AsymKeypair__mMX1LOGlynHzPqX7bTK3fA* src_p1) {
	if ((*dest_p0).publicKey.p != (*src_p1).publicKey.p) {	eqdestroy___cherZgvzrf_u2631((*dest_p0).publicKey);
	}
(*dest_p0).publicKey.len = (*src_p1).publicKey.len; (*dest_p0).publicKey.p = (*src_p1).publicKey.p;
	if ((*dest_p0).secretKey.p != (*src_p1).secretKey.p) {	eqdestroy___cherZgvzrf_u2631((*dest_p0).secretKey);
	}
(*dest_p0).secretKey.len = (*src_p1).secretKey.len; (*dest_p0).secretKey.p = (*src_p1).secretKey.p;
}
N_LIB_PRIVATE N_NIMCALL(void, asymKeypair__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u1654)(tyEnum_SignatureAlgorithm__kiijkWO23zuWe1s7T6mDWg alg_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ seed_p1, tyObject_AsymKeypair__mMX1LOGlynHzPqX7bTK3fA* Result) {
	tyObject_SignatureKeypair__tj4GaKvR2x3SedT8vg2teQ kp0_1;
NIM_BOOL* nimErr_;
	nimfr_("asymKeypair", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_AsymKeypair__mMX1LOGlynHzPqX7bTK3fA));
	nimZeroMem((void*)(&kp0_1), sizeof(tyObject_SignatureKeypair__tj4GaKvR2x3SedT8vg2teQ));
	nimln_(1121);	{
		tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ* T6_;
		if (!(alg_p0 == ((tyEnum_SignatureAlgorithm__kiijkWO23zuWe1s7T6mDWg)2) || alg_p0 == ((tyEnum_SignatureAlgorithm__kiijkWO23zuWe1s7T6mDWg)3))) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ*) nimNewObj(sizeof(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ), NIM_ALIGNOF(tyObject_ValueError__knMwTE9cBPqCO0qkZrysJgQ));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__knMwTE9cBPqCO0qkZrysJgQ_);
		(*T6_).Sup.Sup.name = "ValueError";
		(*T6_).Sup.Sup.message = TM__Lly9bsS8jW67q6QyyKjIBFQ_7;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(1122);		raiseExceptionEx((Exception*)T6_, "ValueError", "asymKeypair", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim", 1122);
goto LA1_;
	}
LA4_: ;
	nimln_(1124);	signatureKeypair__OOZfepZcebgbpbyfZjenccreZurycrefZfvtangher95fhccbeg_u245(alg_p0, seed_p1, (&kp0_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(1772, "/nix/store/3k4xwgcqrlf4rya9x5lvq90cqcpyb8lj-nim-unwrapped-2.2.4/nim/lib/pure/times.nim");	eqsink___cherZgvzrf_u2640((&(*Result).publicKey), kp0_1.publicKey);
	eqwasMoved___cherZgvzrf_u2628((&kp0_1.publicKey));
	eqsink___cherZgvzrf_u2640((&(*Result).secretKey), kp0_1.secretKey);
	eqwasMoved___cherZgvzrf_u2628((&kp0_1.secretKey));
	{
		LA1_:;
	}
	{
		nimlf_(163, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/helpers/signature_support.nim");		eqdestroy___OOZfepZcebgbpbyfZjenccreZurycrefZfvtangher95fhccbeg_u339((&kp0_1));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___grfg95choyvp95ncv95fhesnpr_u694)(tyObject_AsymKeypair__mMX1LOGlynHzPqX7bTK3fA* dest_p0) {
	eqdestroy___cherZgvzrf_u2631((*dest_p0).publicKey);
	eqdestroy___cherZgvzrf_u2631((*dest_p0).secretKey);
}
N_LIB_PRIVATE N_NIMCALL(void, atzdotdotatffepatfcebgbpbyfatfjenccreatfonfvp_ncvdotnim_Init000)(void) {
{
	NIM_BOOL colontmpD_;
	NIM_BOOL T1_;
NIM_BOOL* nimErr_;
	nimfr_("basic_api", "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");
nimErr_ = nimErrorFlag();
	colontmpD_ = (NIM_BOOL)0;
	nimlf_(549, "/mnt/temp/CodingMain/Tyr-Crypto/src/protocols/wrapper/basic_api.nim");	oqsEntropyExtra__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u406.len = 0; oqsEntropyExtra__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u406.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	nimln_(552);	T1_ = (NIM_BOOL)0;
	{
		nimln_(553);		initLock__pberZybpxf_u7((&oqsEntropyLock__OOZfepZcebgbpbyfZjenccreZonfvp95ncv_u401));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD_ = NIM_TRUE;
		T1_ = colontmpD_;
	}
	(void)(T1_);
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

