/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -mavx2 -maes -msse2 -O3 -fno-ident -fno-math-errno   -IK:\Progz\nim-2.2.6\lib -IF:\CodingMain\Tyr-Crypto\tests -o F:\CodingMain\Tyr-Crypto\.nimcache\test_sigma_perf_frodo_profile_r\@mtest_sigma_perf_frodo_profile.nim.c.o F:\CodingMain\Tyr-Crypto\.nimcache\test_sigma_perf_frodo_profile_r\@mtest_sigma_perf_frodo_profile.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ;
typedef struct tySequence__1OnGjxKFu6Njn9cN6Dg4AKw tySequence__1OnGjxKFu6Njn9cN6Dg4AKw;
typedef struct tySequence__1OnGjxKFu6Njn9cN6Dg4AKw_Content tySequence__1OnGjxKFu6Njn9cN6Dg4AKw_Content;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ;
typedef struct tySequence__iGdAJC3phThjM84OoSUKow tySequence__iGdAJC3phThjM84OoSUKow;
typedef struct tySequence__iGdAJC3phThjM84OoSUKow_Content tySequence__iGdAJC3phThjM84OoSUKow_Content;
typedef struct tySequence__8C4HJUexy7DvB1lHTkEPKQ tySequence__8C4HJUexy7DvB1lHTkEPKQ;
typedef struct tySequence__8C4HJUexy7DvB1lHTkEPKQ_Content tySequence__8C4HJUexy7DvB1lHTkEPKQ_Content;
typedef struct tySequence__YUlAMkMhimCiWNhkaauP8A tySequence__YUlAMkMhimCiWNhkaauP8A;
typedef struct tySequence__YUlAMkMhimCiWNhkaauP8A_Content tySequence__YUlAMkMhimCiWNhkaauP8A_Content;
typedef struct tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA;
typedef struct tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA;
typedef struct tyObject_BenchResult__nXBqWyFShCxXOZxeYcpzJA tyObject_BenchResult__nXBqWyFShCxXOZxeYcpzJA;
typedef struct tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og;
typedef struct tyObject_FrodoTyrKeypair__69anhgmS9c8bIeiiq4OAUFBQ tyObject_FrodoTyrKeypair__69anhgmS9c8bIeiiq4OAUFBQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_FrodoTyrCipher__EsFlFs0kybVD0EsKRBE6WQ tyObject_FrodoTyrCipher__EsFlFs0kybVD0EsKRBE6WQ;
typedef struct tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA;
typedef struct tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg;
typedef struct Exception Exception;
typedef struct tySequence__Eio1jF59abEpv9bLmutTDQvQ tySequence__Eio1jF59abEpv9bLmutTDQvQ;
typedef struct tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content;
typedef struct tyObject_TestResult__7TJvynIbQiY0kX6IItl1uA tyObject_TestResult__7TJvynIbQiY0kX6IItl1uA;
typedef struct tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw;
typedef struct tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA;
typedef struct tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__1OnGjxKFu6Njn9cN6Dg4AKw {
  NI len; tySequence__1OnGjxKFu6Njn9cN6Dg4AKw_Content* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ {
	RootObj Sup;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NU8 tyEnum_TestStatus__GZYsWtk2SzAvP8QZWAE89cg;
struct tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ {
	NimStringV2 buildRoot;
	NimStringV2 metadataPath;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ metadata;
};
struct tySequence__iGdAJC3phThjM84OoSUKow {
  NI len; tySequence__iGdAJC3phThjM84OoSUKow_Content* p;
};
struct tySequence__8C4HJUexy7DvB1lHTkEPKQ {
  NI len; tySequence__8C4HJUexy7DvB1lHTkEPKQ_Content* p;
};
struct tySequence__YUlAMkMhimCiWNhkaauP8A {
  NI len; tySequence__YUlAMkMhimCiWNhkaauP8A_Content* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef NimStringV2 tyArray__24KAM9afIUgUaqBaEBB6r9bg[3];
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA {
	NimStringV2 name;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA run;
};
struct tyObject_BenchResult__nXBqWyFShCxXOZxeYcpzJA {
	NimStringV2 name;
	NI loops;
	NI64 totalTicks;
	NI64 avgTicks;
};
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_FrodoVariant__nzbmMFwrNDxAlgIrNNqU8w;
struct tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og {
	RootObj Sup;
	tyEnum_FrodoVariant__nzbmMFwrNDxAlgIrNNqU8w v0;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_FrodoTyrKeypair__69anhgmS9c8bIeiiq4OAUFBQ {
	tyEnum_FrodoVariant__nzbmMFwrNDxAlgIrNNqU8w variant;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ publicKey;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ secretKey;
};
struct tyObject_FrodoTyrCipher__EsFlFs0kybVD0EsKRBE6WQ {
	tyEnum_FrodoVariant__nzbmMFwrNDxAlgIrNNqU8w variant;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ ciphertext;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ sharedSecret;
};
struct tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA {
	RootObj Sup;
	tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* kem0;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ pk1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ sk2;
	NimStringV2 name3;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ ct4;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ ssE5;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ ssD6;
};
typedef NimStringV2 tyArray__haiLFy0nBviVTKFGuwztzQ[5];
struct tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg {
	NI rc;
	NI rootIdx;
};
struct tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA {
	NCSTRING method_name;
	NCSTRING alg_version;
	int claimed_nist_level;
	int is_ind_cca;
	size_t length_public_key;
	size_t length_secret_key;
	size_t length_ciphertext;
	size_t length_shared_secret;
	size_t length_keypair_seed;
	size_t length_encaps_seed;
};
struct tySequence__Eio1jF59abEpv9bLmutTDQvQ {
  NI len; tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__Eio1jF59abEpv9bLmutTDQvQ trace;
	Exception* up;
};
struct tyObject_TestResult__7TJvynIbQiY0kX6IItl1uA {
	NimStringV2 suiteName;
	NimStringV2 testName;
	tyEnum_TestStatus__GZYsWtk2SzAvP8QZWAE89cg status;
};
struct tySequence__1OnGjxKFu6Njn9cN6Dg4AKw_Content { NI cap; tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__iGdAJC3phThjM84OoSUKow_Content { NI cap; tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* data[SEQ_DECL_SIZE]; };
struct tySequence__8C4HJUexy7DvB1lHTkEPKQ_Content { NI cap; tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA data[SEQ_DECL_SIZE]; };
struct tySequence__YUlAMkMhimCiWNhkaauP8A_Content { NI cap; tyObject_BenchResult__nXBqWyFShCxXOZxeYcpzJA data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content { NI cap; tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, ensureInitialized__pureZunittest_u1185)(void);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u65)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, NimStringV2 suiteName_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shouldRun__pureZunittest_u912)(NimStringV2 currentSuiteName_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u3748)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u69)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, loadProfileInfo__test95sigma95perf95frodo95profile_u11)(tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ* Result);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u34)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2667)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPathOpenArray)(NimStringV2* parts_p0, NI parts_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetCurrentDir)(void);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2658)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2661)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitLines)(NimStringV2 s_p0, NIM_BOOL keepEol_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readFile__stdZsyncio_u624)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3739)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, printProfileInfo__test95sigma95perf95frodo95profile_u15)(tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ* info_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ensureLibOqsLoaded__OOZsrcZprotocolsZbindingsZliboqs_u636)(void);
N_LIB_PRIVATE N_NIMCALL(void, checkpoint__pureZunittest_u1677)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___test95sigma95perf95frodo95profile_u564)(tySequence__8C4HJUexy7DvB1lHTkEPKQ* dest_p0, tySequence__8C4HJUexy7DvB1lHTkEPKQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, buildCustomFrodoRoundtrip__test95sigma95perf95frodo95profile_u24)(NimStringV2 name_p0, tyEnum_FrodoVariant__nzbmMFwrNDxAlgIrNNqU8w v_p1, tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA* Result);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u3942)(tyProc__HzVCwACFYM9cx9aV62PdjtuA* dest_p0, tyProc__HzVCwACFYM9cx9aV62PdjtuA src_p1);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___test95sigma95perf95frodo95profile_u28)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, frodoTyrKeypair__OOZsrcZprotocolsZcustom95cryptoZfrodoZoperations_u1908)(tyEnum_FrodoVariant__nzbmMFwrNDxAlgIrNNqU8w v_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ randomness_p1, tyObject_FrodoTyrKeypair__69anhgmS9c8bIeiiq4OAUFBQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, frodoTyrEncaps__OOZsrcZprotocolsZcustom95cryptoZfrodoZoperations_u2278)(tyEnum_FrodoVariant__nzbmMFwrNDxAlgIrNNqU8w v_p0, NU8* pk_p1, NI pk_p1Len_0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ randomness_p2, tyObject_FrodoTyrCipher__EsFlFs0kybVD0EsKRBE6WQ* Result);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, frodoTyrDecaps__OOZsrcZprotocolsZcustom95cryptoZfrodoZoperations_u2332)(tyEnum_FrodoVariant__nzbmMFwrNDxAlgIrNNqU8w v_p0, NU8* sk_p1, NI sk_p1Len_0, NU8* ct_p2, NI ct_p2Len_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___test95sigma95perf95frodo95profile_u32)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ y_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2632)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZprotocolsZcustom95cryptoZfrodoZoperations_u2312)(tyObject_FrodoTyrCipher__EsFlFs0kybVD0EsKRBE6WQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZprotocolsZcustom95cryptoZfrodoZoperations_u1994)(tyObject_FrodoTyrKeypair__69anhgmS9c8bIeiiq4OAUFBQ* dest_p0);
static N_INLINE(void, nimMarkCyclic)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, buildOqsKemRoundtrip__test95sigma95perf95frodo95profile_u113)(NimStringV2 name_p0, NimStringV2 algId_p1, tySequence__iGdAJC3phThjM84OoSUKow* holders_p2, tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA* Result);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95sigma95perf95frodo95profile_u1080)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sigma95perf95frodo95profile_u1007)(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA*, OQS_KEM_new__OOZsrcZprotocolsZbindingsZliboqs_u639)(NCSTRING algId_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZtimes_u2641)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sigma95perf95frodo95profile_u1044)(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3431)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__test95sigma95perf95frodo95profile_u148)(tySequence__iGdAJC3phThjM84OoSUKow* x_p0, tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* y_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__OOZsrcZprotocolsZcustom95cryptoZfrodoZutil_u50)(NI len_p0);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___test95sigma95perf95frodo95profile_u273)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, requireSuccess__OOZsrcZprotocolsZbindingsZliboqs_u811)(int status_p0, NimStringV2 action_p1);
N_LIB_PRIVATE N_NIMCALL(int, OQS_KEM_keypair__OOZsrcZprotocolsZbindingsZliboqs_u669)(tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* kem_p0, NU8* public_key_p1, NU8* secret_key_p2);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(int, OQS_KEM_encaps__OOZsrcZprotocolsZbindingsZliboqs_u681)(tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* kem_p0, NU8* ciphertext_p1, NU8* shared_secret_p2, NU8* public_key_p3);
N_LIB_PRIVATE N_NIMCALL(int, OQS_KEM_decaps__OOZsrcZprotocolsZbindingsZliboqs_u687)(tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* kem_p0, NU8* shared_secret_p1, NU8* ciphertext_p2, NU8* secret_key_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95sigma95perf95frodo95profile_u1041)(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZ83igma4566ench65nd69valZsrcZprotocolsZbenchmarks_u92)(tySequence__YUlAMkMhimCiWNhkaauP8A* dest_p0, tySequence__YUlAMkMhimCiWNhkaauP8A src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__YUlAMkMhimCiWNhkaauP8A, compareAlgorithms__OOZOOZ83igma4566ench65nd69valZsrcZprotocolsZbenchmarks_u12)(tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA* algos_p0, NI algos_p0Len_0, NI loops_p1, NI warmup_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZ83igma4566ench65nd69valZsrcZprotocolsZbenchmarks_u83)(tySequence__YUlAMkMhimCiWNhkaauP8A dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u74)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2);
static N_INLINE(void, quit__system_u8177)(NI errorcode_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatBenchResults__OOZOOZ83igma4566ench65nd69valZsrcZprotocolsZbenchmarks_u288)(tyObject_BenchResult__nXBqWyFShCxXOZxeYcpzJA* results_p0, NI results_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, OQS_KEM_free__OOZsrcZprotocolsZbindingsZliboqs_u661)(tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* kem_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sigma95perf95frodo95profile_u555)(tySequence__8C4HJUexy7DvB1lHTkEPKQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sigma95perf95frodo95profile_u437)(tySequence__iGdAJC3phThjM84OoSUKow dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sigma95perf95frodo95profile_u413)(tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ* dest_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZtypedthreads_u187)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
static N_INLINE(NimStringV2, exceptionTypeName__pureZunittest_u1667)(Exception* e_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
static N_INLINE(NimStringV2, getCurrentExceptionMsg__system_u8142)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getStackTrace__system_u3981)(Exception* e_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZtypedthreads_u184)(Exception* dest_p0);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, raiseDefect)(void);
N_LIB_PRIVATE N_NIMCALL(void, setProgramResult__stdZexitprocs_u241)(NI a_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2664)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u1658)(tyObject_TestResult__7TJvynIbQiY0kX6IItl1uA* testResult_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sigma95perf95frodo95profile_u867)(tyObject_TestResult__7TJvynIbQiY0kX6IItl1uA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u1618)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, chckNilDisp)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u795)(tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw* formatter_p0, NimStringV2 suiteName_p1);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u567)(tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA* formatter_p0, NimStringV2 suiteName_p1);
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u62)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, NimStringV2 suiteName_p1);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u798)(tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw* formatter_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u618)(tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA* formatter_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u66)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, NimStringV2 testName_p1);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u805)(tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u621)(tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2);
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u70)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u832)(tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw* formatter_p0, tyObject_TestResult__7TJvynIbQiY0kX6IItl1uA* testResult_p1);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u630)(tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA* formatter_p0, tyObject_TestResult__7TJvynIbQiY0kX6IItl1uA* testResult_p1);
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u75)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, tyObject_TestResult__7TJvynIbQiY0kX6IItl1uA* testResult_p1);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u888)(tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u717)(tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u79)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatsexitprocsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpterminaldotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpunittestdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssysranddotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatsmonotimesdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpprotocolsatsbindingsatsliboqsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[31+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_2 = { 31 | NIM_STRLIT_FLAG, "Sigma Frodo profile performance" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_3 = {31, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_2};
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_4 = {31, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_2};
static const struct {
  NI cap; NIM_CHAR data[51+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_5 = { 51 | NIM_STRLIT_FLAG, "compare Tyr Frodo against one explicit liboqs build" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_6 = {51, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_5};
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_7 = {51, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_5};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_8 = { 17 | NIM_STRLIT_FLAG, "LIBOQS_BUILD_ROOT" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_9 = {17, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_8};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_10 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_11 = {0, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_10};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__jM27Cl58K9aw1WymP9a7uCbg_12 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_13 = {0, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_10};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_14 = { 5 | NIM_STRLIT_FLAG, "build" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_15 = {5, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_14};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_16 = { 6 | NIM_STRLIT_FLAG, "liboqs" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_17 = {6, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_16};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_18 = { 7 | NIM_STRLIT_FLAG, "install" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_19 = {7, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_18};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_20 = { 22 | NIM_STRLIT_FLAG, "tyr_liboqs_profile.txt" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_21 = {22, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_20};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_22 = { 22 | NIM_STRLIT_FLAG, "## liboqs build root: " };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_23 = {22, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_22};
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_24 = { 28 | NIM_STRLIT_FLAG, "## liboqs profile metadata: " };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_25 = {28, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_24};
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_27 = { 34 | NIM_STRLIT_FLAG, "## liboqs profile metadata missing" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_28 = { 3 | NIM_STRLIT_FLAG, "## " };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_29 = {3, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_28};
static const struct {
  NI cap; NIM_CHAR data[60+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_30 = { 60 | NIM_STRLIT_FLAG, "liboqs runtime unavailable; skipping Frodo profile benchmark" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_31 = {60, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_30};
N_LIB_PRIVATE TNimTypeV2 NTIv2__LtqdWAjAyGx6PhuxclJ2Og_;
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_33 = { 70 | NIM_STRLIT_FLAG, "test_sigma_perf_frodo_profile.nim(53, 5) `shared == env.sharedSecret` " };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_34 = {70, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_33};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_35 = { 25 | NIM_STRLIT_FLAG, "tyr_frodo976aes_roundtrip" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_36 = {25, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_35};
N_LIB_PRIVATE TNimTypeV2 NTIv2__FwS8DHdxI9cjI0FChDKNinA_;
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_38 = { 9 | NIM_STRLIT_FLAG, "Skipping " };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_39 = {9, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_38};
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_40 = { 32 | NIM_STRLIT_FLAG, ": liboqs algorithm unavailable (" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_41 = {32, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_40};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_42 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_43 = {1, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_42};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_44 = { 8 | NIM_STRLIT_FLAG, "_keypair" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_45 = {8, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_44};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_46 = { 7 | NIM_STRLIT_FLAG, "_encaps" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_47 = {7, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_46};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_48 = { 7 | NIM_STRLIT_FLAG, "_decaps" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_49 = {7, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_48};
static const struct {
  NI cap; NIM_CHAR data[54+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_50 = { 54 | NIM_STRLIT_FLAG, "test_sigma_perf_frodo_profile.nim(78, 7) `ssD == ssE` " };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_51 = {54, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_50};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_52 = { 25 | NIM_STRLIT_FLAG, "oqs_frodo976aes_roundtrip" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_53 = {25, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_52};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_54 = { 16 | NIM_STRLIT_FLAG, "FrodoKEM-976-AES" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_55 = {16, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_54};
static const struct {
  NI cap; NIM_CHAR data[113+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_56 = { 113 | NIM_STRLIT_FLAG, "F:\\CodingMain\\Tyr-Crypto\\tests\\test_sigma_perf_frodo_profile.nim(106, 26): Check failed: results.len == algos.len" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_57 = {113, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_56};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_58 = { 16 | NIM_STRLIT_FLAG, "results.len was " };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_59 = {16, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_58};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_60 = { 14 | NIM_STRLIT_FLAG, "algos.len was " };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_61 = {14, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_60};
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_62 = {0, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_63 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_64 = {1, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_63};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_65 = { 19 | NIM_STRLIT_FLAG, "<foreign exception>" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_66 = {19, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_65};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_67 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_68 = {1, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_67};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_69 = { 21 | NIM_STRLIT_FLAG, "Unhandled exception: " };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_70 = {21, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_69};
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_71 = {0, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_72 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_73 = {1, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_72};
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_74 = {21, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_69};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__jM27Cl58K9aw1WymP9a7uCbg_75 = { 22 | NIM_STRLIT_FLAG, " [<foreign exception>]" };
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_76 = {22, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_75};
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_77 = {0, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_10};
static const NimStringV2 TM__jM27Cl58K9aw1WymP9a7uCbg_78 = {51, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_5};
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__jM27Cl58K9aw1WymP9a7uCbg_26 = {{34, (NimStrPayload*)&TM__jM27Cl58K9aw1WymP9a7uCbg_27}}
;
N_LIB_PRIVATE NimStringV2 testSuiteName__test95sigma95perf95frodo95profile_u287;
N_LIB_PRIVATE tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ** formatter__test95sigma95perf95frodo95profile_u291;
extern NIM_THREADVAR tySequence__1OnGjxKFu6Njn9cN6Dg4AKw formatters__pureZunittest_u46;
extern NIM_THREADVAR tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints__pureZunittest_u45;
N_LIB_PRIVATE tyEnum_TestStatus__GZYsWtk2SzAvP8QZWAE89cg testStatusIMPL__test95sigma95perf95frodo95profile_u296 = ((tyEnum_TestStatus__GZYsWtk2SzAvP8QZWAE89cg)0);
N_LIB_PRIVATE tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ** formatter__test95sigma95perf95frodo95profile_u300;
N_LIB_PRIVATE tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ info__test95sigma95perf95frodo95profile_u301;
N_LIB_PRIVATE tySequence__iGdAJC3phThjM84OoSUKow holders__test95sigma95perf95frodo95profile_u306;
N_LIB_PRIVATE tySequence__8C4HJUexy7DvB1lHTkEPKQ algos__test95sigma95perf95frodo95profile_u311;
N_LIB_PRIVATE tySequence__YUlAMkMhimCiWNhkaauP8A results__test95sigma95perf95frodo95profile_u316;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4319;
N_LIB_PRIVATE NI i__test95sigma95perf95frodo95profile_u317 = ((NI)0);
static NIM_CONST NU32 TM__jM27Cl58K9aw1WymP9a7uCbg_32[2] = {3701606400, 3667744768};
N_LIB_PRIVATE TNimTypeV2 NTIv2__LtqdWAjAyGx6PhuxclJ2Og_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og), .align = (NI16) NIM_ALIGNOF(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og), .depth = 1, .display = TM__jM27Cl58K9aw1WymP9a7uCbg_32, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__jM27Cl58K9aw1WymP9a7uCbg_37[2] = {3701606400, 79432704};
N_LIB_PRIVATE TNimTypeV2 NTIv2__FwS8DHdxI9cjI0FChDKNinA_ = {.destructor = (void*)rttiDestroy__test95sigma95perf95frodo95profile_u1080, .size = sizeof(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA), .align = (NI16) NIM_ALIGNOF(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA), .depth = 1, .display = TM__jM27Cl58K9aw1WymP9a7uCbg_37, .traceImpl = (void*)NIM_NIL, .flags = 0};
N_LIB_PRIVATE NI colonc1___test95sigma95perf95frodo95profile_u346;
N_LIB_PRIVATE NI colonc2___test95sigma95perf95frodo95profile_u351;
N_LIB_PRIVATE tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ** formatterX60gensym11___test95sigma95perf95frodo95profile_u356;
extern NIM_THREADVAR NIM_BOOL abortOnError__pureZunittest_u44;
extern NIM_THREADVAR Exception* currException__system_u4026;
N_LIB_PRIVATE Exception* e__test95sigma95perf95frodo95profile_u361;
N_LIB_PRIVATE NimStringV2 eTypeDesc__test95sigma95perf95frodo95profile_u362;
N_LIB_PRIVATE NimStringV2 stackTrace__test95sigma95perf95frodo95profile_u363;
N_LIB_PRIVATE tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ** formatterX60gensym12___test95sigma95perf95frodo95profile_u368;
N_LIB_PRIVATE tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ** formatterX60gensym13___test95sigma95perf95frodo95profile_u377;
N_LIB_PRIVATE tyObject_TestResult__7TJvynIbQiY0kX6IItl1uA testResult__test95sigma95perf95frodo95profile_u386;
extern tySequence__sM4lkSb7zS6F7OVMvW9cffQ extraLibCandidates__OOZsrcZprotocolsZbindingsZliboqs_u223;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4319);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, loadProfileInfo__test95sigma95perf95frodo95profile_u11)(tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ* Result) {
	NimStringV2 buildRoot_1;
	NimStringV2 colontmpD_;
	NimStringV2 metadataPath_1;
	tyArray__24KAM9afIUgUaqBaEBB6r9bg T11_;
	NimStringV2 T12_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ));
	buildRoot_1.len = 0; buildRoot_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	metadataPath_1.len = 0; metadataPath_1.p = NIM_NIL;
	colontmpD_ = getEnv__stdZenvvars_u34(TM__jM27Cl58K9aw1WymP9a7uCbg_9, TM__jM27Cl58K9aw1WymP9a7uCbg_11);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	buildRoot_1 = nsuStrip(colontmpD_, NIM_TRUE, NIM_TRUE, TM__jM27Cl58K9aw1WymP9a7uCbg_12);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	metadataPath_1 = TM__jM27Cl58K9aw1WymP9a7uCbg_13;
	{
		NimStringV2 colontmpD__2;
		tyArray__24KAM9afIUgUaqBaEBB6r9bg T7_;
		NimStringV2 T8_;
		if (!(buildRoot_1.len == ((NI)0))) goto LA4_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		colontmpD__2 = nosgetCurrentDir();
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		T7_[0] = colontmpD__2;
		T7_[1] = TM__jM27Cl58K9aw1WymP9a7uCbg_15;
		T7_[2] = TM__jM27Cl58K9aw1WymP9a7uCbg_17;
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = nosjoinPathOpenArray(T7_, 3);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T8_); goto LA6_;}
		eqsink___system_u2667((&buildRoot_1), T8_);
		{
			LA6_:;
		}
		{
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA4_: ;
	T11_[0] = buildRoot_1;
	T11_[1] = TM__jM27Cl58K9aw1WymP9a7uCbg_19;
	T11_[2] = TM__jM27Cl58K9aw1WymP9a7uCbg_21;
	T12_.len = 0; T12_.p = NIM_NIL;
	T12_ = nosjoinPathOpenArray(T11_, 3);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T12_); goto LA1_;}
	eqsink___system_u2667((&metadataPath_1), T12_);
	eqsink___system_u2667((&(*Result).buildRoot), buildRoot_1);
	eqwasMoved___system_u2658((&buildRoot_1));
	eqcopy___system_u2661((&(*Result).metadataPath), metadataPath_1);
	{
		NIM_BOOL T15_;
		NimStringV2 colontmpD__3;
		tySequence__sM4lkSb7zS6F7OVMvW9cffQ T19_;
		T15_ = (NIM_BOOL)0;
		T15_ = nosfileExists(metadataPath_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!T15_) goto LA16_;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		colontmpD__3 = readFile__stdZsyncio_u624(metadataPath_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA18_;
		T19_.len = 0; T19_.p = NIM_NIL;
		T19_ = nsuSplitLines(colontmpD__3, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u3739(T19_); goto LA18_;}
		eqsink___system_u3748((&(*Result).metadata), T19_);
		{
			LA18_:;
		}
		{
			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA16_: ;
	{
		LA1_:;
	}
	{
		if (metadataPath_1.p && !(metadataPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(metadataPath_1.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (buildRoot_1.p && !(buildRoot_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(buildRoot_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, printProfileInfo__test95sigma95perf95frodo95profile_u15)(tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ* info_p0) {
	NI i_1;
	tyArray__Re75IspeoxXy2oCZHwcRrA T1_;
	tyArray__Re75IspeoxXy2oCZHwcRrA T2_;
{	i_1 = ((NI)0);
	T1_[0] = TM__jM27Cl58K9aw1WymP9a7uCbg_23;
	T1_[1] = (*info_p0).buildRoot;
	echoBinSafe(T1_, 2);
	T2_[0] = TM__jM27Cl58K9aw1WymP9a7uCbg_25;
	T2_[1] = (*info_p0).metadataPath;
	echoBinSafe(T2_, 2);
	{
		NI T5_;
		T5_ = (*info_p0).metadata.len;
		if (!(T5_ == ((NI)0))) goto LA6_;
		echoBinSafe(TM__jM27Cl58K9aw1WymP9a7uCbg_26, 1);
		goto BeforeRet_;
	}
LA6_: ;
	i_1 = ((NI)0);
	{
		while (1) {
			NI T10_;
			T10_ = (*info_p0).metadata.len;
			if (!(i_1 < T10_)) goto LA9;
			{
				tyArray__Re75IspeoxXy2oCZHwcRrA T15_;
				if (!(((NI)0) < (*info_p0).metadata.p->data[i_1].len)) goto LA13_;
				T15_[0] = TM__jM27Cl58K9aw1WymP9a7uCbg_29;
				T15_[1] = (*info_p0).metadata.p->data[i_1];
				echoBinSafe(T15_, 2);
			}
LA13_: ;
			i_1 = (NI)(i_1 + ((NI)1));
		} LA9: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___test95sigma95perf95frodo95profile_u28)(void* ClE_0) {
	tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og* colonenvP__1;
	tyObject_FrodoTyrKeypair__69anhgmS9c8bIeiiq4OAUFBQ kp_1;
	tyObject_FrodoTyrCipher__EsFlFs0kybVD0EsKRBE6WQ env_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ shared_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T2_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colonenvP__1 = (tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og*) ClE_0;
	nimZeroMem((void*)(&kp_1), sizeof(tyObject_FrodoTyrKeypair__69anhgmS9c8bIeiiq4OAUFBQ));
	nimZeroMem((void*)(&env_1), sizeof(tyObject_FrodoTyrCipher__EsFlFs0kybVD0EsKRBE6WQ));
	shared_1.len = 0; shared_1.p = NIM_NIL;
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_.len = 0; T2_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	frodoTyrKeypair__OOZsrcZprotocolsZcustom95cryptoZfrodoZoperations_u1908((*colonenvP__1).v0, T2_, (&kp_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_.len = 0; T3_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	frodoTyrEncaps__OOZsrcZprotocolsZcustom95cryptoZfrodoZoperations_u2278((*colonenvP__1).v0, ((kp_1.publicKey).p) ? (kp_1.publicKey.p->data) : NIM_NIL, kp_1.publicKey.len, T3_, (&env_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	shared_1 = frodoTyrDecaps__OOZsrcZprotocolsZcustom95cryptoZfrodoZoperations_u2332((*colonenvP__1).v0, ((kp_1.secretKey).p) ? (kp_1.secretKey.p->data) : NIM_NIL, kp_1.secretKey.len, ((env_1.ciphertext).p) ? (env_1.ciphertext.p->data) : NIM_NIL, env_1.ciphertext.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = eqeq___test95sigma95perf95frodo95profile_u32(shared_1, env_1.sharedSecret);
		if (!!(T6_)) goto LA7_;
		failedAssertImpl__stdZassertions_u234(TM__jM27Cl58K9aw1WymP9a7uCbg_34);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA7_: ;
	{
		LA1_:;
	}
	{
		eqdestroy___pureZtimes_u2632(shared_1);
		eqdestroy___OOZsrcZprotocolsZcustom95cryptoZfrodoZoperations_u2312((&env_1));
		eqdestroy___OOZsrcZprotocolsZcustom95cryptoZfrodoZoperations_u1994((&kp_1));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimMarkCyclic)(void* p_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, buildCustomFrodoRoundtrip__test95sigma95perf95frodo95profile_u24)(NimStringV2 name_p0, tyEnum_FrodoVariant__nzbmMFwrNDxAlgIrNNqU8w v_p1, tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA* Result) {
	tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og* colonenv__1;
	tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og* T1_;
	tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og* blitTmp_1;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T2_;
	nimZeroMem((void*)Result, sizeof(tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA));
	colonenv__1 = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og*) nimNewObj(sizeof(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og), NIM_ALIGNOF(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildCustomFrodoRoundtrip___LtqdWAjAyGx6PhuxclJ2Og));
	(*T1_).Sup.m_type = (&NTIv2__LtqdWAjAyGx6PhuxclJ2Og_);
	colonenv__1 = T1_;
	(*colonenv__1).v0 = v_p1;
	eqcopy___system_u2661((&(*Result).name), name_p0);
	blitTmp_1 = colonenv__1;
	nimMarkCyclic(colonenv__1);
	nimZeroMem((void*)(&T2_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T2_.ClP_0 = colonanonymous___test95sigma95perf95frodo95profile_u28; T2_.ClE_0 = blitTmp_1;
	eqsink___system_u3942((&(*Result).run), T2_);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sigma95perf95frodo95profile_u1007)(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA* dest_p0) {
	eqdestroy___pureZtimes_u2632((*dest_p0).ssD6);
	eqdestroy___pureZtimes_u2632((*dest_p0).ssE5);
	eqdestroy___pureZtimes_u2632((*dest_p0).ct4);
	if ((*dest_p0).name3.p && !((*dest_p0).name3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).name3.p);
}
	eqdestroy___pureZtimes_u2632((*dest_p0).sk2);
	eqdestroy___pureZtimes_u2632((*dest_p0).pk1);
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__test95sigma95perf95frodo95profile_u1080)(void* dest_p0) {
	eqdestroy___test95sigma95perf95frodo95profile_u1007(((tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA*) (dest_p0)));
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p_p0, TNimTypeV2* desc_p1) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__k08a1tJo9av1ZQ0pmWpy6yg*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		rememberCycle__system_u3431(result, cell_1, desc_p1);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sigma95perf95frodo95profile_u1044)(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicStatic(dest_p0, ((TNimTypeV2*) ((&NTIv2__FwS8DHdxI9cjI0FChDKNinA_))));
		if (!T3_) goto LA4_;
		eqdestroy___test95sigma95perf95frodo95profile_u1007((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___test95sigma95perf95frodo95profile_u273)(void* ClE_0) {
	tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA* colonenvP__1;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* T2_;
	NU8* T3_;
	int T4_;
	NimStringV2 T5_;
	tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* T6_;
	NU8* T7_;
	NU8* T8_;
	int T9_;
	NimStringV2 T10_;
	tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* T11_;
	NU8* T12_;
	NU8* T13_;
	int T14_;
	NimStringV2 T15_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colonenvP__1 = (tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA*) ClE_0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	T2_ = (tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA*)0;
	T2_ = (*colonenvP__1).kem0;
	T3_ = (NU8*)0;
	T3_ = (&(*colonenvP__1).pk1.p->data[((NI)0)]);
	T4_ = (int)0;
	T4_ = OQS_KEM_keypair__OOZsrcZprotocolsZbindingsZliboqs_u669(T2_, T3_, (&(*colonenvP__1).sk2.p->data[((NI)0)]));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T5_.len = 0; T5_.p = NIM_NIL;
	T5_ = rawNewString((*colonenvP__1).name3.len + 8);
appendString((&T5_), (*colonenvP__1).name3);
appendString((&T5_), TM__jM27Cl58K9aw1WymP9a7uCbg_45);
	colontmpD_ = T5_;
	requireSuccess__OOZsrcZprotocolsZbindingsZliboqs_u811(T4_, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T6_ = (tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA*)0;
	T6_ = (*colonenvP__1).kem0;
	T7_ = (NU8*)0;
	T7_ = (&(*colonenvP__1).ct4.p->data[((NI)0)]);
	T8_ = (NU8*)0;
	T8_ = (&(*colonenvP__1).ssE5.p->data[((NI)0)]);
	T9_ = (int)0;
	T9_ = OQS_KEM_encaps__OOZsrcZprotocolsZbindingsZliboqs_u681(T6_, T7_, T8_, (&(*colonenvP__1).pk1.p->data[((NI)0)]));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T10_.len = 0; T10_.p = NIM_NIL;
	T10_ = rawNewString((*colonenvP__1).name3.len + 7);
appendString((&T10_), (*colonenvP__1).name3);
appendString((&T10_), TM__jM27Cl58K9aw1WymP9a7uCbg_47);
	colontmpD__2 = T10_;
	requireSuccess__OOZsrcZprotocolsZbindingsZliboqs_u811(T9_, colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T11_ = (tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA*)0;
	T11_ = (*colonenvP__1).kem0;
	T12_ = (NU8*)0;
	T12_ = (&(*colonenvP__1).ssD6.p->data[((NI)0)]);
	T13_ = (NU8*)0;
	T13_ = (&(*colonenvP__1).ct4.p->data[((NI)0)]);
	T14_ = (int)0;
	T14_ = OQS_KEM_decaps__OOZsrcZprotocolsZbindingsZliboqs_u687(T11_, T12_, T13_, (&(*colonenvP__1).sk2.p->data[((NI)0)]));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T15_.len = 0; T15_.p = NIM_NIL;
	T15_ = rawNewString((*colonenvP__1).name3.len + 7);
appendString((&T15_), (*colonenvP__1).name3);
appendString((&T15_), TM__jM27Cl58K9aw1WymP9a7uCbg_49);
	colontmpD__3 = T15_;
	requireSuccess__OOZsrcZprotocolsZbindingsZliboqs_u811(T14_, colontmpD__3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = eqeq___test95sigma95perf95frodo95profile_u32((*colonenvP__1).ssD6, (*colonenvP__1).ssE5);
		if (!!(T18_)) goto LA19_;
		failedAssertImpl__stdZassertions_u234(TM__jM27Cl58K9aw1WymP9a7uCbg_51);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA19_: ;
	{
		LA1_:;
	}
	{
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___test95sigma95perf95frodo95profile_u1041)(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, buildOqsKemRoundtrip__test95sigma95perf95frodo95profile_u113)(NimStringV2 name_p0, NimStringV2 algId_p1, tySequence__iGdAJC3phThjM84OoSUKow* holders_p2, tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA* Result) {
	tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA* colonenv__1;
	tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* colontmpD_;
	tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA* T2_;
	tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA* T3_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T4_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T5_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T6_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T7_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T8_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T14_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T15_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T16_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T17_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T18_;
	tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA* blitTmp_1;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T19_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA));
	colonenv__1 = NIM_NIL;
	colontmpD_ = (tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA*)0;
	T2_ = NIM_NIL;
	T2_ = (tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA*) nimNewObj(sizeof(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA), NIM_ALIGNOF(tyObject_Env_test_sigma_perf_frodo_profiledotnim_buildOqsKemRoundtrip___FwS8DHdxI9cjI0FChDKNinA));
	(*T2_).Sup.m_type = (&NTIv2__FwS8DHdxI9cjI0FChDKNinA_);
	colonenv__1 = T2_;
	eqcopy___system_u2661((&(*colonenv__1).name3), name_p0);
	T3_ = (tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA*)0;
	T3_ = OQS_KEM_new__OOZsrcZprotocolsZbindingsZliboqs_u639(nimToCStringConv(algId_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*colonenv__1).kem0 = T3_;
	T4_.len = 0; T4_.p = NIM_NIL;
	T4_.len = 0; T4_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	eqsink___pureZtimes_u2641((&(*colonenv__1).pk1), T4_);
	T5_.len = 0; T5_.p = NIM_NIL;
	T5_.len = 0; T5_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	eqsink___pureZtimes_u2641((&(*colonenv__1).sk2), T5_);
	T6_.len = 0; T6_.p = NIM_NIL;
	T6_.len = 0; T6_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	eqsink___pureZtimes_u2641((&(*colonenv__1).ct4), T6_);
	T7_.len = 0; T7_.p = NIM_NIL;
	T7_.len = 0; T7_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	eqsink___pureZtimes_u2641((&(*colonenv__1).ssE5), T7_);
	T8_.len = 0; T8_.p = NIM_NIL;
	T8_.len = 0; T8_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	eqsink___pureZtimes_u2641((&(*colonenv__1).ssD6), T8_);
	{
		tyArray__haiLFy0nBviVTKFGuwztzQ T13_;
		if (!((*colonenv__1).kem0 == ((tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA*) NIM_NIL))) goto LA11_;
		T13_[0] = TM__jM27Cl58K9aw1WymP9a7uCbg_39;
		T13_[1] = (*colonenv__1).name3;
		T13_[2] = TM__jM27Cl58K9aw1WymP9a7uCbg_41;
		T13_[3] = algId_p1;
		T13_[4] = TM__jM27Cl58K9aw1WymP9a7uCbg_43;
		echoBinSafe(T13_, 5);
		eqdestroy___test95sigma95perf95frodo95profile_u1044(colonenv__1);
		goto BeforeRet_;
	}
LA11_: ;
	colontmpD_ = (*colonenv__1).kem0;
	add__test95sigma95perf95frodo95profile_u148((&(*holders_p2)), colontmpD_);
	T14_.len = 0; T14_.p = NIM_NIL;
	T14_ = newSeq__OOZsrcZprotocolsZcustom95cryptoZfrodoZutil_u50((((NI) ((*(*colonenv__1).kem0).length_public_key))));
	eqsink___pureZtimes_u2641((&(*colonenv__1).pk1), T14_);
	T15_.len = 0; T15_.p = NIM_NIL;
	T15_ = newSeq__OOZsrcZprotocolsZcustom95cryptoZfrodoZutil_u50((((NI) ((*(*colonenv__1).kem0).length_secret_key))));
	eqsink___pureZtimes_u2641((&(*colonenv__1).sk2), T15_);
	T16_.len = 0; T16_.p = NIM_NIL;
	T16_ = newSeq__OOZsrcZprotocolsZcustom95cryptoZfrodoZutil_u50((((NI) ((*(*colonenv__1).kem0).length_ciphertext))));
	eqsink___pureZtimes_u2641((&(*colonenv__1).ct4), T16_);
	T17_.len = 0; T17_.p = NIM_NIL;
	T17_ = newSeq__OOZsrcZprotocolsZcustom95cryptoZfrodoZutil_u50((((NI) ((*(*colonenv__1).kem0).length_shared_secret))));
	eqsink___pureZtimes_u2641((&(*colonenv__1).ssE5), T17_);
	T18_.len = 0; T18_.p = NIM_NIL;
	T18_ = newSeq__OOZsrcZprotocolsZcustom95cryptoZfrodoZutil_u50((((NI) ((*(*colonenv__1).kem0).length_shared_secret))));
	eqsink___pureZtimes_u2641((&(*colonenv__1).ssD6), T18_);
	eqcopy___system_u2661((&(*Result).name), (*colonenv__1).name3);
	blitTmp_1 = colonenv__1;
	nimMarkCyclic(colonenv__1);
	eqwasMoved___test95sigma95perf95frodo95profile_u1041(&colonenv__1);
	nimZeroMem((void*)(&T19_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T19_.ClP_0 = colonanonymous___test95sigma95perf95frodo95profile_u273; T19_.ClE_0 = blitTmp_1;
	eqsink___system_u3942((&(*Result).run), T19_);
	{
		LA1_:;
	}
	{
		eqdestroy___test95sigma95perf95frodo95profile_u1044(colonenv__1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, quit__system_u8177)(NI errorcode_p0) {
	{
		if (!(errorcode_p0 < ((NI)(-2147483647 -1)))) goto LA3_;
		exit(((int)(-2147483647 -1)));
	}
	goto LA1_;
LA3_: ;
	{
		if (!(((NI)2147483647) < errorcode_p0)) goto LA6_;
		exit(((int)2147483647));
	}
	goto LA1_;
LA6_: ;
	{
		exit(((int) (errorcode_p0)));
	}
LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sigma95perf95frodo95profile_u413)(tyObject_ProfileInfo__B1BqanegRJovMaykXvvogQ* dest_p0) {
	eqdestroy___system_u3739((*dest_p0).metadata);
	if ((*dest_p0).metadataPath.p && !((*dest_p0).metadataPath.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).metadataPath.p);
}
	if ((*dest_p0).buildRoot.p && !((*dest_p0).buildRoot.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).buildRoot.p);
}
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = currException__system_u4026;
	return result;
}
static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	result = NIM_NIL;
	eqcopy___stdZtypedthreads_u187(&result, currException__system_u4026, NIM_FALSE);
	return result;
}
static N_INLINE(NimStringV2, exceptionTypeName__pureZunittest_u1667)(Exception* e_p0) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!(e_p0 == ((Exception*) NIM_NIL))) goto LA4_;
		result = TM__jM27Cl58K9aw1WymP9a7uCbg_66;
	}
	goto LA2_;
LA4_: ;
	{
		result = cstrToNimstr((*e_p0).name);
	}
LA2_: ;
	return result;
}
static N_INLINE(NimStringV2, getCurrentExceptionMsg__system_u8142)(void) {
	NimStringV2 result;
	NimStringV2 T1_;
{	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!(currException__system_u4026 == ((Exception*) NIM_NIL))) goto LA4_;
		result = TM__jM27Cl58K9aw1WymP9a7uCbg_71;
	}
	goto LA2_;
LA4_: ;
	{
		eqcopy___system_u2661((&result), (*currException__system_u4026).message);
	}
LA2_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___stdZtypedthreads_u187(&currException__system_u4026, (*currException__system_u4026).up, NIM_FALSE);
}
N_LIB_PRIVATE N_NIMCALL(void, suiteStarted__pureZunittest_u65)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, NimStringV2 suiteName_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	chckNilDisp(formatter_p0);
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 2806603008)))) goto LA3_;
		suiteStarted__pureZunittest_u795(((tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw*) (formatter_p0)), suiteName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 3020471040)))) goto LA6_;
		suiteStarted__pureZunittest_u567(((tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA*) (formatter_p0)), suiteName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 3573266944)))) goto LA9_;
		suiteStarted__pureZunittest_u62(formatter_p0, suiteName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, testStarted__pureZunittest_u69)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, NimStringV2 testName_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	chckNilDisp(formatter_p0);
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 2806603008)))) goto LA3_;
		testStarted__pureZunittest_u798(((tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw*) (formatter_p0)), testName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 3020471040)))) goto LA6_;
		testStarted__pureZunittest_u618(((tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA*) (formatter_p0)), testName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 3573266944)))) goto LA9_;
		testStarted__pureZunittest_u66(formatter_p0, testName_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, failureOccurred__pureZunittest_u74)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ checkpoints_p1, NimStringV2 stackTrace_p2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	chckNilDisp(formatter_p0);
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 2806603008)))) goto LA3_;
		failureOccurred__pureZunittest_u805(((tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw*) (formatter_p0)), checkpoints_p1, stackTrace_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 3020471040)))) goto LA6_;
		failureOccurred__pureZunittest_u621(((tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA*) (formatter_p0)), checkpoints_p1, stackTrace_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 3573266944)))) goto LA9_;
		failureOccurred__pureZunittest_u70(formatter_p0, checkpoints_p1, stackTrace_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, testEnded__pureZunittest_u78)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0, tyObject_TestResult__7TJvynIbQiY0kX6IItl1uA* testResult_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	chckNilDisp(formatter_p0);
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 2806603008)))) goto LA3_;
		testEnded__pureZunittest_u832(((tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw*) (formatter_p0)), testResult_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 3020471040)))) goto LA6_;
		testEnded__pureZunittest_u630(((tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA*) (formatter_p0)), testResult_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 3573266944)))) goto LA9_;
		testEnded__pureZunittest_u75(formatter_p0, testResult_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, suiteEnded__pureZunittest_u81)(tyObject_OutputFormattercolonObjectType___VdT7ujziOj81GHmU2ybyRQ* formatter_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	chckNilDisp(formatter_p0);
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 2806603008)))) goto LA3_;
		suiteEnded__pureZunittest_u888(((tyObject_JUnitOutputFormattercolonObjectType___PadJXaYAJY9a4B9cwG9aVzutw*) (formatter_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 2, 3020471040)))) goto LA6_;
		suiteEnded__pureZunittest_u717(((tyObject_ConsoleOutputFormattercolonObjectType___bbQIuzZfeXvBlD3UpAMGBA*) (formatter_p0)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		if (!((formatter_p0) && (isObjDisplayCheck((*formatter_p0).Sup.m_type, 1, 3573266944)))) goto LA9_;
		suiteEnded__pureZunittest_u79(formatter_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA9_: ;
LA1_: ;
	}BeforeRet_: ;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atpstdatsexitprocsdotnim_Init000();
	atpstdatssynciodotnim_Init000();
	atpwinleandotnim_Init000();
	atpunittestdotnim_Init000();
	atpprotocolsatsbindingsatsliboqsdotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpstdatssynciodotnim_DatInit000();
	atpsystemdotnim_Init000();
	atpwinleandotnim_DatInit000();
	atpterminaldotnim_DatInit000();
	atpstdatssysranddotnim_DatInit000();
	atpstdatsmonotimesdotnim_DatInit000();
	(*inner)();
#else
	atpstdatssynciodotnim_DatInit000();
	atpsystemdotnim_Init000();
	atpwinleandotnim_DatInit000();
	atpterminaldotnim_DatInit000();
	atpstdatssysranddotnim_DatInit000();
	atpstdatsmonotimesdotnim_DatInit000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
NIM_BOOL oldNimErrFin26_;
NIM_BOOL oldNimErrFin18_;
NIM_BOOL oldNimErrFin3_;
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	{
		testSuiteName__test95sigma95perf95frodo95profile_u287 = TM__jM27Cl58K9aw1WymP9a7uCbg_3;
		ensureInitialized__pureZunittest_u1185();
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		{
			NI i_1;
			NI L_1;
			NI T5_;
			i_1 = ((NI)0);
			T5_ = formatters__pureZunittest_u46.len;
			L_1 = T5_;
			{
				while (1) {
					if (!(i_1 < L_1)) goto LA7;
					formatter__test95sigma95perf95frodo95profile_u291 = &formatters__pureZunittest_u46.p->data[i_1];
					suiteStarted__pureZunittest_u65((*formatter__test95sigma95perf95frodo95profile_u291), TM__jM27Cl58K9aw1WymP9a7uCbg_4);
					if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
					i_1 += ((NI)1);
				} LA7: ;
			}
		}
		ensureInitialized__pureZunittest_u1185();
		if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
		{
			NIM_BOOL T10_;
			tySequence__sM4lkSb7zS6F7OVMvW9cffQ T13_;
			T10_ = (NIM_BOOL)0;
			T10_ = shouldRun__pureZunittest_u912(testSuiteName__test95sigma95perf95frodo95profile_u287, TM__jM27Cl58K9aw1WymP9a7uCbg_6);
			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
			if (!T10_) goto LA11_;
			T13_.len = 0; T13_.p = NIM_NIL;
			T13_.len = 0; T13_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
			eqsink___system_u3748((&checkpoints__pureZunittest_u45), T13_);
			{
				NI i_2;
				NI L_2;
				NI T15_;
				i_2 = ((NI)0);
				T15_ = formatters__pureZunittest_u46.len;
				L_2 = T15_;
				{
					while (1) {
						if (!(i_2 < L_2)) goto LA17;
						formatter__test95sigma95perf95frodo95profile_u300 = &formatters__pureZunittest_u46.p->data[i_2];
						testStarted__pureZunittest_u69((*formatter__test95sigma95perf95frodo95profile_u300), TM__jM27Cl58K9aw1WymP9a7uCbg_7);
						if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
						i_2 += ((NI)1);
					} LA17: ;
				}
			}
			loadProfileInfo__test95sigma95perf95frodo95profile_u11((&info__test95sigma95perf95frodo95profile_u301));
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			holders__test95sigma95perf95frodo95profile_u306.len = 0; holders__test95sigma95perf95frodo95profile_u306.p = (tySequence__iGdAJC3phThjM84OoSUKow_Content*) newSeqPayload(0, sizeof(tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA*), NIM_ALIGNOF(tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA*));
			algos__test95sigma95perf95frodo95profile_u311.len = 0; algos__test95sigma95perf95frodo95profile_u311.p = (tySequence__8C4HJUexy7DvB1lHTkEPKQ_Content*) newSeqPayload(0, sizeof(tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA), NIM_ALIGNOF(tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA));
			results__test95sigma95perf95frodo95profile_u316.len = 0; results__test95sigma95perf95frodo95profile_u316.p = (tySequence__YUlAMkMhimCiWNhkaauP8A_Content*) newSeqPayload(0, sizeof(tyObject_BenchResult__nXBqWyFShCxXOZxeYcpzJA), NIM_ALIGNOF(tyObject_BenchResult__nXBqWyFShCxXOZxeYcpzJA));
			printProfileInfo__test95sigma95perf95frodo95profile_u15((&info__test95sigma95perf95frodo95profile_u301));
			if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			{
				NIM_BOOL T22_;
				T22_ = (NIM_BOOL)0;
				T22_ = ensureLibOqsLoaded__OOZsrcZprotocolsZbindingsZliboqs_u636();
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				if (!!(T22_)) goto LA23_;
				checkpoint__pureZunittest_u1677(TM__jM27Cl58K9aw1WymP9a7uCbg_31);
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			}
			goto LA20_;
LA23_: ;
			{
				NimStringV2 colontmpD_;
				tySequence__8C4HJUexy7DvB1lHTkEPKQ T28_;
				tySequence__YUlAMkMhimCiWNhkaauP8A T29_;
				tyArray__nHXaesL0DJZHyVS07ARPRA T54_;
				NimStringV2 T55_;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				T28_.len = 0; T28_.p = NIM_NIL;
				T28_.len = 2; T28_.p = (tySequence__8C4HJUexy7DvB1lHTkEPKQ_Content*) newSeqPayload(2, sizeof(tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA), NIM_ALIGNOF(tyObject_BenchAlgo__YdEl6AGAVp4RtrhLq7ZOgA));
				buildCustomFrodoRoundtrip__test95sigma95perf95frodo95profile_u24(TM__jM27Cl58K9aw1WymP9a7uCbg_36, ((tyEnum_FrodoVariant__nzbmMFwrNDxAlgIrNNqU8w)0), (&T28_.p->data[0]));
				if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
				buildOqsKemRoundtrip__test95sigma95perf95frodo95profile_u113(TM__jM27Cl58K9aw1WymP9a7uCbg_53, TM__jM27Cl58K9aw1WymP9a7uCbg_55, (&holders__test95sigma95perf95frodo95profile_u306), (&T28_.p->data[1]));
				if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
				eqsink___test95sigma95perf95frodo95profile_u564((&algos__test95sigma95perf95frodo95profile_u311), T28_);
				T29_.len = 0; T29_.p = NIM_NIL;
				T29_ = compareAlgorithms__OOZOOZ83igma4566ench65nd69valZsrcZprotocolsZbenchmarks_u12(((algos__test95sigma95perf95frodo95profile_u311).p) ? (algos__test95sigma95perf95frodo95profile_u311.p->data) : NIM_NIL, algos__test95sigma95perf95frodo95profile_u311.len, ((NI)5), ((NI)1));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZOOZ83igma4566ench65nd69valZsrcZprotocolsZbenchmarks_u83(T29_); goto LA27_;}
				eqsink___OOZOOZ83igma4566ench65nd69valZsrcZprotocolsZbenchmarks_u92((&results__test95sigma95perf95frodo95profile_u316), T29_);
				{
					NI T31_;
					NI T32_;
					T31_ = results__test95sigma95perf95frodo95profile_u316.len;
					colonc1___test95sigma95perf95frodo95profile_u346 = T31_;
					T32_ = algos__test95sigma95perf95frodo95profile_u311.len;
					colonc2___test95sigma95perf95frodo95profile_u351 = T32_;
					{
						if (!(colonc1___test95sigma95perf95frodo95profile_u346 == colonc2___test95sigma95perf95frodo95profile_u351)) goto LA35_;
					}
					goto LA33_;
LA35_: ;
					{
						NimStringV2 colontmpD__2;
						NimStringV2 colontmpD__3;
						NimStringV2 colontmpD__4;
						NimStringV2 colontmpD__5;
						NimStringV2 T39_;
						NimStringV2 T40_;
						NimStringV2 T41_;
						NimStringV2 T42_;
						tySequence__sM4lkSb7zS6F7OVMvW9cffQ T51_;
						colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
						colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
						colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
						colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
						checkpoint__pureZunittest_u1677(TM__jM27Cl58K9aw1WymP9a7uCbg_57);
						if (NIM_UNLIKELY(*nimErr_)) goto LA38_;
						T39_.len = 0; T39_.p = NIM_NIL;
						T40_.len = 0; T40_.p = NIM_NIL;
						T40_ = dollar___systemZdollars_u14(colonc1___test95sigma95perf95frodo95profile_u346);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T40_); goto LA38_;}
						colontmpD__2 = T40_;
						T39_ = rawNewString(colontmpD__2.len + 16);
appendString((&T39_), TM__jM27Cl58K9aw1WymP9a7uCbg_59);
appendString((&T39_), colontmpD__2);
						colontmpD__3 = T39_;
						checkpoint__pureZunittest_u1677(colontmpD__3);
						if (NIM_UNLIKELY(*nimErr_)) goto LA38_;
						T41_.len = 0; T41_.p = NIM_NIL;
						T42_.len = 0; T42_.p = NIM_NIL;
						T42_ = dollar___systemZdollars_u14(colonc2___test95sigma95perf95frodo95profile_u351);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T42_); goto LA38_;}
						colontmpD__4 = T42_;
						T41_ = rawNewString(colontmpD__4.len + 14);
appendString((&T41_), TM__jM27Cl58K9aw1WymP9a7uCbg_61);
appendString((&T41_), colontmpD__4);
						colontmpD__5 = T41_;
						checkpoint__pureZunittest_u1677(colontmpD__5);
						if (NIM_UNLIKELY(*nimErr_)) goto LA38_;
						testStatusIMPL__test95sigma95perf95frodo95profile_u296 = ((tyEnum_TestStatus__GZYsWtk2SzAvP8QZWAE89cg)1);
						ensureInitialized__pureZunittest_u1185();
						if (NIM_UNLIKELY(*nimErr_)) goto LA38_;
						{
							NI i_3;
							NI L_3;
							NI T44_;
							i_3 = ((NI)0);
							T44_ = formatters__pureZunittest_u46.len;
							L_3 = T44_;
							{
								while (1) {
									if (!(i_3 < L_3)) goto LA46;
									formatterX60gensym11___test95sigma95perf95frodo95profile_u356 = &formatters__pureZunittest_u46.p->data[i_3];
									failureOccurred__pureZunittest_u74((*formatterX60gensym11___test95sigma95perf95frodo95profile_u356), checkpoints__pureZunittest_u45, TM__jM27Cl58K9aw1WymP9a7uCbg_62);
									if (NIM_UNLIKELY(*nimErr_)) goto LA38_;
									i_3 += ((NI)1);
								} LA46: ;
							}
						}
						{
							if (!abortOnError__pureZunittest_u44) goto LA49_;
							quit__system_u8177(((NI)1));
						}
LA49_: ;
						T51_.len = 0; T51_.p = NIM_NIL;
						T51_.len = 0; T51_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
						eqsink___system_u3748((&checkpoints__pureZunittest_u45), T51_);
						{
							LA38_:;
						}
						{
							if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
							if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
							if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
							if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
					}
LA33_: ;
				}
				T55_.len = 0; T55_.p = NIM_NIL;
				T55_ = formatBenchResults__OOZOOZ83igma4566ench65nd69valZsrcZprotocolsZbenchmarks_u288(((results__test95sigma95perf95frodo95profile_u316).p) ? (results__test95sigma95perf95frodo95profile_u316.p->data) : NIM_NIL, results__test95sigma95perf95frodo95profile_u316.len);
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T55_); goto LA27_;}
				colontmpD_ = T55_;
				T54_[0] = colontmpD_;
				echoBinSafe(T54_, 1);
				{
					LA27_:;
				}
				{
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
				{
					LA26_:;
				}
				{
					oldNimErrFin26_ = *nimErr_; *nimErr_ = NIM_FALSE;
					i__test95sigma95perf95frodo95profile_u317 = ((NI)0);
					{
						while (1) {
							NI T62_;
							T62_ = holders__test95sigma95perf95frodo95profile_u306.len;
							if (!(i__test95sigma95perf95frodo95profile_u317 < T62_)) goto LA61;
							{
								if (!!((holders__test95sigma95perf95frodo95profile_u306.p->data[i__test95sigma95perf95frodo95profile_u317] == ((tyObject_OqsKem__eVMQfWnBJ5RoGJfcD63lwA*) NIM_NIL)))) goto LA65_;
								OQS_KEM_free__OOZsrcZprotocolsZbindingsZliboqs_u661(holders__test95sigma95perf95frodo95profile_u306.p->data[i__test95sigma95perf95frodo95profile_u317]);
								if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
							}
LA65_: ;
							i__test95sigma95perf95frodo95profile_u317 = (NI)(i__test95sigma95perf95frodo95profile_u317 + ((NI)1));
						} LA61: ;
					}
					*nimErr_ = oldNimErrFin26_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
			}
LA20_: ;
			{
				LA19_:;
			}
			{
				eqdestroy___OOZOOZ83igma4566ench65nd69valZsrcZprotocolsZbenchmarks_u83(results__test95sigma95perf95frodo95profile_u316);
				eqdestroy___test95sigma95perf95frodo95profile_u555(algos__test95sigma95perf95frodo95profile_u311);
				eqdestroy___test95sigma95perf95frodo95profile_u437(holders__test95sigma95perf95frodo95profile_u306);
				eqdestroy___test95sigma95perf95frodo95profile_u413((&info__test95sigma95perf95frodo95profile_u301));
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA18_;
			if (NIM_UNLIKELY(*nimErr_)) {
				LA18_:;
				if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 1, 1285336064)) {
					NimStringV2 colontmpD__6;
					NimStringV2 colontmpD__7;
					NimStringV2 colontmpD__8;
					NimStringV2 T73_;
					NimStringV2 T74_;
					NimStringV2 T75_;
					tySequence__sM4lkSb7zS6F7OVMvW9cffQ T84_;
					*nimErr_ = NIM_FALSE;
					colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
					colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
					colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
					e__test95sigma95perf95frodo95profile_u361 = getCurrentException();
					T73_.len = 0; T73_.p = NIM_NIL;
					T74_.len = 0; T74_.p = NIM_NIL;
					T74_ = exceptionTypeName__pureZunittest_u1667(e__test95sigma95perf95frodo95profile_u361);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T74_); goto LA72_;}
					colontmpD__6 = T74_;
					T73_ = rawNewString(colontmpD__6.len + 2);
appendString((&T73_), TM__jM27Cl58K9aw1WymP9a7uCbg_64);
appendString((&T73_), colontmpD__6);
appendString((&T73_), TM__jM27Cl58K9aw1WymP9a7uCbg_68);
					eTypeDesc__test95sigma95perf95frodo95profile_u362 = T73_;
					T75_.len = 0; T75_.p = NIM_NIL;
					colontmpD__7 = getCurrentExceptionMsg__system_u8142();
					T75_ = rawNewString(colontmpD__7.len + eTypeDesc__test95sigma95perf95frodo95profile_u362.len + 22);
appendString((&T75_), TM__jM27Cl58K9aw1WymP9a7uCbg_70);
appendString((&T75_), colontmpD__7);
appendString((&T75_), TM__jM27Cl58K9aw1WymP9a7uCbg_73);
appendString((&T75_), eTypeDesc__test95sigma95perf95frodo95profile_u362);
					colontmpD__8 = T75_;
					checkpoint__pureZunittest_u1677(colontmpD__8);
					if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
					stackTrace__test95sigma95perf95frodo95profile_u363 = getStackTrace__system_u3981(e__test95sigma95perf95frodo95profile_u361);
					testStatusIMPL__test95sigma95perf95frodo95profile_u296 = ((tyEnum_TestStatus__GZYsWtk2SzAvP8QZWAE89cg)1);
					ensureInitialized__pureZunittest_u1185();
					if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
					{
						NI i_4;
						NI L_4;
						NI T77_;
						i_4 = ((NI)0);
						T77_ = formatters__pureZunittest_u46.len;
						L_4 = T77_;
						{
							while (1) {
								if (!(i_4 < L_4)) goto LA79;
								formatterX60gensym12___test95sigma95perf95frodo95profile_u368 = &formatters__pureZunittest_u46.p->data[i_4];
								failureOccurred__pureZunittest_u74((*formatterX60gensym12___test95sigma95perf95frodo95profile_u368), checkpoints__pureZunittest_u45, stackTrace__test95sigma95perf95frodo95profile_u363);
								if (NIM_UNLIKELY(*nimErr_)) goto LA72_;
								i_4 += ((NI)1);
							} LA79: ;
						}
					}
					{
						if (!abortOnError__pureZunittest_u44) goto LA82_;
						quit__system_u8177(((NI)1));
					}
LA82_: ;
					T84_.len = 0; T84_.p = NIM_NIL;
					T84_.len = 0; T84_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
					eqsink___system_u3748((&checkpoints__pureZunittest_u45), T84_);
					{
						LA72_:;
					}
					{
						if (stackTrace__test95sigma95perf95frodo95profile_u363.p && !(stackTrace__test95sigma95perf95frodo95profile_u363.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(stackTrace__test95sigma95perf95frodo95profile_u363.p);
}
						if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
						if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
						if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
						if (eTypeDesc__test95sigma95perf95frodo95profile_u362.p && !(eTypeDesc__test95sigma95perf95frodo95profile_u362.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(eTypeDesc__test95sigma95perf95frodo95profile_u362.p);
}
						eqdestroy___stdZtypedthreads_u184(e__test95sigma95perf95frodo95profile_u361);
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA70_;
					popCurrentException();
					LA70_:;
				}
				else				{
					NimStringV2 colontmpD__9;
					NimStringV2 colontmpD__10;
					NimStringV2 T90_;
					tySequence__sM4lkSb7zS6F7OVMvW9cffQ T99_;
					*nimErr_ = NIM_FALSE;
					colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
					colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
					raiseDefect();
					T90_.len = 0; T90_.p = NIM_NIL;
					colontmpD__9 = getCurrentExceptionMsg__system_u8142();
					T90_ = rawNewString(colontmpD__9.len + 43);
appendString((&T90_), TM__jM27Cl58K9aw1WymP9a7uCbg_74);
appendString((&T90_), colontmpD__9);
appendString((&T90_), TM__jM27Cl58K9aw1WymP9a7uCbg_76);
					colontmpD__10 = T90_;
					checkpoint__pureZunittest_u1677(colontmpD__10);
					if (NIM_UNLIKELY(*nimErr_)) goto LA89_;
					testStatusIMPL__test95sigma95perf95frodo95profile_u296 = ((tyEnum_TestStatus__GZYsWtk2SzAvP8QZWAE89cg)1);
					ensureInitialized__pureZunittest_u1185();
					if (NIM_UNLIKELY(*nimErr_)) goto LA89_;
					{
						NI i_5;
						NI L_5;
						NI T92_;
						i_5 = ((NI)0);
						T92_ = formatters__pureZunittest_u46.len;
						L_5 = T92_;
						{
							while (1) {
								if (!(i_5 < L_5)) goto LA94;
								formatterX60gensym13___test95sigma95perf95frodo95profile_u377 = &formatters__pureZunittest_u46.p->data[i_5];
								failureOccurred__pureZunittest_u74((*formatterX60gensym13___test95sigma95perf95frodo95profile_u377), checkpoints__pureZunittest_u45, TM__jM27Cl58K9aw1WymP9a7uCbg_77);
								if (NIM_UNLIKELY(*nimErr_)) goto LA89_;
								i_5 += ((NI)1);
							} LA94: ;
						}
					}
					{
						if (!abortOnError__pureZunittest_u44) goto LA97_;
						quit__system_u8177(((NI)1));
					}
LA97_: ;
					T99_.len = 0; T99_.p = NIM_NIL;
					T99_.len = 0; T99_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
					eqsink___system_u3748((&checkpoints__pureZunittest_u45), T99_);
					{
						LA89_:;
					}
					{
						if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
						if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA87_;
					popCurrentException();
					LA87_:;
				}
			}
			{
				NimStringV2 colontmpD__11;
				tyEnum_TestStatus__GZYsWtk2SzAvP8QZWAE89cg colontmpD__12;
				tySequence__sM4lkSb7zS6F7OVMvW9cffQ T108_;
				oldNimErrFin18_ = *nimErr_; *nimErr_ = NIM_FALSE;
				colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
				colontmpD__12 = (tyEnum_TestStatus__GZYsWtk2SzAvP8QZWAE89cg)0;
				{
					if (!(testStatusIMPL__test95sigma95perf95frodo95profile_u296 == ((tyEnum_TestStatus__GZYsWtk2SzAvP8QZWAE89cg)1))) goto LA106_;
					setProgramResult__stdZexitprocs_u241(((NI)1));
					if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
				}
LA106_: ;
				colontmpD__11 = eqdup___system_u2664(testSuiteName__test95sigma95perf95frodo95profile_u287);
				testResult__test95sigma95perf95frodo95profile_u386.suiteName = colontmpD__11;
				testResult__test95sigma95perf95frodo95profile_u386.testName = TM__jM27Cl58K9aw1WymP9a7uCbg_78;
				colontmpD__12 = testStatusIMPL__test95sigma95perf95frodo95profile_u296;
				testResult__test95sigma95perf95frodo95profile_u386.status = colontmpD__12;
				testEnded__pureZunittest_u1658((&testResult__test95sigma95perf95frodo95profile_u386));
				if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
				T108_.len = 0; T108_.p = NIM_NIL;
				T108_.len = 0; T108_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
				eqsink___system_u3748((&checkpoints__pureZunittest_u45), T108_);
				{
					LA103_:;
				}
				{
					eqdestroy___test95sigma95perf95frodo95profile_u867((&testResult__test95sigma95perf95frodo95profile_u386));
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
				*nimErr_ = oldNimErrFin18_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
		}
LA11_: ;
		{
			LA3_:;
		}
		{
			oldNimErrFin3_ = *nimErr_; *nimErr_ = NIM_FALSE;
			suiteEnded__pureZunittest_u1618();
			if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
			*nimErr_ = oldNimErrFin3_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
		{
			LA2_:;
		}
		{
			if (testSuiteName__test95sigma95perf95frodo95profile_u287.p && !(testSuiteName__test95sigma95perf95frodo95profile_u287.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(testSuiteName__test95sigma95perf95frodo95profile_u287.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	eqdestroy___system_u3739(extraLibCandidates__OOZsrcZprotocolsZbindingsZliboqs_u223);
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

