/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -mavx2 -maes -msse2 -O3 -fno-ident -fno-math-errno   -IK:\Progz\nim-2.2.6\lib -IF:\CodingMain\Tyr-Crypto\tests -o F:\CodingMain\Tyr-Crypto\.nimcache\test_sigma_perf_frodo_profile_r2\@pprotocols@scustom_crypto@ssha3@ssha3.nim.c.o F:\CodingMain\Tyr-Crypto\.nimcache\test_sigma_perf_frodo_profile_r2\@pprotocols@scustom_crypto@ssha3@ssha3.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <x86intrin.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_EVP_MD__0MD0T8CQnxCXReL79cD6bTw tyObject_EVP_MD__0MD0T8CQnxCXReL79cD6bTw;
typedef struct tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef N_CDECL_PTR(tyObject_EVP_MD__0MD0T8CQnxCXReL79cD6bTw*, tyProc__PjL6SbbnlwLZUSmwCYfZpQ) (void);
typedef N_CDECL_PTR(tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw*, tyProc__driCK9aC9aJeFeKkHSx2SBcQ) (void);
typedef N_CDECL_PTR(void, tyProc__DezcYG8z7IngxGQ8QZmVHw) (tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw* ctx_p0);
typedef N_CDECL_PTR(int, tyProc__3MEgciwbuZY9b2W4fWg0fAQ) (tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw* ctx_p0, tyObject_EVP_MD__0MD0T8CQnxCXReL79cD6bTw* typ_p1, void* engine_p2);
typedef N_CDECL_PTR(int, tyProc__7MpYzSgnxBnf9bEAJScCqwQ) (tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw* ctx_p0, void* data_p1, size_t len_p2);
typedef N_CDECL_PTR(int, tyProc__w5saCo0KLzWLTh9c2KgipdQ) (tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw* ctx_p0, NU8* md_p1, size_t len_p2);
typedef NU64 tyArray__ti0bWuszecJ2jGEjnJGmWg[25];
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
typedef NimStringV2 tyArray__24KAM9afIUgUaqBaEBB6r9bg[3];
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef NimStringV2 tyArray__haiLFy0nBviVTKFGuwztzQ[5];
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw {
	char dummy;
};
typedef NU8 tyArray__k5CantrhGuvnhsRWsHF5HA[168];
typedef NU64 tyArray__13id4dQh19aNgtyEctXzOhA[24];
typedef NU8 tyArray__cdsir9aPB24hAk6k77P9b9bCA[8];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shake256OpenSslInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u270)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ensureOpenSslShakeLoaded__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u113)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, collectOpenSslCandidates__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u79)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u34)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitChar)(NimStringV2 s_p0, NIM_CHAR sep_p1, NI maxsplit_p2);
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringV2 path_p0, tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2658)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, absolutePath__stdZprivateZospaths2_u390)(NimStringV2 path_p0, NimStringV2 root_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPathOpenArray)(NimStringV2* parts_p0, NI parts_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetCurrentDir)(void);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2664)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2667)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8845)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(void, appendOpenSslCandidates__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u66)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* candidates_p0, NimStringV2 dirPath_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2661)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZosdirs_u85)(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3739)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u3)(NimStringV2 path_p0, NIM_BOOL globalSymbols_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u120)(NimStringV2 symName_p0, tyProc__PjL6SbbnlwLZUSmwCYfZpQ* target_p1);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_u74)(void* lib_p0, NCSTRING name_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, unloadOpenSslShake__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u106)(void);
N_LIB_PRIVATE N_NIMCALL(void, unloadLib__pureZdynlib_u7)(void* lib_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u145)(NimStringV2 symName_p0, tyProc__driCK9aC9aJeFeKkHSx2SBcQ* target_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u170)(NimStringV2 symName_p0, tyProc__DezcYG8z7IngxGQ8QZmVHw* target_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u195)(NimStringV2 symName_p0, tyProc__3MEgciwbuZY9b2W4fWg0fAQ* target_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u220)(NimStringV2 symName_p0, tyProc__7MpYzSgnxBnf9bEAJScCqwQ* target_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u245)(NimStringV2 symName_p0, tyProc__w5saCo0KLzWLTh9c2KgipdQ* target_p1);
static N_INLINE(void, shake256AbsorbOnce__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u1125)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0);
static N_INLINE(void, absorbFinalPartsWithDomain__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u787)(NU64* S_p0, NI rateBytes_p1, NU8 domain_p2, NU8* A_p3, NI A_p3Len_0);
static N_INLINE(void, absorbPartState__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u766)(NU64* S_p0, NU8* tail_p1, NI* tailLen_p2, NU8* A_p3, NI A_p3Len_0, NI rateBytes_p4);
static N_INLINE(void, absorbBlock__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u556)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0, NI o_p2, NI rateBytes_p3);
static N_INLINE(NU64, load64Le__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u492)(NU8* A_p0, NI A_p0Len_0, NI o_p1);
N_LIB_PRIVATE N_NIMCALL(void, keccakF1600Ref__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u613)(NU64* S_p0);
static N_INLINE(NU64, rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861)(NU64 value_p0, NI shift_p1);
static N_INLINE(int, shiftTypeTo__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u889)(NI shift_p1);
static N_INLINE(void, squeezeBytesInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u678)(tyArray__ti0bWuszecJ2jGEjnJGmWg S0_p0, NU8* dst_p1, NI dst_p1Len_0, NI rateBytes_p2);
static N_INLINE(void, squeezeBytesState__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u633)(NU64* S_p0, NU8* dst_p1, NI dst_p1Len_0, NI rateBytes_p2);
static N_INLINE(void, store64Le__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u524)(NU8* A_p0, NI A_p0Len_0, NI o_p1, NU64 v_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shake256OpenSslWordsLeInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u427)(NU16* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2632)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
static N_INLINE(void, absorbFinalBlockWithDomain__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u563)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0, NI o_p2, NI rateBytes_p3, NU8 domain_p4);
N_LIB_PRIVATE N_NIMCALL(void, squeezeWordsLeInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u702)(tyArray__ti0bWuszecJ2jGEjnJGmWg S0_p0, NU16* dst_p1, NI dst_p1Len_0, NI rateBytes_p2);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_3 = {0, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_2};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_4 = { 16 | NIM_STRLIT_FLAG, "OPENSSL_LIB_DIRS" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_5 = {16, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_4};
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_6 = {0, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_2};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__n2hmFo6ThUGbJBhyfD9ajFg_7 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_8 = { 4 | NIM_STRLIT_FLAG, "PATH" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_9 = {4, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_8};
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_10 = {0, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_2};
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_11 = {0, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_2};
static const struct {
  NI cap; NIM_CHAR data[66+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_12 = { 66 | NIM_STRLIT_FLAG, "F:\\CodingMain\\Tyr-Crypto\\src\\protocols\\custom_crypto\\sha3\\sha3.nim" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_13 = {66, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_12};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_14 = { 2 | NIM_STRLIT_FLAG, ".." };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_15 = {2, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_14};
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_16 = {2, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_14};
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_17 = {2, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_14};
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_18 = {2, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_14};
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_20 = { 32 | NIM_STRLIT_FLAG, "C:\\Program Files\\Git\\mingw64\\bin" };
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_21 = { 21 | NIM_STRLIT_FLAG, "C:\\msys64\\mingw64\\bin" };
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_22 = { 21 | NIM_STRLIT_FLAG, "C:\\msys64\\clang64\\bin" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_23 = {0, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_2};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_24 = { 19 | NIM_STRLIT_FLAG, "libcrypto-3-x64.dll" };
static const struct {
  NI cap; NimStringV2 data[1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_25 = {1 | NIM_STRLIT_FLAG, {{19, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_24}}};
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_26 = {0, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_2};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_27 = { 5 | NIM_STRLIT_FLAG, "build" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_28 = {5, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_27};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_29 = { 7 | NIM_STRLIT_FLAG, "openssl" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_30 = {7, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_29};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_31 = { 3 | NIM_STRLIT_FLAG, "lib" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_32 = {3, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_31};
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_33 = {5, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_27};
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_34 = {7, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_29};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_35 = { 7 | NIM_STRLIT_FLAG, "install" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_36 = {7, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_35};
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_37 = {3, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_31};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_38 = { 12 | NIM_STRLIT_FLAG, "EVP_shake256" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_39 = {12, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_38};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_40 = { 14 | NIM_STRLIT_FLAG, "EVP_MD_CTX_new" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_41 = {14, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_40};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_42 = { 15 | NIM_STRLIT_FLAG, "EVP_MD_CTX_free" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_43 = {15, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_42};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_44 = { 17 | NIM_STRLIT_FLAG, "EVP_DigestInit_ex" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_45 = {17, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_44};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_46 = { 16 | NIM_STRLIT_FLAG, "EVP_DigestUpdate" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_47 = {16, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_46};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__n2hmFo6ThUGbJBhyfD9ajFg_48 = { 18 | NIM_STRLIT_FLAG, "EVP_DigestFinalXOF" };
static const NimStringV2 TM__n2hmFo6ThUGbJBhyfD9ajFg_49 = {18, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_48};
static NIM_CONST tyArray__24KAM9afIUgUaqBaEBB6r9bg TM__n2hmFo6ThUGbJBhyfD9ajFg_19 = {{32, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_20},
{21, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_21},
{21, (NimStrPayload*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_22}}
;
N_LIB_PRIVATE NIM_CONST tySequence__sM4lkSb7zS6F7OVMvW9cffQ opensslShakeLibNames__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u24 = {1, (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*)&TM__n2hmFo6ThUGbJBhyfD9ajFg_25};
N_LIB_PRIVATE NIM_CONST tyArray__13id4dQh19aNgtyEctXzOhA keccakRoundConstants__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u25 = {1ULL,
32898ULL,
9223372036854808714ULL,
9223372039002292224ULL,
32907ULL,
2147483649ULL,
9223372039002292353ULL,
9223372036854808585ULL,
138ULL,
136ULL,
2147516425ULL,
2147483658ULL,
2147516555ULL,
9223372036854775947ULL,
9223372036854808713ULL,
9223372036854808579ULL,
9223372036854808578ULL,
9223372036854775936ULL,
32778ULL,
9223372039002259466ULL,
9223372039002292353ULL,
9223372036854808704ULL,
2147483649ULL,
9223372039002292232ULL}
;
N_LIB_PRIVATE void* opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57;
N_LIB_PRIVATE NIM_BOOL opensslShakeChecked__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u58 = NIM_FALSE;
N_LIB_PRIVATE NIM_BOOL opensslShakeReady__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u59 = NIM_FALSE;
N_LIB_PRIVATE tyProc__PjL6SbbnlwLZUSmwCYfZpQ osslShake256__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u60;
N_LIB_PRIVATE tyProc__driCK9aC9aJeFeKkHSx2SBcQ osslMdCtxNew__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u61;
N_LIB_PRIVATE tyProc__DezcYG8z7IngxGQ8QZmVHw osslMdCtxFree__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u62;
N_LIB_PRIVATE tyProc__3MEgciwbuZY9b2W4fWg0fAQ osslDigestInitEx__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u63;
N_LIB_PRIVATE tyProc__7MpYzSgnxBnf9bEAJScCqwQ osslDigestUpdate__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u64;
N_LIB_PRIVATE tyProc__w5saCo0KLzWLTh9c2KgipdQ osslDigestFinalXof__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u65;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4319;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4319);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, appendOpenSslCandidates__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u66)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* candidates_p0, NimStringV2 dirPath_p1) {
	NimStringV2 trimmed_1;
	NimStringV2 name_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	trimmed_1.len = 0; trimmed_1.p = NIM_NIL;
	name_1.len = 0; name_1.p = NIM_NIL;
	trimmed_1 = nsuStrip(dirPath_p1, NIM_TRUE, NIM_TRUE, TM__n2hmFo6ThUGbJBhyfD9ajFg_7);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	name_1 = TM__n2hmFo6ThUGbJBhyfD9ajFg_26;
	{
		if (!(trimmed_1.len == ((NI)0))) goto LA4_;
		if (trimmed_1.p && !(trimmed_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(trimmed_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	{
		NimStringV2* name_2;
		NI i_1;
		NI L_1;
		name_2 = (NimStringV2*)0;
		i_1 = ((NI)0);
		L_1 = ((NI)1);
		{
			while (1) {
				NimStringV2 T9_;
				if (!(i_1 < L_1)) goto LA8;
				name_2 = (&opensslShakeLibNames__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u24.p->data[i_1]);
				T9_.len = 0; T9_.p = NIM_NIL;
				T9_ = nosjoinPath(trimmed_1, (*name_2));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T9_); goto LA1_;}
				add__stdZenumutils_u70((&(*candidates_p0)), T9_);
				i_1 += ((NI)1);
			} LA8: ;
		}
	}
	{
		LA1_:;
	}
	{
		if (trimmed_1.p && !(trimmed_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(trimmed_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, collectOpenSslCandidates__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u79)(void) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
	NimStringV2 envDirs_1;
	NimStringV2 colontmpD_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ pathDirs_1;
	NimStringV2 colontmpD__2;
	NimStringV2 dirPath_1;
	NimStringV2 moduleDir_1;
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg colontmpD__3;
	NimStringV2 repoRoot_1;
	NimStringV2 colontmpD__4;
	NimStringV2 colontmpD__5;
	tyArray__24KAM9afIUgUaqBaEBB6r9bg commonWindowsDirs_1;
	NimStringV2 name_1;
	NimStringV2 colontmpD__6;
	NimStringV2 colontmpD__7;
	tyArray__haiLFy0nBviVTKFGuwztzQ T2_;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ T29_;
	tyArray__haiLFy0nBviVTKFGuwztzQ T30_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	envDirs_1.len = 0; envDirs_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	pathDirs_1.len = 0; pathDirs_1.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	dirPath_1.len = 0; dirPath_1.p = NIM_NIL;
	moduleDir_1.len = 0; moduleDir_1.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__3), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	repoRoot_1.len = 0; repoRoot_1.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
	nimZeroMem((void*)commonWindowsDirs_1, sizeof(tyArray__24KAM9afIUgUaqBaEBB6r9bg));
	name_1.len = 0; name_1.p = NIM_NIL;
	colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
	colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
	colontmpD_ = getEnv__stdZenvvars_u34(TM__n2hmFo6ThUGbJBhyfD9ajFg_5, TM__n2hmFo6ThUGbJBhyfD9ajFg_6);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	envDirs_1 = nsuStrip(colontmpD_, NIM_TRUE, NIM_TRUE, TM__n2hmFo6ThUGbJBhyfD9ajFg_7);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = getEnv__stdZenvvars_u34(TM__n2hmFo6ThUGbJBhyfD9ajFg_9, TM__n2hmFo6ThUGbJBhyfD9ajFg_10);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	pathDirs_1 = nsuSplitChar(colontmpD__2, 59, ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	dirPath_1 = TM__n2hmFo6ThUGbJBhyfD9ajFg_11;
	nossplitFile(TM__n2hmFo6ThUGbJBhyfD9ajFg_13, (&colontmpD__3));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	moduleDir_1 = colontmpD__3.Field0;
	eqwasMoved___system_u2658((&colontmpD__3.Field0));
	T2_[0] = moduleDir_1;
	T2_[1] = TM__n2hmFo6ThUGbJBhyfD9ajFg_15;
	T2_[2] = TM__n2hmFo6ThUGbJBhyfD9ajFg_16;
	T2_[3] = TM__n2hmFo6ThUGbJBhyfD9ajFg_17;
	T2_[4] = TM__n2hmFo6ThUGbJBhyfD9ajFg_18;
	colontmpD__4 = nosjoinPathOpenArray(T2_, 5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__5 = nosgetCurrentDir();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	repoRoot_1 = absolutePath__stdZprivateZospaths2_u390(colontmpD__4, colontmpD__5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimCopyMem((void*)commonWindowsDirs_1, (NIM_CONST void*)TM__n2hmFo6ThUGbJBhyfD9ajFg_19, sizeof(tyArray__24KAM9afIUgUaqBaEBB6r9bg));
	name_1 = TM__n2hmFo6ThUGbJBhyfD9ajFg_23;
	{
		NimStringV2* name_2;
		NI i_1;
		NI L_1;
		name_2 = (NimStringV2*)0;
		i_1 = ((NI)0);
		L_1 = ((NI)1);
		{
			while (1) {
				NimStringV2 colontmpD__8;
				if (!(i_1 < L_1)) goto LA5;
				colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
				name_2 = (&opensslShakeLibNames__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u24.p->data[i_1]);
				colontmpD__8 = eqdup___system_u2664((*name_2));
				add__stdZenumutils_u70((&result), colontmpD__8);
				i_1 += ((NI)1);
			} LA5: ;
		}
	}
	{
		if (!(((NI)0) < envDirs_1.len)) goto LA8_;
		{
			NimStringV2 dirPath_2;
			NI lastX60gensym37__1;
			NI splitsX60gensym37__1;
			dirPath_2.len = 0; dirPath_2.p = NIM_NIL;
			lastX60gensym37__1 = ((NI)0);
			splitsX60gensym37__1 = ((NI)-1);
			{
				while (1) {
					NI firstX60gensym37__1;
					NimStringV2 T22_;
					if (!(lastX60gensym37__1 <= envDirs_1.len)) goto LA13;
					firstX60gensym37__1 = lastX60gensym37__1;
					{
						while (1) {
							NIM_BOOL T16_;
							T16_ = (NIM_BOOL)0;
							T16_ = (lastX60gensym37__1 < envDirs_1.len);
							if (!(T16_)) goto LA17_;
							T16_ = !((((NU8)(envDirs_1.p->data[lastX60gensym37__1])) == ((NU8)(59)) || ((NU8)(envDirs_1.p->data[lastX60gensym37__1])) == ((NU8)(58))));
LA17_: ;
							if (!T16_) goto LA15;
							lastX60gensym37__1 += ((NI)1);
						} LA15: ;
					}
					{
						if (!(splitsX60gensym37__1 == ((NI)0))) goto LA20_;
						lastX60gensym37__1 = envDirs_1.len;
					}
LA20_: ;
					T22_.len = 0; T22_.p = NIM_NIL;
					T22_ = substr__system_u8845(envDirs_1, firstX60gensym37__1, (NI)(lastX60gensym37__1 - ((NI)1)));
					eqsink___system_u2667((&dirPath_2), T22_);
					appendOpenSslCandidates__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u66((&result), dirPath_2);
					if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
					{
						if (!(splitsX60gensym37__1 == ((NI)0))) goto LA25_;
						goto LA12;
					}
LA25_: ;
					splitsX60gensym37__1 -= ((NI)1);
					lastX60gensym37__1 += ((NI)1);
				} LA13: ;
			} LA12: ;
			{
				LA11_:;
			}
			{
				if (dirPath_2.p && !(dirPath_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dirPath_2.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
	}
LA8_: ;
	T29_[0] = repoRoot_1;
	T29_[1] = TM__n2hmFo6ThUGbJBhyfD9ajFg_28;
	T29_[2] = TM__n2hmFo6ThUGbJBhyfD9ajFg_30;
	T29_[3] = TM__n2hmFo6ThUGbJBhyfD9ajFg_32;
	colontmpD__6 = nosjoinPathOpenArray(T29_, 4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	appendOpenSslCandidates__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u66((&result), colontmpD__6);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T30_[0] = repoRoot_1;
	T30_[1] = TM__n2hmFo6ThUGbJBhyfD9ajFg_33;
	T30_[2] = TM__n2hmFo6ThUGbJBhyfD9ajFg_34;
	T30_[3] = TM__n2hmFo6ThUGbJBhyfD9ajFg_36;
	T30_[4] = TM__n2hmFo6ThUGbJBhyfD9ajFg_37;
	colontmpD__7 = nosjoinPathOpenArray(T30_, 5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	appendOpenSslCandidates__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u66((&result), colontmpD__7);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2* dirPath_3;
		NI i_2;
		NI L_2;
		NI T32_;
		dirPath_3 = (NimStringV2*)0;
		i_2 = ((NI)0);
		T32_ = pathDirs_1.len;
		L_2 = T32_;
		{
			while (1) {
				if (!(i_2 < L_2)) goto LA34;
				dirPath_3 = (&pathDirs_1.p->data[i_2]);
				appendOpenSslCandidates__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u66((&result), (*dirPath_3));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				i_2 += ((NI)1);
			} LA34: ;
		}
	}
	{
		NimStringV2 dirPath_4;
		NI i_3;
		dirPath_4.len = 0; dirPath_4.p = NIM_NIL;
		i_3 = ((NI)0);
		{
			while (1) {
				eqcopy___system_u2661((&dirPath_4), commonWindowsDirs_1[(i_3)- 0]);
				appendOpenSslCandidates__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u66((&result), dirPath_4);
				if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
				{
					if (!(((NI)2) <= i_3)) goto LA41_;
					goto LA37;
				}
LA41_: ;
				i_3 += ((NI)1);
			}
		} LA37: ;
		{
			LA36_:;
		}
		{
			if (dirPath_4.p && !(dirPath_4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dirPath_4.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	{
		LA1_:;
	}
	{
		if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (repoRoot_1.p && !(repoRoot_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(repoRoot_1.p);
}
		eqdestroy___stdZprivateZosdirs_u85((&colontmpD__3));
		if (moduleDir_1.p && !(moduleDir_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(moduleDir_1.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		eqdestroy___system_u3739(pathDirs_1);
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (envDirs_1.p && !(envDirs_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(envDirs_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, unloadOpenSslShake__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u106)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!((opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57 == NIM_NIL))) goto LA3_;
		unloadLib__pureZdynlib_u7(opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57 = NIM_NIL;
	}
LA3_: ;
	opensslShakeReady__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u59 = NIM_FALSE;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u120)(NimStringV2 symName_p0, tyProc__PjL6SbbnlwLZUSmwCYfZpQ* target_p1) {
	NIM_BOOL result;
	void* addrSym_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	addrSym_1 = symAddr__pureZdynlib_u74(opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57, nimToCStringConv(symName_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(addrSym_1 == 0)) goto LA3_;
		unloadOpenSslShake__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u106();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	(*target_p1) = ((tyProc__PjL6SbbnlwLZUSmwCYfZpQ) (addrSym_1));
	result = NIM_TRUE;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u145)(NimStringV2 symName_p0, tyProc__driCK9aC9aJeFeKkHSx2SBcQ* target_p1) {
	NIM_BOOL result;
	void* addrSym_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	addrSym_1 = symAddr__pureZdynlib_u74(opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57, nimToCStringConv(symName_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(addrSym_1 == 0)) goto LA3_;
		unloadOpenSslShake__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u106();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	(*target_p1) = ((tyProc__driCK9aC9aJeFeKkHSx2SBcQ) (addrSym_1));
	result = NIM_TRUE;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u170)(NimStringV2 symName_p0, tyProc__DezcYG8z7IngxGQ8QZmVHw* target_p1) {
	NIM_BOOL result;
	void* addrSym_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	addrSym_1 = symAddr__pureZdynlib_u74(opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57, nimToCStringConv(symName_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(addrSym_1 == 0)) goto LA3_;
		unloadOpenSslShake__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u106();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	(*target_p1) = ((tyProc__DezcYG8z7IngxGQ8QZmVHw) (addrSym_1));
	result = NIM_TRUE;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u195)(NimStringV2 symName_p0, tyProc__3MEgciwbuZY9b2W4fWg0fAQ* target_p1) {
	NIM_BOOL result;
	void* addrSym_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	addrSym_1 = symAddr__pureZdynlib_u74(opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57, nimToCStringConv(symName_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(addrSym_1 == 0)) goto LA3_;
		unloadOpenSslShake__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u106();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	(*target_p1) = ((tyProc__3MEgciwbuZY9b2W4fWg0fAQ) (addrSym_1));
	result = NIM_TRUE;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u220)(NimStringV2 symName_p0, tyProc__7MpYzSgnxBnf9bEAJScCqwQ* target_p1) {
	NIM_BOOL result;
	void* addrSym_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	addrSym_1 = symAddr__pureZdynlib_u74(opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57, nimToCStringConv(symName_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(addrSym_1 == 0)) goto LA3_;
		unloadOpenSslShake__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u106();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	(*target_p1) = ((tyProc__7MpYzSgnxBnf9bEAJScCqwQ) (addrSym_1));
	result = NIM_TRUE;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u245)(NimStringV2 symName_p0, tyProc__w5saCo0KLzWLTh9c2KgipdQ* target_p1) {
	NIM_BOOL result;
	void* addrSym_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	addrSym_1 = symAddr__pureZdynlib_u74(opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57, nimToCStringConv(symName_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(addrSym_1 == 0)) goto LA3_;
		unloadOpenSslShake__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u106();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	(*target_p1) = ((tyProc__w5saCo0KLzWLTh9c2KgipdQ) (addrSym_1));
	result = NIM_TRUE;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ensureOpenSslShakeLoaded__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u113)(void) {
	NIM_BOOL result;
	NimStringV2 candidate_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	candidate_1.len = 0; candidate_1.p = NIM_NIL;
	candidate_1 = TM__n2hmFo6ThUGbJBhyfD9ajFg_3;
	{
		if (!opensslShakeChecked__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u58) goto LA3_;
		result = opensslShakeReady__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u59;
		goto BeforeRet_;
	}
LA3_: ;
	opensslShakeChecked__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u58 = NIM_TRUE;
	{
		tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmp_;
		NimStringV2* candidate_2;
		NI i_1;
		NI L_1;
		NI T7_;
		colontmp_.len = 0; colontmp_.p = NIM_NIL;
		candidate_2 = (NimStringV2*)0;
		colontmp_ = collectOpenSslCandidates__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u79();
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		i_1 = ((NI)0);
		T7_ = colontmp_.len;
		L_1 = T7_;
		{
			while (1) {
				void* T10_;
				if (!(i_1 < L_1)) goto LA9;
				candidate_2 = (&colontmp_.p->data[i_1]);
				T10_ = (void*)0;
				T10_ = loadLib__pureZdynlib_u3((*candidate_2), NIM_FALSE);
				if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
				opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57 = T10_;
				{
					if (!!((opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57 == NIM_NIL))) goto LA13_;
					eqdestroy___system_u3739(colontmp_);
					goto LA5;
				}
LA13_: ;
				i_1 += ((NI)1);
			} LA9: ;
		}
		{
			LA6_:;
		}
		{
			eqdestroy___system_u3739(colontmp_);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	} LA5: ;
	{
		if (!(opensslShakeHandle__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u57 == NIM_NIL)) goto LA19_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA19_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u120(TM__n2hmFo6ThUGbJBhyfD9ajFg_39, (&osslShake256__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u60));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T23_)) goto LA24_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA24_: ;
	{
		NIM_BOOL T28_;
		T28_ = (NIM_BOOL)0;
		T28_ = loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u145(TM__n2hmFo6ThUGbJBhyfD9ajFg_41, (&osslMdCtxNew__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u61));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T28_)) goto LA29_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA29_: ;
	{
		NIM_BOOL T33_;
		T33_ = (NIM_BOOL)0;
		T33_ = loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u170(TM__n2hmFo6ThUGbJBhyfD9ajFg_43, (&osslMdCtxFree__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u62));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T33_)) goto LA34_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA34_: ;
	{
		NIM_BOOL T38_;
		T38_ = (NIM_BOOL)0;
		T38_ = loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u195(TM__n2hmFo6ThUGbJBhyfD9ajFg_45, (&osslDigestInitEx__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u63));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T38_)) goto LA39_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA39_: ;
	{
		NIM_BOOL T43_;
		T43_ = (NIM_BOOL)0;
		T43_ = loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u220(TM__n2hmFo6ThUGbJBhyfD9ajFg_47, (&osslDigestUpdate__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T43_)) goto LA44_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA44_: ;
	{
		NIM_BOOL T48_;
		T48_ = (NIM_BOOL)0;
		T48_ = loadOpenSslSymbol__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u245(TM__n2hmFo6ThUGbJBhyfD9ajFg_49, (&osslDigestFinalXof__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u65));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T48_)) goto LA49_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA49_: ;
	opensslShakeReady__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u59 = NIM_TRUE;
	result = NIM_TRUE;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shake256OpenSslInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u270)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
	NIM_BOOL result;
	tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw* ctx_1;
NIM_BOOL oldNimErrFin10_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	ctx_1 = (tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw*)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ensureOpenSslShakeLoaded__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u113();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA4_: ;
	ctx_1 = osslMdCtxNew__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u61();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(ctx_1 == ((tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw*) NIM_NIL))) goto LA8_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA8_: ;
	{
		tyObject_EVP_MD__0MD0T8CQnxCXReL79cD6bTw* T13_;
		int T14_;
		T13_ = (tyObject_EVP_MD__0MD0T8CQnxCXReL79cD6bTw*)0;
		T13_ = osslShake256__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u60();
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		T14_ = (int)0;
		T14_ = osslDigestInitEx__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u63(ctx_1, T13_, NIM_NIL);
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		if (!!((T14_ == ((NI32)1)))) goto LA15_;
		result = NIM_FALSE;
		osslMdCtxFree__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u62(ctx_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA15_: ;
	{
		NIM_BOOL T19_;
		int T21_;
		T19_ = (NIM_BOOL)0;
		T19_ = (((NI)0) < A_p1Len_0);
		if (!(T19_)) goto LA20_;
		T21_ = (int)0;
		T21_ = osslDigestUpdate__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u64(ctx_1, ((void*) ((&A_p1[((NI)0)]))), ((size_t) (A_p1Len_0)));
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		T19_ = !((T21_ == ((NI32)1)));
LA20_: ;
		if (!T19_) goto LA22_;
		result = NIM_FALSE;
		osslMdCtxFree__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u62(ctx_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA22_: ;
	{
		NIM_BOOL T26_;
		int T28_;
		T26_ = (NIM_BOOL)0;
		T26_ = (((NI)0) < dst_p0Len_0);
		if (!(T26_)) goto LA27_;
		T28_ = (int)0;
		T28_ = osslDigestFinalXof__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u65(ctx_1, (&dst_p0[((NI)0)]), ((size_t) (dst_p0Len_0)));
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		T26_ = !((T28_ == ((NI32)1)));
LA27_: ;
		if (!T26_) goto LA29_;
		result = NIM_FALSE;
		osslMdCtxFree__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u62(ctx_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA29_: ;
	result = NIM_TRUE;
	{
		LA10_:;
	}
	{
		oldNimErrFin10_ = *nimErr_; *nimErr_ = NIM_FALSE;
		osslMdCtxFree__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u62(ctx_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin10_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU64, load64Le__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u492)(NU8* A_p0, NI A_p0Len_0, NI o_p1) {
	NU64 result;
	result = (NU64)((NU64)((NU64)((NU64)((NU64)((NU64)((NU64)(((NU64) (A_p0[o_p1])) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)1))]))) << (NU64)(((NI)8)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)2))]))) << (NU64)(((NI)16)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)3))]))) << (NU64)(((NI)24)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)4))]))) << (NU64)(((NI)32)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)5))]))) << (NU64)(((NI)40)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)6))]))) << (NU64)(((NI)48)))) | (NU64)((NU64)(((NU64) (A_p0[(NI)(o_p1 + ((NI)7))]))) << (NU64)(((NI)56))));
	return result;
}
static N_INLINE(void, absorbBlock__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u556)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0, NI o_p2, NI rateBytes_p3) {
	NI lane_1;
	NI laneCount_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	lane_1 = ((NI)0);
	laneCount_1 = ((NI)0);
	laneCount_1 = (NI)(rateBytes_p3 / ((NI)8));
	lane_1 = ((NI)0);
	{
		while (1) {
			NU64 T3_;
			if (!(lane_1 < laneCount_1)) goto LA2;
			T3_ = (NU64)0;
			T3_ = load64Le__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u492(A_p1, A_p1Len_0, (NI)(o_p2 + (NI)(lane_1 * ((NI)8))));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			S_p0[(lane_1)- 0] = (NU64)(S_p0[(lane_1)- 0] ^ T3_);
			lane_1 = (NI)(lane_1 + ((NI)1));
		} LA2: ;
	}
	}BeforeRet_: ;
}
static N_INLINE(int, shiftTypeTo__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u889)(NI shift_p1) {
	int result;
	result = (int)0;
	result = ((int) (shift_p1));
	return result;
}
static N_INLINE(NU64, rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861)(NU64 value_p0, NI shift_p1) {
	NU64 result;
	int T1_;
	unsigned long long T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU64)0;
	T1_ = (int)0;
	T1_ = shiftTypeTo__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u889(shift_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (unsigned long long)0;
	T2_ = __rolq(((unsigned long long) (value_p0)), T1_);
	result = ((NU64) (T2_));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, keccakF1600Ref__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u613)(NU64* S_p0) {
	NU64 c0_1;
	NU64 c1_1;
	NU64 c2_1;
	NU64 c3_1;
	NU64 c4_1;
	NU64 d0_1;
	NU64 d1_1;
	NU64 d2_1;
	NU64 d3_1;
	NU64 d4_1;
	NU64 b0_1;
	NU64 b1_1;
	NU64 b2_1;
	NU64 b3_1;
	NU64 b4_1;
	NU64 b5_1;
	NU64 b6_1;
	NU64 b7_1;
	NU64 b8_1;
	NU64 b9_1;
	NU64 b10_1;
	NU64 b11_1;
	NU64 b12_1;
	NU64 b13_1;
	NU64 b14_1;
	NU64 b15_1;
	NU64 b16_1;
	NU64 b17_1;
	NU64 b18_1;
	NU64 b19_1;
	NU64 b20_1;
	NU64 b21_1;
	NU64 b22_1;
	NU64 b23_1;
	NU64 b24_1;
	NI round_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	c0_1 = 0ULL;
	c1_1 = 0ULL;
	c2_1 = 0ULL;
	c3_1 = 0ULL;
	c4_1 = 0ULL;
	d0_1 = 0ULL;
	d1_1 = 0ULL;
	d2_1 = 0ULL;
	d3_1 = 0ULL;
	d4_1 = 0ULL;
	b0_1 = 0ULL;
	b1_1 = 0ULL;
	b2_1 = 0ULL;
	b3_1 = 0ULL;
	b4_1 = 0ULL;
	b5_1 = 0ULL;
	b6_1 = 0ULL;
	b7_1 = 0ULL;
	b8_1 = 0ULL;
	b9_1 = 0ULL;
	b10_1 = 0ULL;
	b11_1 = 0ULL;
	b12_1 = 0ULL;
	b13_1 = 0ULL;
	b14_1 = 0ULL;
	b15_1 = 0ULL;
	b16_1 = 0ULL;
	b17_1 = 0ULL;
	b18_1 = 0ULL;
	b19_1 = 0ULL;
	b20_1 = 0ULL;
	b21_1 = 0ULL;
	b22_1 = 0ULL;
	b23_1 = 0ULL;
	b24_1 = 0ULL;
	round_1 = ((NI)0);
	round_1 = ((NI)0);
	{
		while (1) {
			NU64 T3_;
			NU64 T4_;
			NU64 T5_;
			NU64 T6_;
			NU64 T7_;
			if (!(round_1 < ((NI)24))) goto LA2;
			c0_1 = (NU64)((NU64)((NU64)((NU64)(S_p0[(((NI)0))- 0] ^ S_p0[(((NI)5))- 0]) ^ S_p0[(((NI)10))- 0]) ^ S_p0[(((NI)15))- 0]) ^ S_p0[(((NI)20))- 0]);
			c1_1 = (NU64)((NU64)((NU64)((NU64)(S_p0[(((NI)1))- 0] ^ S_p0[(((NI)6))- 0]) ^ S_p0[(((NI)11))- 0]) ^ S_p0[(((NI)16))- 0]) ^ S_p0[(((NI)21))- 0]);
			c2_1 = (NU64)((NU64)((NU64)((NU64)(S_p0[(((NI)2))- 0] ^ S_p0[(((NI)7))- 0]) ^ S_p0[(((NI)12))- 0]) ^ S_p0[(((NI)17))- 0]) ^ S_p0[(((NI)22))- 0]);
			c3_1 = (NU64)((NU64)((NU64)((NU64)(S_p0[(((NI)3))- 0] ^ S_p0[(((NI)8))- 0]) ^ S_p0[(((NI)13))- 0]) ^ S_p0[(((NI)18))- 0]) ^ S_p0[(((NI)23))- 0]);
			c4_1 = (NU64)((NU64)((NU64)((NU64)(S_p0[(((NI)4))- 0] ^ S_p0[(((NI)9))- 0]) ^ S_p0[(((NI)14))- 0]) ^ S_p0[(((NI)19))- 0]) ^ S_p0[(((NI)24))- 0]);
			T3_ = (NU64)0;
			T3_ = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(c1_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			d0_1 = (NU64)(c4_1 ^ T3_);
			T4_ = (NU64)0;
			T4_ = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(c2_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			d1_1 = (NU64)(c0_1 ^ T4_);
			T5_ = (NU64)0;
			T5_ = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(c3_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			d2_1 = (NU64)(c1_1 ^ T5_);
			T6_ = (NU64)0;
			T6_ = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(c4_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			d3_1 = (NU64)(c2_1 ^ T6_);
			T7_ = (NU64)0;
			T7_ = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(c0_1, ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			d4_1 = (NU64)(c3_1 ^ T7_);
			S_p0[(((NI)0))- 0] = (NU64)(S_p0[(((NI)0))- 0] ^ d0_1);
			S_p0[(((NI)5))- 0] = (NU64)(S_p0[(((NI)5))- 0] ^ d0_1);
			S_p0[(((NI)10))- 0] = (NU64)(S_p0[(((NI)10))- 0] ^ d0_1);
			S_p0[(((NI)15))- 0] = (NU64)(S_p0[(((NI)15))- 0] ^ d0_1);
			S_p0[(((NI)20))- 0] = (NU64)(S_p0[(((NI)20))- 0] ^ d0_1);
			S_p0[(((NI)1))- 0] = (NU64)(S_p0[(((NI)1))- 0] ^ d1_1);
			S_p0[(((NI)6))- 0] = (NU64)(S_p0[(((NI)6))- 0] ^ d1_1);
			S_p0[(((NI)11))- 0] = (NU64)(S_p0[(((NI)11))- 0] ^ d1_1);
			S_p0[(((NI)16))- 0] = (NU64)(S_p0[(((NI)16))- 0] ^ d1_1);
			S_p0[(((NI)21))- 0] = (NU64)(S_p0[(((NI)21))- 0] ^ d1_1);
			S_p0[(((NI)2))- 0] = (NU64)(S_p0[(((NI)2))- 0] ^ d2_1);
			S_p0[(((NI)7))- 0] = (NU64)(S_p0[(((NI)7))- 0] ^ d2_1);
			S_p0[(((NI)12))- 0] = (NU64)(S_p0[(((NI)12))- 0] ^ d2_1);
			S_p0[(((NI)17))- 0] = (NU64)(S_p0[(((NI)17))- 0] ^ d2_1);
			S_p0[(((NI)22))- 0] = (NU64)(S_p0[(((NI)22))- 0] ^ d2_1);
			S_p0[(((NI)3))- 0] = (NU64)(S_p0[(((NI)3))- 0] ^ d3_1);
			S_p0[(((NI)8))- 0] = (NU64)(S_p0[(((NI)8))- 0] ^ d3_1);
			S_p0[(((NI)13))- 0] = (NU64)(S_p0[(((NI)13))- 0] ^ d3_1);
			S_p0[(((NI)18))- 0] = (NU64)(S_p0[(((NI)18))- 0] ^ d3_1);
			S_p0[(((NI)23))- 0] = (NU64)(S_p0[(((NI)23))- 0] ^ d3_1);
			S_p0[(((NI)4))- 0] = (NU64)(S_p0[(((NI)4))- 0] ^ d4_1);
			S_p0[(((NI)9))- 0] = (NU64)(S_p0[(((NI)9))- 0] ^ d4_1);
			S_p0[(((NI)14))- 0] = (NU64)(S_p0[(((NI)14))- 0] ^ d4_1);
			S_p0[(((NI)19))- 0] = (NU64)(S_p0[(((NI)19))- 0] ^ d4_1);
			S_p0[(((NI)24))- 0] = (NU64)(S_p0[(((NI)24))- 0] ^ d4_1);
			b0_1 = S_p0[(((NI)0))- 0];
			b10_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)1))- 0], ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b20_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)2))- 0], ((NI)62));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b5_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)3))- 0], ((NI)28));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b15_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)4))- 0], ((NI)27));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b16_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)5))- 0], ((NI)36));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b1_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)6))- 0], ((NI)44));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b11_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)7))- 0], ((NI)6));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b21_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)8))- 0], ((NI)55));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b6_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)9))- 0], ((NI)20));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b7_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)10))- 0], ((NI)3));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b17_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)11))- 0], ((NI)10));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b2_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)12))- 0], ((NI)43));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b12_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)13))- 0], ((NI)25));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b22_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)14))- 0], ((NI)39));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b23_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)15))- 0], ((NI)41));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b8_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)16))- 0], ((NI)45));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b18_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)17))- 0], ((NI)15));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b3_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)18))- 0], ((NI)21));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b13_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)19))- 0], ((NI)8));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b14_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)20))- 0], ((NI)18));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b24_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)21))- 0], ((NI)2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b9_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)22))- 0], ((NI)61));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b19_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)23))- 0], ((NI)56));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			b4_1 = rotateLeftBits__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u861(S_p0[(((NI)24))- 0], ((NI)14));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			S_p0[(((NI)0))- 0] = (NU64)(b0_1 ^ (NU64)((NU64)((NU64) ~(b1_1)) & b2_1));
			S_p0[(((NI)1))- 0] = (NU64)(b1_1 ^ (NU64)((NU64)((NU64) ~(b2_1)) & b3_1));
			S_p0[(((NI)2))- 0] = (NU64)(b2_1 ^ (NU64)((NU64)((NU64) ~(b3_1)) & b4_1));
			S_p0[(((NI)3))- 0] = (NU64)(b3_1 ^ (NU64)((NU64)((NU64) ~(b4_1)) & b0_1));
			S_p0[(((NI)4))- 0] = (NU64)(b4_1 ^ (NU64)((NU64)((NU64) ~(b0_1)) & b1_1));
			S_p0[(((NI)5))- 0] = (NU64)(b5_1 ^ (NU64)((NU64)((NU64) ~(b6_1)) & b7_1));
			S_p0[(((NI)6))- 0] = (NU64)(b6_1 ^ (NU64)((NU64)((NU64) ~(b7_1)) & b8_1));
			S_p0[(((NI)7))- 0] = (NU64)(b7_1 ^ (NU64)((NU64)((NU64) ~(b8_1)) & b9_1));
			S_p0[(((NI)8))- 0] = (NU64)(b8_1 ^ (NU64)((NU64)((NU64) ~(b9_1)) & b5_1));
			S_p0[(((NI)9))- 0] = (NU64)(b9_1 ^ (NU64)((NU64)((NU64) ~(b5_1)) & b6_1));
			S_p0[(((NI)10))- 0] = (NU64)(b10_1 ^ (NU64)((NU64)((NU64) ~(b11_1)) & b12_1));
			S_p0[(((NI)11))- 0] = (NU64)(b11_1 ^ (NU64)((NU64)((NU64) ~(b12_1)) & b13_1));
			S_p0[(((NI)12))- 0] = (NU64)(b12_1 ^ (NU64)((NU64)((NU64) ~(b13_1)) & b14_1));
			S_p0[(((NI)13))- 0] = (NU64)(b13_1 ^ (NU64)((NU64)((NU64) ~(b14_1)) & b10_1));
			S_p0[(((NI)14))- 0] = (NU64)(b14_1 ^ (NU64)((NU64)((NU64) ~(b10_1)) & b11_1));
			S_p0[(((NI)15))- 0] = (NU64)(b15_1 ^ (NU64)((NU64)((NU64) ~(b16_1)) & b17_1));
			S_p0[(((NI)16))- 0] = (NU64)(b16_1 ^ (NU64)((NU64)((NU64) ~(b17_1)) & b18_1));
			S_p0[(((NI)17))- 0] = (NU64)(b17_1 ^ (NU64)((NU64)((NU64) ~(b18_1)) & b19_1));
			S_p0[(((NI)18))- 0] = (NU64)(b18_1 ^ (NU64)((NU64)((NU64) ~(b19_1)) & b15_1));
			S_p0[(((NI)19))- 0] = (NU64)(b19_1 ^ (NU64)((NU64)((NU64) ~(b15_1)) & b16_1));
			S_p0[(((NI)20))- 0] = (NU64)(b20_1 ^ (NU64)((NU64)((NU64) ~(b21_1)) & b22_1));
			S_p0[(((NI)21))- 0] = (NU64)(b21_1 ^ (NU64)((NU64)((NU64) ~(b22_1)) & b23_1));
			S_p0[(((NI)22))- 0] = (NU64)(b22_1 ^ (NU64)((NU64)((NU64) ~(b23_1)) & b24_1));
			S_p0[(((NI)23))- 0] = (NU64)(b23_1 ^ (NU64)((NU64)((NU64) ~(b24_1)) & b20_1));
			S_p0[(((NI)24))- 0] = (NU64)(b24_1 ^ (NU64)((NU64)((NU64) ~(b20_1)) & b21_1));
			S_p0[(((NI)0))- 0] = (NU64)(S_p0[(((NI)0))- 0] ^ keccakRoundConstants__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u25[(round_1)- 0]);
			round_1 = (NI)(round_1 + ((NI)1));
		} LA2: ;
	}
	}BeforeRet_: ;
}
static N_INLINE(void, absorbPartState__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u766)(NU64* S_p0, NU8* tail_p1, NI* tailLen_p2, NU8* A_p3, NI A_p3Len_0, NI rateBytes_p4) {
	NI offset_1;
	NI take_1;
	NI i_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	offset_1 = ((NI)0);
	take_1 = ((NI)0);
	i_1 = ((NI)0);
	{
		if (!(((NI)0) < (*tailLen_p2))) goto LA3_;
		take_1 = (NI)(rateBytes_p4 - (*tailLen_p2));
		{
			if (!(A_p3Len_0 < take_1)) goto LA7_;
			take_1 = A_p3Len_0;
		}
LA7_: ;
		i_1 = ((NI)0);
		{
			while (1) {
				if (!(i_1 < take_1)) goto LA10;
				tail_p1[((NI)((*tailLen_p2) + i_1))- 0] = A_p3[i_1];
				i_1 = (NI)(i_1 + ((NI)1));
			} LA10: ;
		}
		(*tailLen_p2) = (NI)((*tailLen_p2) + take_1);
		offset_1 = take_1;
		{
			if (!((*tailLen_p2) == rateBytes_p4)) goto LA13_;
			absorbBlock__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u556(S_p0, tail_p1, 168, ((NI)0), rateBytes_p4);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			keccakF1600Ref__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u613(S_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			(*tailLen_p2) = ((NI)0);
		}
LA13_: ;
	}
LA3_: ;
	{
		while (1) {
			if (!((NI)(offset_1 + rateBytes_p4) <= A_p3Len_0)) goto LA16;
			absorbBlock__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u556(S_p0, A_p3, A_p3Len_0, offset_1, rateBytes_p4);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			keccakF1600Ref__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u613(S_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			offset_1 = (NI)(offset_1 + rateBytes_p4);
		} LA16: ;
	}
	{
		while (1) {
			if (!(offset_1 < A_p3Len_0)) goto LA18;
			tail_p1[((*tailLen_p2))- 0] = A_p3[offset_1];
			(*tailLen_p2) = (NI)((*tailLen_p2) + ((NI)1));
			offset_1 = (NI)(offset_1 + ((NI)1));
		} LA18: ;
	}
	}BeforeRet_: ;
}
static N_INLINE(void, absorbFinalPartsWithDomain__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u787)(NU64* S_p0, NI rateBytes_p1, NU8 domain_p2, NU8* A_p3, NI A_p3Len_0) {
	tyArray__k5CantrhGuvnhsRWsHF5HA tail_1;
	NI tailLen_1;
	NI i_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)tail_1, sizeof(tyArray__k5CantrhGuvnhsRWsHF5HA));
	tailLen_1 = ((NI)0);
	i_1 = ((NI)0);
	absorbPartState__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u766(S_p0, tail_1, (&tailLen_1), A_p3, A_p3Len_0, rateBytes_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	i_1 = tailLen_1;
	{
		while (1) {
			if (!(i_1 < rateBytes_p1)) goto LA2;
			tail_1[(i_1)- 0] = ((NU8)0);
			i_1 = (NI)(i_1 + ((NI)1));
		} LA2: ;
	}
	tail_1[(tailLen_1)- 0] = (NU8)(tail_1[(tailLen_1)- 0] ^ domain_p2);
	tail_1[((NI)(rateBytes_p1 - ((NI)1)))- 0] = (NU8)(tail_1[((NI)(rateBytes_p1 - ((NI)1)))- 0] ^ ((NU8)128));
	absorbBlock__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u556(S_p0, tail_1, 168, ((NI)0), rateBytes_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, shake256AbsorbOnce__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u1125)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	absorbFinalPartsWithDomain__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u787(S_p0, ((NI)136), ((NU8)31), A_p1, A_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	keccakF1600Ref__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u613(S_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, store64Le__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u524)(NU8* A_p0, NI A_p0Len_0, NI o_p1, NU64 v_p2) {
	A_p0[o_p1] = ((NU8) ((NU64)(v_p2 & 255ULL)));
	A_p0[(NI)(o_p1 + ((NI)1))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)8))) & 255ULL)));
	A_p0[(NI)(o_p1 + ((NI)2))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)16))) & 255ULL)));
	A_p0[(NI)(o_p1 + ((NI)3))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)24))) & 255ULL)));
	A_p0[(NI)(o_p1 + ((NI)4))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)32))) & 255ULL)));
	A_p0[(NI)(o_p1 + ((NI)5))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)40))) & 255ULL)));
	A_p0[(NI)(o_p1 + ((NI)6))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)48))) & 255ULL)));
	A_p0[(NI)(o_p1 + ((NI)7))] = ((NU8) ((NU64)((NU64)((NU64)(v_p2) >> (NU64)(((NI)56))) & 255ULL)));
}
static N_INLINE(void, squeezeBytesState__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u633)(NU64* S_p0, NU8* dst_p1, NI dst_p1Len_0, NI rateBytes_p2) {
	NI i_1;
	tyArray__cdsir9aPB24hAk6k77P9b9bCA laneBytes_1;
	NI produced_1;
	NI take_1;
	NI blockBytes_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	i_1 = ((NI)0);
	produced_1 = ((NI)0);
	take_1 = ((NI)0);
	blockBytes_1 = ((NI)0);
	{
		while (1) {
			if (!(produced_1 < dst_p1Len_0)) goto LA2;
			blockBytes_1 = rateBytes_p2;
			{
				if (!((NI)(dst_p1Len_0 - produced_1) < blockBytes_1)) goto LA5_;
				blockBytes_1 = (NI)(dst_p1Len_0 - produced_1);
			}
LA5_: ;
			i_1 = ((NI)0);
			{
				while (1) {
					if (!((NI)(i_1 * ((NI)8)) < blockBytes_1)) goto LA8;
					store64Le__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u524(laneBytes_1, 8, ((NI)0), S_p0[(i_1)- 0]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					take_1 = (NI)(blockBytes_1 - (NI)(i_1 * ((NI)8)));
					{
						if (!(((NI)8) < take_1)) goto LA11_;
						take_1 = ((NI)8);
					}
LA11_: ;
					{
						NI j_1;
						NI i_2;
						j_1 = (NI)0;
						i_2 = ((NI)0);
						{
							while (1) {
								if (!(i_2 < take_1)) goto LA15;
								j_1 = i_2;
								dst_p1[(NI)((NI)(produced_1 + (NI)(i_1 * ((NI)8))) + j_1)] = laneBytes_1[(j_1)- 0];
								i_2 += ((NI)1);
							} LA15: ;
						}
					}
					i_1 = (NI)(i_1 + ((NI)1));
				} LA8: ;
			}
			produced_1 = (NI)(produced_1 + blockBytes_1);
			{
				if (!(produced_1 < dst_p1Len_0)) goto LA18_;
				keccakF1600Ref__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u613(S_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA18_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
}
static N_INLINE(void, squeezeBytesInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u678)(tyArray__ti0bWuszecJ2jGEjnJGmWg S0_p0, NU8* dst_p1, NI dst_p1Len_0, NI rateBytes_p2) {
	tyArray__ti0bWuszecJ2jGEjnJGmWg S_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimCopyMem((void*)S_1, (NIM_CONST void*)S0_p0, sizeof(tyArray__ti0bWuszecJ2jGEjnJGmWg));
	squeezeBytesState__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u633(S_1, dst_p1, dst_p1Len_0, rateBytes_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, shake256Into__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u615)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
	tyArray__ti0bWuszecJ2jGEjnJGmWg S_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)S_1, sizeof(tyArray__ti0bWuszecJ2jGEjnJGmWg));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = shake256OpenSslInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u270(dst_p0, dst_p0Len_0, A_p1, A_p1Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	shake256AbsorbOnce__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u1125(S_1, A_p1, A_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	squeezeBytesInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u678(S_1, dst_p0, dst_p0Len_0, ((NI)136));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, shake256OpenSslWordsLeInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u427)(NU16* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
	NIM_BOOL result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tmp_1;
	tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw* ctx_1;
	NI i_1;
NIM_BOOL oldNimErrFin11_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	tmp_1.len = 0; tmp_1.p = NIM_NIL;
	ctx_1 = (tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw*)0;
	tmp_1.len = 0; tmp_1.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	i_1 = ((NI)0);
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = ensureOpenSslShakeLoaded__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u113();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(T4_)) goto LA5_;
		result = NIM_FALSE;
		eqdestroy___pureZtimes_u2632(tmp_1);
		goto BeforeRet_;
	}
LA5_: ;
	ctx_1 = osslMdCtxNew__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u61();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!(ctx_1 == ((tyObject_EVP_MD_CTX__of30b9apM2PWmw1jyTHQxEw*) NIM_NIL))) goto LA9_;
		result = NIM_FALSE;
		eqdestroy___pureZtimes_u2632(tmp_1);
		goto BeforeRet_;
	}
LA9_: ;
	{
		tyObject_EVP_MD__0MD0T8CQnxCXReL79cD6bTw* T14_;
		int T15_;
		T14_ = (tyObject_EVP_MD__0MD0T8CQnxCXReL79cD6bTw*)0;
		T14_ = osslShake256__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u60();
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		T15_ = (int)0;
		T15_ = osslDigestInitEx__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u63(ctx_1, T14_, NIM_NIL);
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		if (!!((T15_ == ((NI32)1)))) goto LA16_;
		result = NIM_FALSE;
		osslMdCtxFree__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u62(ctx_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		eqdestroy___pureZtimes_u2632(tmp_1);
		goto BeforeRet_;
	}
LA16_: ;
	{
		NIM_BOOL T20_;
		int T22_;
		T20_ = (NIM_BOOL)0;
		T20_ = (((NI)0) < A_p1Len_0);
		if (!(T20_)) goto LA21_;
		T22_ = (int)0;
		T22_ = osslDigestUpdate__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u64(ctx_1, ((void*) ((&A_p1[((NI)0)]))), ((size_t) (A_p1Len_0)));
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		T20_ = !((T22_ == ((NI32)1)));
LA21_: ;
		if (!T20_) goto LA23_;
		result = NIM_FALSE;
		osslMdCtxFree__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u62(ctx_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		eqdestroy___pureZtimes_u2632(tmp_1);
		goto BeforeRet_;
	}
LA23_: ;
	{
		NIM_BOOL T27_;
		int T29_;
		T27_ = (NIM_BOOL)0;
		T27_ = (((NI)0) < dst_p0Len_0);
		if (!(T27_)) goto LA28_;
		T29_ = (int)0;
		T29_ = osslDigestFinalXof__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u65(ctx_1, ((NU8*) ((&dst_p0[((NI)0)]))), ((size_t) ((NI)(dst_p0Len_0 * ((NI)2)))));
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		T27_ = !((T29_ == ((NI32)1)));
LA28_: ;
		if (!T27_) goto LA30_;
		result = NIM_FALSE;
		osslMdCtxFree__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u62(ctx_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		eqdestroy___pureZtimes_u2632(tmp_1);
		goto BeforeRet_;
	}
LA30_: ;
	result = NIM_TRUE;
	{
		LA11_:;
	}
	{
		oldNimErrFin11_ = *nimErr_; *nimErr_ = NIM_FALSE;
		osslMdCtxFree__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u62(ctx_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		*nimErr_ = oldNimErrFin11_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___pureZtimes_u2632(tmp_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, absorbFinalBlockWithDomain__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u563)(NU64* S_p0, NU8* A_p1, NI A_p1Len_0, NI o_p2, NI rateBytes_p3, NU8 domain_p4) {
	tyArray__k5CantrhGuvnhsRWsHF5HA blk_1;
	NI take_1;
	NI i_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)blk_1, sizeof(tyArray__k5CantrhGuvnhsRWsHF5HA));
	take_1 = ((NI)0);
	i_1 = ((NI)0);
	take_1 = (NI)(A_p1Len_0 - o_p2);
	{
		if (!(take_1 < ((NI)0))) goto LA3_;
		take_1 = ((NI)0);
	}
LA3_: ;
	i_1 = ((NI)0);
	{
		while (1) {
			if (!(i_1 < take_1)) goto LA6;
			blk_1[(i_1)- 0] = A_p1[(NI)(o_p2 + i_1)];
			i_1 = (NI)(i_1 + ((NI)1));
		} LA6: ;
	}
	blk_1[(take_1)- 0] = (NU8)(blk_1[(take_1)- 0] ^ domain_p4);
	blk_1[((NI)(rateBytes_p3 - ((NI)1)))- 0] = (NU8)(blk_1[((NI)(rateBytes_p3 - ((NI)1)))- 0] ^ ((NU8)128));
	absorbBlock__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u556(S_p0, blk_1, 168, ((NI)0), rateBytes_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, squeezeWordsLeInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u702)(tyArray__ti0bWuszecJ2jGEjnJGmWg S0_p0, NU16* dst_p1, NI dst_p1Len_0, NI rateBytes_p2) {
	tyArray__ti0bWuszecJ2jGEjnJGmWg S_1;
	NI produced_1;
	NI blockWords_1;
	NI lane_1;
	NU64 laneValue_1;
	NI wordIdx_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimCopyMem((void*)S_1, (NIM_CONST void*)S0_p0, sizeof(tyArray__ti0bWuszecJ2jGEjnJGmWg));
	produced_1 = ((NI)0);
	blockWords_1 = ((NI)0);
	lane_1 = ((NI)0);
	laneValue_1 = 0ULL;
	wordIdx_1 = ((NI)0);
	{
		while (1) {
			if (!(produced_1 < dst_p1Len_0)) goto LA2;
			blockWords_1 = (NI)(rateBytes_p2 / ((NI)2));
			{
				if (!((NI)(dst_p1Len_0 - produced_1) < blockWords_1)) goto LA5_;
				blockWords_1 = (NI)(dst_p1Len_0 - produced_1);
			}
LA5_: ;
			lane_1 = ((NI)0);
			{
				while (1) {
					if (!((NI)(lane_1 * ((NI)4)) < blockWords_1)) goto LA8;
					laneValue_1 = S_1[(lane_1)- 0];
					wordIdx_1 = (NI)(blockWords_1 - (NI)(lane_1 * ((NI)4)));
					{
						if (!(((NI)4) < wordIdx_1)) goto LA11_;
						wordIdx_1 = ((NI)4);
					}
LA11_: ;
					{
						if (!(((NI)0) < wordIdx_1)) goto LA15_;
						dst_p1[(NI)((NI)(produced_1 + (NI)(lane_1 * ((NI)4))) + ((NI)0))] = ((NU16) ((NU64)(laneValue_1 & 65535ULL)));
					}
LA15_: ;
					{
						if (!(((NI)1) < wordIdx_1)) goto LA19_;
						dst_p1[(NI)((NI)(produced_1 + (NI)(lane_1 * ((NI)4))) + ((NI)1))] = ((NU16) ((NU64)((NU64)((NU64)(laneValue_1) >> (NU64)(((NI)16))) & 65535ULL)));
					}
LA19_: ;
					{
						if (!(((NI)2) < wordIdx_1)) goto LA23_;
						dst_p1[(NI)((NI)(produced_1 + (NI)(lane_1 * ((NI)4))) + ((NI)2))] = ((NU16) ((NU64)((NU64)((NU64)(laneValue_1) >> (NU64)(((NI)32))) & 65535ULL)));
					}
LA23_: ;
					{
						if (!(((NI)3) < wordIdx_1)) goto LA27_;
						dst_p1[(NI)((NI)(produced_1 + (NI)(lane_1 * ((NI)4))) + ((NI)3))] = ((NU16) ((NU64)((NU64)((NU64)(laneValue_1) >> (NU64)(((NI)48))) & 65535ULL)));
					}
LA27_: ;
					lane_1 = (NI)(lane_1 + ((NI)1));
				} LA8: ;
			}
			produced_1 = (NI)(produced_1 + blockWords_1);
			{
				if (!(produced_1 < dst_p1Len_0)) goto LA31_;
				keccakF1600Ref__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u613(S_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA31_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, shake256WordsLeInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u627)(NU16* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
	tyArray__ti0bWuszecJ2jGEjnJGmWg S_1;
	NI rateBytes_1;
	NI offset_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)S_1, sizeof(tyArray__ti0bWuszecJ2jGEjnJGmWg));
	rateBytes_1 = ((NI)136);
	offset_1 = ((NI)0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = shake256OpenSslWordsLeInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u427(dst_p0, dst_p0Len_0, A_p1, A_p1Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	{
		while (1) {
			if (!((NI)(offset_1 + rateBytes_1) <= A_p1Len_0)) goto LA7;
			absorbBlock__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u556(S_1, A_p1, A_p1Len_0, offset_1, rateBytes_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			keccakF1600Ref__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u613(S_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			offset_1 = (NI)(offset_1 + rateBytes_1);
		} LA7: ;
	}
	absorbFinalBlockWithDomain__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u563(S_1, A_p1, A_p1Len_0, offset_1, rateBytes_1, ((NU8)31));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	keccakF1600Ref__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u613(S_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	squeezeWordsLeInto__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u702(S_1, dst_p0, dst_p0Len_0, rateBytes_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
