/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -mavx2 -maes -msse2 -O3 -fno-ident -fno-math-errno   -IK:\Progz\nim-2.2.6\lib -IF:\CodingMain\Tyr-Crypto\tests -o F:\CodingMain\Tyr-Crypto\.nimcache\test_otter_perf_pq_r\@pprotocols@ssimd@sgeneric_u64.nim.c.o F:\CodingMain\Tyr-Crypto\.nimcache\test_otter_perf_pq_r\@pprotocols@ssimd@sgeneric_u64.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "immintrin.h"
#include <string.h>
#include "emmintrin.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef NU64 tyArray__WOK9agWVIFrysHjlc69b06uA[4];
typedef NU64 tyArray__NzKR9bw29cLPrd712Xt6Liiw[2];
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4319;
N_LIB_PRIVATE N_NIMCALL(__m256i, set1U64__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha395simd_u600)(NU64 v_p0) {
	__m256i result;
	result = _mm256_set1_epi64x(((NI64) (v_p0)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(__m256i, rotl64__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha395simd_u569)(__m256i A_p0, NI32 k_p1) {
	__m256i result;
	__m256i T1_;
	__m256i T2_;
	T1_ = _mm256_slli_epi64(A_p0, k_p1);
	T2_ = _mm256_srli_epi64(A_p0, (NI32)(((NI32)64) - k_p1));
	result = _mm256_or_si256(T1_, T2_);
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4319);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
N_LIB_PRIVATE N_NIMCALL(void, storeU64x4__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha395simd_u541)(__m256i A_p0, tyArray__WOK9agWVIFrysHjlc69b06uA Result) {
	tyArray__WOK9agWVIFrysHjlc69b06uA R_1;
	nimZeroMem((void*)Result, sizeof(tyArray__WOK9agWVIFrysHjlc69b06uA));
	nimZeroMem((void*)R_1, sizeof(tyArray__WOK9agWVIFrysHjlc69b06uA));
	_mm256_storeu_si256(((__m256i*) (((void*) ((&R_1[(((NI)0))- 0]))))), A_p0);
	nimCopyMem((void*)Result, (NIM_CONST void*)R_1, sizeof(tyArray__WOK9agWVIFrysHjlc69b06uA));
}
N_LIB_PRIVATE N_NIMCALL(__m128i, set1U64__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha395simd_u326)(NU64 v_p0) {
	__m128i result;
	result = _mm_set1_epi64x(((NI64) (v_p0)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(__m128i, rotl64__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha395simd_u295)(__m128i A_p0, NI32 k_p1) {
	__m128i result;
	__m128i T1_;
	__m128i T2_;
	T1_ = _mm_slli_epi64(A_p0, k_p1);
	T2_ = _mm_srli_epi64(A_p0, (NI32)(((NI32)64) - k_p1));
	result = _mm_or_si128(T1_, T2_);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, storeU64x2__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha395simd_u253)(__m128i A_p0, tyArray__NzKR9bw29cLPrd712Xt6Liiw Result) {
	tyArray__NzKR9bw29cLPrd712Xt6Liiw R_1;
	nimZeroMem((void*)Result, sizeof(tyArray__NzKR9bw29cLPrd712Xt6Liiw));
	nimZeroMem((void*)R_1, sizeof(tyArray__NzKR9bw29cLPrd712Xt6Liiw));
	_mm_storeu_si128(((__m128i*) (((void*) ((&R_1[(((NI)0))- 0]))))), A_p0);
	nimCopyMem((void*)Result, (NIM_CONST void*)R_1, sizeof(tyArray__NzKR9bw29cLPrd712Xt6Liiw));
}
