/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -mavx2 -maes -msse2 -O3 -fno-ident -fno-math-errno   -IK:\Progz\nim-2.2.6\lib -IF:\CodingMain\Tyr-Crypto\tests -o F:\CodingMain\Tyr-Crypto\.nimcache\test_otter_perf_pq_r\@pprotocols@scustom_crypto@skyber@ssymmetric.nim.c.o F:\CodingMain\Tyr-Crypto\.nimcache\test_otter_perf_pq_r\@pprotocols@scustom_crypto@skyber@ssymmetric.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw;
typedef struct tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__Eio1jF59abEpv9bLmutTDQvQ tySequence__Eio1jF59abEpv9bLmutTDQvQ;
typedef struct tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content;
typedef struct tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__Eio1jF59abEpv9bLmutTDQvQ {
  NI len; tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__Eio1jF59abEpv9bLmutTDQvQ trace;
	Exception* up;
};
struct tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA {
	Exception Sup;
};
struct tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw {
	tyObject_CatchableError__scUEQ6c1HM0ixYGwcQfRNA Sup;
};
typedef NU8 tyArray__1S3PkXs1i9a3odYVGYxTIlQ[33];
struct tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__Eio1jF59abEpv9bLmutTDQvQ_Content { NI cap; tyObject_StackTraceEntry__xt2NQlld35KOToHY8kYTjw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, sha3512Into__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u1352)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, shake256Into__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u653)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(void, sha3256Into__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u1346)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0);
extern TNimTypeV2 NTIv2__w75dCcMqUymzJ8IcKO0oIw_;
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__0SwSAxpKxCzhbELP6GsfbQ_2 = { 35 | NIM_STRLIT_FLAG, "Kyber hashG output must be 64 bytes" };
static const NimStringV2 TM__0SwSAxpKxCzhbELP6GsfbQ_3 = {35, (NimStrPayload*)&TM__0SwSAxpKxCzhbELP6GsfbQ_2};
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__0SwSAxpKxCzhbELP6GsfbQ_4 = { 30 | NIM_STRLIT_FLAG, "Kyber PRF key must be 32 bytes" };
static const NimStringV2 TM__0SwSAxpKxCzhbELP6GsfbQ_5 = {30, (NimStrPayload*)&TM__0SwSAxpKxCzhbELP6GsfbQ_4};
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__0SwSAxpKxCzhbELP6GsfbQ_6 = { 35 | NIM_STRLIT_FLAG, "Kyber hashH output must be 32 bytes" };
static const NimStringV2 TM__0SwSAxpKxCzhbELP6GsfbQ_7 = {35, (NimStrPayload*)&TM__0SwSAxpKxCzhbELP6GsfbQ_6};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__0SwSAxpKxCzhbELP6GsfbQ_8 = { 33 | NIM_STRLIT_FLAG, "Kyber KDF output must be 32 bytes" };
static const NimStringV2 TM__0SwSAxpKxCzhbELP6GsfbQ_9 = {33, (NimStrPayload*)&TM__0SwSAxpKxCzhbELP6GsfbQ_8};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4319;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4319);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, hashGInto__OOZsrcZprotocolsZcustom95cryptoZkyberZsymmetric_u33)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw* T5_;
		if (!!((dst_p0Len_0 == ((NI)64)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw*) nimNewObj(sizeof(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw), NIM_ALIGNOF(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__w75dCcMqUymzJ8IcKO0oIw_);
		(*T5_).Sup.Sup.name = "ValueError";
		(*T5_).Sup.Sup.message = TM__0SwSAxpKxCzhbELP6GsfbQ_3;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T5_, "ValueError", "hashGInto", "symmetric.nim", 22);
goto BeforeRet_;
	}
LA3_: ;
	sha3512Into__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u1352(dst_p0, dst_p0Len_0, A_p1, A_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, prfInto__OOZsrcZprotocolsZcustom95cryptoZkyberZsymmetric_u93)(NU8* dst_p0, NI dst_p0Len_0, NU8* key_p1, NI key_p1Len_0, NU8 nonce_p2) {
	tyArray__1S3PkXs1i9a3odYVGYxTIlQ material_1;
	NI i_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)material_1, sizeof(tyArray__1S3PkXs1i9a3odYVGYxTIlQ));
	i_1 = ((NI)0);
	{
		tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw* T5_;
		if (!!((key_p1Len_0 == ((NI)32)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw*) nimNewObj(sizeof(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw), NIM_ALIGNOF(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__w75dCcMqUymzJ8IcKO0oIw_);
		(*T5_).Sup.Sup.name = "ValueError";
		(*T5_).Sup.Sup.message = TM__0SwSAxpKxCzhbELP6GsfbQ_5;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T5_, "ValueError", "prfInto", "symmetric.nim", 47);
goto BeforeRet_;
	}
LA3_: ;
	i_1 = ((NI)0);
	{
		while (1) {
			if (!(i_1 < ((NI)32))) goto LA7;
			material_1[(i_1)- 0] = key_p1[i_1];
			i_1 = (NI)(i_1 + ((NI)1));
		} LA7: ;
	}
	material_1[(((NI)32))- 0] = nonce_p2;
	shake256Into__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u653(dst_p0, dst_p0Len_0, material_1, 33);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, hashHInto__OOZsrcZprotocolsZcustom95cryptoZkyberZsymmetric_u3)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw* T5_;
		if (!!((dst_p0Len_0 == ((NI)32)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw*) nimNewObj(sizeof(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw), NIM_ALIGNOF(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__w75dCcMqUymzJ8IcKO0oIw_);
		(*T5_).Sup.Sup.name = "ValueError";
		(*T5_).Sup.Sup.message = TM__0SwSAxpKxCzhbELP6GsfbQ_7;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T5_, "ValueError", "hashHInto", "symmetric.nim", 11);
goto BeforeRet_;
	}
LA3_: ;
	sha3256Into__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u1346(dst_p0, dst_p0Len_0, A_p1, A_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, kdfInto__OOZsrcZprotocolsZcustom95cryptoZkyberZsymmetric_u63)(NU8* dst_p0, NI dst_p0Len_0, NU8* A_p1, NI A_p1Len_0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw* T5_;
		if (!!((dst_p0Len_0 == ((NI)32)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw*) nimNewObj(sizeof(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw), NIM_ALIGNOF(tyObject_ValueError__w75dCcMqUymzJ8IcKO0oIw));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIv2__w75dCcMqUymzJ8IcKO0oIw_);
		(*T5_).Sup.Sup.name = "ValueError";
		(*T5_).Sup.Sup.message = TM__0SwSAxpKxCzhbELP6GsfbQ_9;
		(*T5_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T5_, "ValueError", "kdfInto", "symmetric.nim", 33);
goto BeforeRet_;
	}
LA3_: ;
	shake256Into__OOZsrcZprotocolsZcustom95cryptoZsha3Zsha3_u653(dst_p0, dst_p0Len_0, A_p1, A_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
