/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\msys64\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -mavx2 -maes -msse2 -O3 -fno-ident -fno-math-errno   -IK:\Progz\nim-2.2.6\lib -IF:\CodingMain\Tyr-Crypto\tests -o F:\CodingMain\Tyr-Crypto\.nimcache\test_otter_perf_pq_r\@psets.nim.c.o F:\CodingMain\Tyr-Crypto\.nimcache\test_otter_perf_pq_r\@psets.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len; tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw {
	tySequence__4eRCaZmrYLLw2k30GPTiMw data;
	NI counter;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
	NI Field0;
	NimStringV2 Field1;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE]; };
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u245)(NI x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pureZunittest_u1251)(tySequence__4eRCaZmrYLLw2k30GPTiMw* s_p0, NI len_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NI, rawGet__pureZunittest_u1271)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u601)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NI, nextTry__pureZcollectionsZsets_u42)(NI h_p0, NI maxHash_p1);
static N_INLINE(NIM_BOOL, mustRehash__pureZunittest_u1319)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZunittest_u1391)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0);
static N_INLINE(NI, rawGetKnownHC__pureZunittest_u1443)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0, NimStringV2 key_p1, NI hc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZunittest_u1500)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0, tySequence__4eRCaZmrYLLw2k30GPTiMw* data_p1, NimStringV2 key_p2, NI hc_p3, NI h_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2661)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZunittest_u1018)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4319;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4319);
	return result;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = nextPowerOfTwo__pureZmath_u245((NI)((NI)((NI)(count_p0 / ((NI)2)) + count_p0) + ((NI)4)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZunittest_u1084)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* dest_p0) {
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field1.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZunittest_u1081)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* dest_p0) {
	(*dest_p0).Field0 = 0;
	(*dest_p0).Field1.len = 0; (*dest_p0).Field1.p = NIM_NIL;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0) {
	NIM_BOOL result;
	result = !((hcode_p0 == ((NI)0)));
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1749)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1749(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZsets_u42)(NI h_p0, NI maxHash_p1) {
	NI result;
	result = (NI)((NI)(h_p0 + ((NI)1)) & maxHash_p1);
	return result;
}
static N_INLINE(NI, rawGet__pureZunittest_u1271)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u601(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	{
		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	{
		NI T8_;
		T8_ = t_p0.data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	T11_ = (t_p0.data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				T17_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			T21_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	result = (NI)(((NI)-1) - h_1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__pureZunittest_u1319)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	NI T4_;
	T1_ = (NIM_BOOL)0;
	T2_ = t_p0.data.len;
	T1_ = (T2_ < (NI)(t_p0.counter + (NI)(t_p0.counter / ((NI)2))));
	if (T1_) goto LA3_;
	T4_ = t_p0.data.len;
	T1_ = ((NI)(T4_ - t_p0.counter) < ((NI)4));
LA3_: ;
	result = T1_;
	return result;
}
static N_INLINE(NI, rawGetKnownHC__pureZunittest_u1443)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw t_p0, NimStringV2 key_p1, NI hc_p2) {
	NI result;
	NI h_1;
	NI T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (t_p0.data.len-1);
	h_1 = (NI)(hc_p2 & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				T12_ = (t_p0.data.p->data[h_1].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				T12_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				result = h_1;
				goto BeforeRet_;
			}
LA14_: ;
			T16_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	result = (NI)(((NI)-1) - h_1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZunittest_u1500)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0, tySequence__4eRCaZmrYLLw2k30GPTiMw* data_p1, NimStringV2 key_p2, NI hc_p3, NI h_p4) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI correctSizeX60gensym50__1;
		T3_ = (*data_p1).len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		correctSizeX60gensym50__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*s_p0).counter = ((NI)0);
		newSeq__pureZunittest_u1251((&(*s_p0).data), (correctSizeX60gensym50__1));
	}
LA4_: ;
	eqcopy___system_u2661((&(*data_p1).p->data[h_p4].Field1), key_p2);
	(*data_p1).p->data[h_p4].Field0 = hc_p3;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZunittest_u1018)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field1.p && !(dest_p0.p->data[colontmp_].Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].Field1.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__QeWl6B6ffS4pU6WWrtcrDw));
}
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZunittest_u1391)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0) {
	tySequence__4eRCaZmrYLLw2k30GPTiMw n_1;
	NI T1_;
	tySequence__4eRCaZmrYLLw2k30GPTiMw T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	T1_ = (*s_p0).data.len;
	newSeq__pureZunittest_u1251((&n_1), ((NI)(T1_ * ((NI)2))));
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*s_p0).data;
	(*s_p0).data = n_1;
	n_1 = T2_;
	{
		NI i_1;
		NI colontmp_;
		NI T4_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		T4_ = (n_1.len-1);
		colontmp_ = T4_;
		res_1 = ((NI)0);
		{
			while (1) {
				if (!(res_1 <= colontmp_)) goto LA6;
				i_1 = ((NI) (res_1));
				{
					NIM_BOOL T9_;
					NI j_1;
					NI T12_;
					tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* T13_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZsets_u39(n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T9_) goto LA10_;
					T12_ = (NI)0;
					T12_ = rawGetKnownHC__pureZunittest_u1443((*s_p0), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					j_1 = (NI)(((NI)-1) - T12_);
					T13_ = (tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw*)0;
					T13_ = s_p0;
					rawInsert__pureZunittest_u1500(T13_, (&(*s_p0).data), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0, j_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA10_: ;
				res_1 += ((NI)1);
			} LA6: ;
		}
	}
	eqdestroy___pureZunittest_u1018(n_1);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, incl__pureZunittest_u1217)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* s_p0, NimStringV2 key_p1) {
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI correctSizeX60gensym41__1;
		T3_ = (*s_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		correctSizeX60gensym41__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*s_p0).counter = ((NI)0);
		newSeq__pureZunittest_u1251((&(*s_p0).data), (correctSizeX60gensym41__1));
	}
LA4_: ;
	hc_1 = (NI)0;
	index_1 = rawGet__pureZunittest_u1271((*s_p0), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw* T15_;
		if (!(index_1 < ((NI)0))) goto LA8_;
		{
			NIM_BOOL T12_;
			T12_ = (NIM_BOOL)0;
			T12_ = mustRehash__pureZunittest_u1319((*s_p0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T12_) goto LA13_;
			enlarge__pureZunittest_u1391(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			index_1 = rawGetKnownHC__pureZunittest_u1443((*s_p0), key_p1, hc_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA13_: ;
		T15_ = (tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw*)0;
		T15_ = s_p0;
		rawInsert__pureZunittest_u1500(T15_, (&(*s_p0).data), key_p1, hc_1, (NI)(((NI)-1) - index_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*s_p0).counter += ((NI)1);
	}
LA8_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, len__pureZunittest_u931)(tyObject_HashSet__Z7G8Qmlgey1VEfv8cSZckw s_p0) {
	NI result;
	result = s_p0.counter;
	return result;
}
